# Generated by Django 2.0.3 on 2018-03-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitcoinBotResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(db_index=True, unique=True, max_length=500)),
                ('response', models.CharField(max_length=500)),
            ],
        ),
    ]
