# Generated by Django 2.1.2 on 2018-12-03 22:38

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_user_id', models.IntegerField()),
                ('from_user_id', models.IntegerField()),
                ('CTA_URL', models.URLField(max_length=255, null=True)),
                ('CTA_Text', models.CharField(max_length=255)),
                ('message_html', models.CharField(help_text='Html message', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
