# Generated by Django 2.1.2 on 2018-12-07 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=255)),
                ('CTA_URL', models.URLField(max_length=255, null=True)),
                ('CTA_Text', models.CharField(max_length=255)),
                ('message_html', models.CharField(help_text='Html message', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('from_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
