# Generated by Django 2.1.2 on 2018-12-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(default='NULL', max_length=255),
            preserve_default=False,
        ),
    ]
