# Generated by Django 2.1.2 on 2018-12-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='username',
        ),
    ]
