# Generated by Django 2.1.2 on 2018-12-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_remove_notification_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
