# Generated by Django 2.2.4 on 2020-06-09 19:44

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0118_auto_20200605_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('token_state', models.CharField(choices=[('open', 'open'), ('progress', 'progress'), ('completed', 'completed'), ('denied', 'denied')], db_index=True, default='open', max_length=50)),
                ('network', models.CharField(default='', max_length=255)),
                ('web3_created', models.DateTimeField(db_index=True)),
                ('token_name', models.CharField(max_length=50)),
                ('token_symbol', models.CharField(max_length=10, null=True)),
                ('token_address', models.CharField(max_length=50)),
                ('token_owner_address', models.CharField(blank=True, max_length=255)),
                ('total_minted', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total minted', max_digits=50, null=True)),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('tx_status', models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped')], db_index=True, default='na', max_length=9)),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('token_owner_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_created', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedemptionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('redemption_state', models.CharField(choices=[('request', 'requested'), ('accepted', 'accepted'), ('denied', 'denied'), ('completed', 'completed')], db_index=True, default='request', max_length=50)),
                ('network', models.CharField(default='', max_length=255)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total ptokens to redeem', max_digits=50, null=True)),
                ('txid', models.CharField(blank=True, max_length=255)),
                ('redemption_accepted', models.DateTimeField(null=True)),
                ('tx_status', models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped')], db_index=True, default='na', max_length=9)),
                ('web3_created', models.DateTimeField(null=True)),
                ('ptoken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptokens.PersonalToken')),
                ('redemption_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasePToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('token_name', models.CharField(max_length=50)),
                ('token_address', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=255)),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('tx_status', models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped')], db_index=True, default='na', max_length=9)),
                ('web3_created', models.DateTimeField(db_index=True)),
                ('token_holder_address', models.CharField(blank=True, max_length=255)),
                ('ptoken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptokens.PersonalToken')),
                ('token_holder_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptoken_purchases', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
