# Generated by Django 2.2.4 on 2020-06-03 11:56

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0109_profile_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('token_state', models.CharField(choices=[('open', 'open'), ('progress', 'progress'), ('completed', 'completed'), ('denied', 'denied')], db_index=True, default='open', max_length=50)),
                ('web3_type', models.CharField(default='token_network', max_length=50)),
                ('web3_created', models.DateTimeField(db_index=True)),
                ('token_name', models.CharField(max_length=50)),
                ('token_address', models.CharField(max_length=50)),
                ('token_owner_name', models.CharField(blank=True, max_length=255)),
                ('token_owner_address', models.CharField(blank=True, max_length=255)),
                ('total_minted', models.IntegerField(db_index=True, default=0, help_text='Total minted')),
                ('token_holders_count', models.IntegerField(db_index=True, default=0, help_text='How many users hold this token?')),
                ('txid', models.CharField(default='', max_length=255)),
                ('token_owner_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_created', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedemptionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('redemption_state', models.CharField(choices=[('request', 'requested'), ('accepted', 'accepted'), ('denied', 'denied'), ('completed', 'completed')], db_index=True, default='open', max_length=50)),
                ('web3_type', models.CharField(default='token_network', max_length=50)),
                ('reason', models.CharField(max_length=1000)),
                ('web3_created', models.DateTimeField(db_index=True)),
                ('buyer_address', models.CharField(max_length=50)),
                ('total', models.IntegerField(db_index=True, default=0, help_text='Total minted')),
                ('txid', models.CharField(default='', max_length=255)),
                ('buyer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_redemption', to='dashboard.Profile')),
                ('ptoken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptokens.PersonalToken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
