# Generated by Django 2.2.4 on 2020-06-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltoken',
            name='network',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
