# Generated by Django 2.2.4 on 2020-06-07 14:55

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20200607_1455'),
        ('ptokens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltoken',
            name='token_holders_count',
        ),
        migrations.RemoveField(
            model_name='personaltoken',
            name='token_owner_name',
        ),
        migrations.RemoveField(
            model_name='personaltoken',
            name='web3_type',
        ),
        migrations.RemoveField(
            model_name='redemptiontoken',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='redemptiontoken',
            name='buyer_profile',
        ),
        migrations.RemoveField(
            model_name='redemptiontoken',
            name='web3_type',
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='network',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='token_symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='tx_status',
            field=models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped')], db_index=True, default='na', max_length=9),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='redemptiontoken',
            name='network',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='redemptiontoken',
            name='redemption_accepted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redemptiontoken',
            name='redemption_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='redemptiontoken',
            name='tx_status',
            field=models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped')], db_index=True, default='na', max_length=9),
        ),
        migrations.AlterField(
            model_name='personaltoken',
            name='token_owner_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_created', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='personaltoken',
            name='total_minted',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total minted', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='redemptiontoken',
            name='reason',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='redemptiontoken',
            name='redemption_state',
            field=models.CharField(choices=[('request', 'requested'), ('accepted', 'accepted'), ('denied', 'denied'), ('completed', 'completed')], db_index=True, default='request', max_length=50),
        ),
        migrations.AlterField(
            model_name='redemptiontoken',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total ptokens to redeem', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='redemptiontoken',
            name='web3_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='PurchasePToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('token_name', models.CharField(max_length=50)),
                ('token_address', models.CharField(max_length=50)),
                ('network', models.CharField(default='', max_length=255)),
                ('txid', models.CharField(default='', max_length=255)),
                ('tx_status', models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped')], db_index=True, default='na', max_length=9)),
                ('web3_created', models.DateTimeField(db_index=True)),
                ('token_holder_address', models.CharField(blank=True, max_length=255)),
                ('ptoken', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptokens.PersonalToken')),
                ('token_holder_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptoken_purchases', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
