# Generated by Django 2.2.4 on 2020-06-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptokens', '0002_auto_20200617_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseptoken',
            name='ptoken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptoken_purchases', to='ptokens.PersonalToken'),
        ),
    ]
