# Generated by Django 2.2.4 on 2020-06-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptokens', '0002_auto_20200607_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltoken',
            name='token_owner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_created', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='purchaseptoken',
            name='ptoken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptokens.PersonalToken'),
        ),
    ]
