# Generated by Django 2.2.4 on 2020-07-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptokens', '0003_auto_20200628_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptiontoken',
            name='canceller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceller', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='redemptiontoken',
            name='redemption_state',
            field=models.CharField(choices=[('request', 'requested'), ('accepted', 'accepted'), ('denied', 'denied'), ('cancelled', 'canceled'), ('waiting_complete', 'waiting_complete'), ('completed', 'completed')], db_index=True, default='request', max_length=50),
        ),
    ]
