# Generated by Django 2.2.4 on 2020-06-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptokens', '0003_auto_20200607_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltoken',
            name='txid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseptoken',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='purchaseptoken',
            name='network',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseptoken',
            name='txid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='redemptiontoken',
            name='reason',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='redemptiontoken',
            name='txid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
