# Generated by Django 2.2.4 on 2020-07-24 10:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptokens', '0004_auto_20200720_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltoken',
            name='cached_balances',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='holders',
            field=models.PositiveIntegerField(default=0, help_text='Total Holders'),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='last_block',
            field=models.IntegerField(default=0, help_text='Last block used to calculate cached properties'),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='purchases',
            field=models.IntegerField(default=0, help_text='Number of purchases'),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='redemptions',
            field=models.IntegerField(default=0, help_text='Number of redemptions'),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='total_available',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total available', max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='total_purchased',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total purchases', max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='personaltoken',
            name='total_redeemed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total redeemed', max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='redemptiontoken',
            name='redemption_requester_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
