# Generated by Django 2.2.4 on 2020-07-31 07:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('ptokens', '0005_auto_20200724_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTokenEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('event', models.CharField(choices=[('mint_ptoken', 'Mint tokens'), ('burn_ptoken', 'Burn tokens'), ('update_supply', 'Update ptoken supply')], max_length=20)),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('tx_status', models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped')], db_index=True, default='na', max_length=9)),
                ('network', models.CharField(db_index=True, default='', max_length=255)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('ptoken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptokens.PersonalToken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
