# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
