# Generated by Django 2.2.4 on 2020-05-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='source_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
