# Generated by Django 2.2.24 on 2021-07-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200512_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='img_url',
            field=models.CharField(default='', max_length=600, null=True),
        ),
    ]
