# Generated by Django 2.2.3 on 2019-11-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='img_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
