# Generated by Django 2.2.3 on 2019-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_searchresult_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='img_url',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
