# Generated by Django 2.2.3 on 2019-11-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20191115_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
