# Generated by Django 2.0.3 on 2018-03-21 04:44

import django.contrib.postgres.fields
from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source_project', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=1)),
                ('amount_denomination', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_sync_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
