# Generated by Django 2.1.4 on 2018-12-26 17:16

import django.contrib.postgres.fields
from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('action_url', models.URLField(db_index=True, help_text='Where to send interested parties')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Plainext only please!')),
                ('source_project', models.CharField(help_text='The upstream project being linked it..', max_length=255)),
                ('amount', models.FloatField(default=1, null=True)),
                ('amount_denomination', models.CharField(blank=True, help_text='ex: ETH, LTC, BTC', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_sync_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='comma delimited', size=None)),
                ('github_handle', models.CharField(blank=True, max_length=255)),
                ('payout_str', models.CharField(blank=True, default='', help_text='string representation of the payout (only needed it amount/denomination cannot be filled out', max_length=255)),
                ('idx_fiat_price', models.DecimalField(decimal_places=4, default=0, max_digits=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
