# Generated by Django 2.0.3 on 2018-03-21 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_bounties', '0002_externalbounty_action_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalbounty',
            name='github_handle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='externalbounty',
            name='action_url',
            field=models.URLField(db_index=True, help_text='Where to send interested parties'),
        ),
        migrations.AlterField(
            model_name='externalbounty',
            name='amount_denomination',
            field=models.CharField(help_text='ex: ETH, LTC, BTC', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalbounty',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Plainext only please!'),
        ),
        migrations.AlterField(
            model_name='externalbounty',
            name='source_project',
            field=models.CharField(help_text='The upstream project being linked it..', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalbounty',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], help_text='comma delimited', size=None),
        ),
    ]
