# Generated by Django 2.0.3 on 2018-03-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_bounties', '0003_auto_20180321_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalbounty',
            name='idx_fiat_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='externalbounty',
            name='payout_str',
            field=models.CharField(blank=True, default='', help_text='string representation of the payout (only needed it amount/denomination cannot be filled out', max_length=255),
        ),
    ]
