# Generated by Django 2.0.3 on 2018-03-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_bounties', '0004_auto_20180321_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalbounty',
            name='amount',
            field=models.FloatField(default=1, null=True),
        ),
    ]
