# Generated by Django 2.1 on 2018-08-15 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_bounties', '0005_auto_20180327_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalbounty',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='comma delimited', size=None),
        ),
    ]
