# Generated by Django 2.1.2 on 2018-11-07 01:13

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_auto_20181101_1922'),
        ('bounty_requests', '0002_auto_20180824_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyRequestMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('last_feedback_sent', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
