# Generated by Django 2.1 on 2018-08-12 10:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import economy.models
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0105_auto_20180812_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('github_profile_link', models.URLField(blank=True, verbose_name='Github Profile Link')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Location')),
                ('job_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=50, verbose_name='Job Type')),
                ('apply_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Is this job active?')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60, null=True), size=None)),
                ('expiry_date', models.DateTimeField(default=jobs.models.get_expiry_time, verbose_name='Expiry Date')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company')),
                ('apply_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email for Job')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='dashboard.Profile')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job',
            },
        ),
    ]
