# Generated by Django 2.0.5 on 2018-05-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email for Job'),
        ),
    ]
