# Generated by Django 2.0.5 on 2018-05-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_apply_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_by_gitcoin_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Username of person who posted Job'),
        ),
    ]
