# Generated by Django 2.0.4 on 2018-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180505_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full-Time'), ('Part Time', 'Part-Time'), ('Contract', 'Contract')], max_length=50, verbose_name='Job Type'),
        ),
    ]
