# Generated by Django 2.0.5 on 2018-05-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_posted_by_gitcoin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='skill'),
        ),
    ]
