# Generated by Django 2.2.4 on 2020-01-30 15:51

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_on',
            field=models.DateTimeField(db_index=True, default=economy.models.get_time),
        ),
        migrations.AddField(
            model_name='answer',
            name='modified_on',
            field=models.DateTimeField(default=economy.models.get_time),
        ),
        migrations.AddField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(db_index=True, default=economy.models.get_time),
        ),
        migrations.AddField(
            model_name='question',
            name='modified_on',
            field=models.DateTimeField(default=economy.models.get_time),
        ),
    ]
