# Generated by Django 2.2.4 on 2020-02-01 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_profile_as_representation'),
        ('questions', '0002_auto_20200130_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to='dashboard.Tip'),
        ),
        migrations.AddField(
            model_name='question',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='dashboard.Tip'),
        ),
    ]
