# Generated by Django 2.1.5 on 2019-03-05 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify
import economy.models
from revenue.utils import sku_generator


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# revenue.migrations.0004_auto_20190123_2221
# revenue.migrations.0006_auto_20190123_2231

sku_names = [
    'kudos',
    'fee_free_marketplace',
    'codefund_impressions',
    'job_board_credits',
    'featured_bounties',
    'job_desc_attachment',
    'personal_consultation',
]

plan_entries = [
    {
        "name": 'Lite',
        "price": 30,
        "period": 30 * 24 * 60 * 60,
        "items": [
            {
                "quantity" : 1,
                "sku_name": "kudos"
            },
            {
                "quantity" : 1,
                "sku_name": "fee_free_marketplace"
            },
            {
                "quantity" : 1000,
                "sku_name": "codefund_impressions"
            },
            {
                "quantity" : 1,
                "sku_name": "job_board_credits"
            },
        ]
    },
    {
        "name": 'Premium',
        "price": 100,
        "period": 30 * 24 * 60 * 60,
        "items": [
            {
                "quantity" : 10,
                "sku_name": "kudos"
            },
            {
                "quantity" : 1,
                "sku_name": "fee_free_marketplace"
            },
            {
                "quantity" : 10000,
                "sku_name": "codefund_impressions"
            },
            {
                "quantity" : 1,
                "sku_name": "job_board_credits"
            },
            {
                "quantity" : 1,
                "sku_name": "featured_bounties"
            },
            {
                "quantity" : 1,
                "sku_name": "job_desc_attachment"
            },
            {
                "quantity" : 1,
                "sku_name": "personal_consultation"
            },
        ]
    },
]

def forwards_func(apps, schema_editor):
    ALaCartePurchase = apps.get_model('revenue', 'ALaCartePurchase')
    SKU = apps.get_model('revenue', 'SKU')

    avatar_sku = SKU.objects.create(
        name = 'Avatar Purchase',
        slug='avatar_purchase',
        sku=sku_generator(),
        )

    for alcp in ALaCartePurchase.objects.all():
        alcp.sku = avatar_sku
        alcp.save()

    for name in sku_names:
        SKU.objects.create(
            name=name,
            sku=sku_generator(),
            )
    Plan = apps.get_model('revenue', 'Plan')
    PlanItem = apps.get_model('revenue', 'PlanItem')

    for plan in plan_entries:
        plan_obj = Plan.objects.create(
            slug = slugify(plan['name']),
            name = (plan['name']),
            cost_per_period=plan['price'],
            period_length_seconds=plan['period'],
            )
        for item in plan['items']:
            PlanItem.objects.create(
                plan=plan_obj,
                quantity=item['quantity'],
                sku=SKU.objects.get(name=item['sku_name']),
                )


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_grant_request_ownership_change'),
        ('grants', '0020_grant_is_paid_plan'),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('code', models.CharField(help_text='The Coupon Code', max_length=255)),
                ('discount_per_period', models.DecimalField(decimal_places=2, help_text='Discount, per period, to be applied to this plan in USD. Must not be more than the price per period of the plan.', max_digits=50)),
                ('start_date', models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0), help_text='The start date for validity of this coupon')),
                ('end_date', models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0), help_text='The end date for validity of this coupon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('slug', models.CharField(help_text='The Slug', max_length=255)),
                ('name', models.CharField(help_text='The SKU Name', max_length=255)),
                ('cost_per_period', models.DecimalField(decimal_places=2, help_text='Cost of this plan in USD', max_digits=50)),
                ('period_length_seconds', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('quantity', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(help_text='The plan that this item is in', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='revenue.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('slug', models.CharField(help_text='The Slug', max_length=255)),
                ('name', models.CharField(help_text='The SKU Name', max_length=255)),
                ('sku', models.CharField(help_text='The SKU', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('grant_subscription', models.ForeignKey(help_text='The grants.subscription for this revenue subscription', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_subscription', to='grants.Subscription')),
                ('plan', models.ForeignKey(help_text='The plan for this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='revenue.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planitem',
            name='sku',
            field=models.ForeignKey(help_text='The sku that is in this item', on_delete=django.db.models.deletion.CASCADE, related_name='planitems', to='revenue.SKU'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='plan',
            field=models.ForeignKey(help_text='The plan that this coupon is for', on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='revenue.Plan'),
        ),
        migrations.AddField(
            model_name='alacartepurchase',
            name='sku',
            field=models.ForeignKey(help_text='The feature that was purchased', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alacartegoodpurchases', to='revenue.SKU'),
        ),
        migrations.AlterField(
            model_name='alacartepurchase',
            name='sku',
            field=models.ForeignKey(help_text='The feature that was purchased', on_delete=django.db.models.deletion.CASCADE, related_name='alacartegoodpurchases', to='revenue.SKU'),
        ),
        migrations.AddField(
            model_name='plan',
            name='grant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_plan', to='grants.Grant'),
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.AddField(
            model_name='plan',
            name='bounties_discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
