# Generated by Django 2.1.2 on 2018-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalgoodpurchase',
            name='primary_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
