# Generated by Django 2.1.2 on 2019-01-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('DigitalGoodPurchase', 'ALaCartePurchase')
    ]
