# Generated by Django 2.2.24 on 2021-09-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_auto_20200605_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalgoodpurchase',
            name='network',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
