# Generated by Django 2.1.2 on 2019-01-23 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0004_auto_20190123_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alacartepurchase',
            name='sku',
            field=models.ForeignKey(help_text='The feature that was purchased', on_delete=django.db.models.deletion.CASCADE, related_name='alacartegoodpurchases', to='revenue.SKU'),
        ),
    ]
