# Generated by Django 2.1.5 on 2019-03-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0016_grant_is_paid_plan'),
        ('revenue', '0006_auto_20190123_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_plan', to='grants.Grant'),
        ),
    ]
