# Generated by Django 2.1.5 on 2019-03-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0007_plan_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='grant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_plan', to='grants.Grant'),
        ),
    ]
