# Generated by Django 2.1.5 on 2019-03-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0008_auto_20190304_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='bounties_discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
