# Generated by Django 2.0.3 on 2018-04-25 17:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0060_tool_modifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('org', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, choices=[('1_5', '1 - 5'), ('5_10', '5 - 10'), ('10_15', '10 - 15'), ('15_20', '15 - 20'), ('20_', '20+')], max_length=5)),
                ('skills_offered', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], help_text='comma delimited', size=None)),
                ('skills_needed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], help_text='comma delimited', size=None)),
                ('available', models.BooleanField(default=False)),
                ('commitment_per_week', models.CharField(blank=True, choices=[('1_5', '1 - 5'), ('5_10', '5 - 10'), ('10_15', '10 - 15'), ('15_20', '15 - 20'), ('20_', '20+')], max_length=5)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
