# Generated by Django 2.2.4 on 2020-01-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20200118_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='mentee_join',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessions',
            name='mentee_leave',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessions',
            name='mentor_join',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessions',
            name='mentor_leave',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
