# Generated by Django 2.2.4 on 2020-01-22 09:18

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_auto_20200122_0918'),
        ('mentor', '0003_auto_20200121_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('active', models.BooleanField(default=False)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('period_time', models.CharField(choices=[('5 minutes', '5 minutes'), ('15 minutes', '15 minutes'), ('30 minutes', '30 minutes'), ('1 hour', '1 hour'), ('2 hours', '2 hour'), ('6 hours', '6 hour')], default='1 hour', max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_availability', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
