# Generated by Django 2.2.24 on 2022-09-02 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_score', '0002_auto_20220902_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr15trustscore',
            name='is_sybil',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is sybil'),
        ),
        migrations.AddField(
            model_name='gr15trustscore',
            name='notes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True, verbose_name='Notes'),
        ),
    ]
