# Generated by Django 2.2.24 on 2022-09-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_score', '0003_auto_20220902_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gr15trustscore',
            name='trust_bonus',
            field=models.DecimalField(decimal_places=18, max_digits=64, verbose_name='Trust bonus'),
        ),
    ]
