# Generated by Django 2.2.24 on 2022-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_score', '0004_auto_20220904_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr15trustscore',
            name='trust_bonus_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
