# Generated by Django 2.2.24 on 2022-09-08 12:54

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport_score', '0005_gr15trustscore_trust_bonus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gr15trustscore',
            name='notes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='gr15trustscore',
            name='stamps',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Scored stamps'),
        ),
        migrations.AlterField(
            model_name='gr15trustscore',
            name='user',
            field=models.ForeignKey(help_text='The owner of the trust bonus', on_delete=django.db.models.deletion.CASCADE, related_name='gr15_trustbonus_set', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
