# Generated by Django 2.2.4 on 2020-01-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmentor', '0002_auto_20200124_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionscheduling',
            name='mentor',
            field=models.ManyToManyField(help_text='Select mentor', limit_choices_to={'persona_is_mentor': True}, to='dashboard.Profile'),
        ),
    ]
