# Generated by Django 2.2.4 on 2020-01-25 19:25

import django.core.validators
from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_auto_20200124_0552'),
        ('gitmentor', '0003_auto_20200124_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('session_datetime', models.DateTimeField(help_text='Requested session date and time.')),
                ('session_duration', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)])),
                ('session_cost', models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(999)])),
                ('session_state', models.CharField(blank=True, choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('Rejected', 'rejected')], db_index=True, max_length=50)),
                ('mentor', models.ManyToManyField(help_text='Select mentor', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SessionScheduling',
        ),
    ]
