# Generated by Django 2.2.4 on 2020-01-26 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmentor', '0004_auto_20200125_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='session_cost',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
