# Generated by Django 2.2.4 on 2020-01-28 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmentor', '0005_auto_20200126_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='mentee_address',
            field=models.CharField(blank=True, db_index=True, default='0xd21aEff7Fc73AB5D608808c99427B1B9084D372e', max_length=256),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='session_cost',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
