# Generated by Django 2.2.4 on 2020-01-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmentor', '0007_auto_20200129_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='gitmentor_session_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
