# Generated by Django 2.2.4 on 2020-09-26 03:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0149_add_twitter_verify_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('invite_codes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('gameboard', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('title', models.TextField(blank=True, max_length=500)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('creator', models.ForeignKey(help_text="The game administrator's profile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_created', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('message', models.TextField(blank=True, max_length=5000)),
                ('game', models.ForeignKey(help_text='Link to Game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='governance.Game')),
                ('sender', models.ForeignKey(help_text="The game feed update creators's profile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_feed', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
