# Generated by Django 2.2.4 on 2020-09-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_game_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamefeed',
            name='message',
        ),
    ]
