# Generated by Django 2.0.7 on 2018-07-23 14:26

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0090_auto_20180723_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('title', models.CharField(max_length=255)),
                ('pitch', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_url', models.URLField(db_index=True)),
                ('current_funding', models.DecimalField(decimal_places=4, default=0, max_digits=50)),
                ('goal_funding', models.DecimalField(decimal_places=4, default=0, max_digits=50)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
