# Generated by Django 2.1.1 on 2018-09-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20180917_2137'),
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='current_funding',
            new_name='amountGoal',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='goal_funding',
            new_name='amountReceived',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='pitch',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='profile',
        ),
        migrations.AddField(
            model_name='grant',
            name='adminAddress',
            field=models.CharField(default='0x0', max_length=255),
        ),
        migrations.AddField(
            model_name='grant',
            name='adminProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_admin', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='grant',
            name='frequency',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='grant',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='grant',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='teamMemberProfiles',
            field=models.ManyToManyField(related_name='grant_team_members', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='title',
            field=models.CharField(default='Very grant. Much cool.', max_length=255),
        ),
    ]
