# Generated by Django 2.1.2 on 2018-10-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='team_member_profiles',
            new_name='team_members',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='status',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='image_url',
        ),
    ]
