# Generated by Django 2.1.2 on 2018-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='network',
            field=models.CharField(default='mainnet', max_length=16),
        ),
    ]
