# Generated by Django 2.1.2 on 2018-12-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='period_seconds',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='token_address',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='token_amount',
        ),
    ]
