# Generated by Django 2.1.2 on 2018-10-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_auto_20181025_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='tx_id',
            field=models.CharField(default='0x0', help_text='The transaction ID of the Contribution.', max_length=255),
        ),
    ]
