# Generated by Django 2.1.2 on 2018-10-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_auto_20181015_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='subscription',
            field=models.ForeignKey(help_text='The associated Subscription.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_contribution', to='grants.Subscription'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='tx_id',
            field=models.CharField(default='0x0', help_text='The transaction ID of the Contribution.', max_length=255),
        ),
        migrations.AlterField(
            model_name='grant',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether or not the Grant is active.'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='admin_address',
            field=models.CharField(default='0x0', help_text='The wallet address for the administrator of this Grant.', max_length=255),
        ),
        migrations.AlterField(
            model_name='grant',
            name='admin_profile',
            field=models.ForeignKey(help_text="The Grant administrator's profile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_admin', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount_goal',
            field=models.DecimalField(decimal_places=4, default=1, help_text='The contribution goal amount for the Grant.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount_received',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The total amount received for the Grant.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='block_number',
            field=models.CharField(default=0, help_text='The Ethereum block number during creation of the Grant.', max_length=9),
        ),
        migrations.AlterField(
            model_name='grant',
            name='contract_address',
            field=models.CharField(default='0x0', help_text='The contract address of the Grant.', max_length=255),
        ),
        migrations.AlterField(
            model_name='grant',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The description of the Grant.'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='frequency',
            field=models.DecimalField(decimal_places=0, default=30, help_text='The payout frequency of the Grant.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='network',
            field=models.CharField(default='mainnet', help_text='The network in which the Grant contract resides.', max_length=8),
        ),
        migrations.AlterField(
            model_name='grant',
            name='reference_url',
            field=models.URLField(blank=True, help_text='The associated reference URL of the Grant.'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='required_gas_price',
            field=models.DecimalField(decimal_places=0, default='0', help_text='The required gas price for the Grant.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='team_members',
            field=models.ManyToManyField(help_text='The team members contributing to this Grant.', related_name='grant_teams', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='title',
            field=models.CharField(default='', help_text='The title of the Grant.', max_length=255),
        ),
        migrations.AlterField(
            model_name='grant',
            name='token_address',
            field=models.CharField(default='0x0', help_text='The token address to be used with the Grant.', max_length=255),
        ),
        migrations.AlterField(
            model_name='grant',
            name='transaction_hash',
            field=models.CharField(default='0x0', help_text='The transaction hash of the Grant.', max_length=255),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='completion_date',
            field=models.DateField(blank=True, default=None, help_text='The Milestone completion date.', null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(help_text='The Milestone description.'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(help_text='The requested Milestone completion date.'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='grant',
            field=models.ForeignKey(help_text='The associated Grant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='grants.Grant'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(help_text='The Milestone title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether or not the Subscription is active.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount_per_period',
            field=models.DecimalField(decimal_places=4, default=1, help_text='The promised contribution amount per period.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='contributor_address',
            field=models.CharField(default='', help_text="The contributor's wallet address of the Subscription.", max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='contributor_profile',
            field=models.ForeignKey(help_text="The Subscription contributor's Profile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_contributor', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='contributor_signature',
            field=models.CharField(default='', help_text="The contributor's signature.", max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gas_price',
            field=models.DecimalField(decimal_places=4, default=1, help_text='The required gas price for the Subscription.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='grant',
            field=models.ForeignKey(help_text='The associated Grant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='grants.Grant'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='network',
            field=models.CharField(default='mainnet', help_text='The network in which the Subscription resides.', max_length=8),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period_seconds',
            field=models.DecimalField(decimal_places=0, default=2592000, help_text='The subscription period length.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_hash',
            field=models.CharField(default='', help_text="The contributor's Subscription hash.", max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='token_address',
            field=models.CharField(default='0x0', help_text='The token address to be used with the Subscription.', max_length=255),
        ),
    ]
