# Generated by Django 2.1.2 on 2018-10-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_auto_20181010_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='network',
            field=models.CharField(default='mainnet', max_length=16),
        ),
    ]
