# Generated by Django 2.1.2 on 2018-11-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_auto_20181119_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='period_seconds',
        ),
        migrations.AddField(
            model_name='grant',
            name='token_symbol',
            field=models.CharField(default='0x0', help_text='The token symbol to be used with the Grant.', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.DecimalField(decimal_places=0, default=0, help_text='The real payout frequency of the Subscription in seconds.', max_digits=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='frequency_uint',
            field=models.CharField(default='', help_text='The text version of frequency units e.g. days, months', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='real_period_seconds',
            field=models.DecimalField(decimal_places=0, default=2592000, help_text='The real payout frequency of the Subscription in seconds.', max_digits=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='token_symbol',
            field=models.CharField(default='0x0', help_text='The token symbol to be used with the Subscription.', max_length=255),
        ),
    ]
