# Generated by Django 2.1.2 on 2018-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_contribution_tx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='frequency',
            field=models.DecimalField(decimal_places=0, default=2592000, help_text='The payout frequency of the Grant.', max_digits=50),
        ),
    ]
