# Generated by Django 2.1.2 on 2018-11-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_auto_20181120_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='frequency_uint',
            new_name='frequency_unit',
        ),
    ]
