# Generated by Django 2.1.1 on 2018-09-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_auto_20180918_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='amountGoal',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=50),
        ),
    ]
