# Generated by Django 2.1.2 on 2018-12-03 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_auto_20181203_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_contribution_date',
            field=models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0), help_text='The last contribution date'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_contribution_date',
            field=models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0), help_text='The last contribution date'),
        ),
    ]
