# Generated by Django 2.1.4 on 2019-01-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_auto_20190104_1931'),
        ('grants', '0002_auto_20190104_2155'),
    ]

    operations = [
    ]
