# Generated by Django 2.1.2 on 2018-12-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_auto_20181203_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='amount_goal',
            field=models.DecimalField(decimal_places=4, default=1, help_text='The contribution goal amount for the Grant in DAI.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount_received',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The total amount received for the Grant in USDT/DAI.', max_digits=50),
        ),
    ]
