# Generated by Django 2.1.2 on 2018-12-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_auto_20181203_2313'),
        ('grants', '0004_auto_20181203_2343'),
    ]

    operations = [
    ]
