# Generated by Django 2.1.1 on 2018-09-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_auto_20180918_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='frequency',
            field=models.DecimalField(decimal_places=0, default=30, max_digits=50),
        ),
    ]
