# Generated by Django 2.1.2 on 2018-11-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_grant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='token_symbol',
            field=models.CharField(default='', help_text='The token symbol to be used with the Grant.', max_length=255),
        ),
    ]
