# Generated by Django 2.1.1 on 2018-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_auto_20180918_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='tokenAddress',
            field=models.CharField(default='0x0', max_length=255),
        ),
    ]
