# Generated by Django 2.1.4 on 2019-01-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_auto_20190109_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='cancel_tx_confirmed',
            field=models.BooleanField(default=False, help_text='Whether or not the grant cancellation transaction has been confirmed on chain.'),
        ),
        migrations.AddField(
            model_name='grant',
            name='deploy_tx_confirmed',
            field=models.BooleanField(default=False, help_text='Whether or not the grant deployment transaction has been confirmed on chain.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_tx_confirmed',
            field=models.BooleanField(default=False, help_text='Whether or not the subscription cancellation transaction has been confirmed on chain.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='end_approved_tx_confirmed',
            field=models.BooleanField(default=False, help_text='Whether or not the end approve transaction has been confirmed on chain.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='new_approved_tx_confirmed',
            field=models.BooleanField(default=False, help_text='Whether or not the new approve transaction has been confirmed on chain.'),
        ),
    ]
