# Generated by Django 2.1.2 on 2018-12-06 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_merge_20181204_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='tx_id',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='transaction_hash',
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_tx_id',
            field=models.CharField(default='0x0', help_text='The transaction id for the contribution.', max_length=255),
        ),
        migrations.AddField(
            model_name='grant',
            name='deploy_tx_id',
            field=models.CharField(default='0x0', help_text='The transaction id for contract deployment.', max_length=255),
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_cancel_tx_id',
            field=models.CharField(default='0x0', help_text='The transaction id for endContract.', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_cancel_tx_id',
            field=models.CharField(default='0x0', help_text='The transaction id for cancelSubscription.', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_end_approve_tx_id',
            field=models.CharField(default='0x0', help_text='The transaction id for subscription approve().', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_new_approve_tx_id',
            field=models.CharField(default='0x0', help_text='The transaction id for subscription approve().', max_length=255),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount_goal',
            field=models.DecimalField(decimal_places=4, default=1, help_text='The monthly contribution goal amount for the Grant in DAI.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_contribution_date',
            field=models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0), help_text='The next contribution date'),
        ),
    ]
