# Generated by Django 2.1.4 on 2019-01-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_grant_request_ownership_change'),
        ('grants', '0006_auto_20190111_2350'),
    ]

    operations = [
    ]
