# Generated by Django 2.1.2 on 2018-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_auto_20181206_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='grant_cancel_tx_id',
            new_name='cancel_tx_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='sub_cancel_tx_id',
            new_name='cancel_tx_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='sub_end_approve_tx_id',
            new_name='end_approve_tx_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='sub_new_approve_tx_id',
            new_name='new_approve_tx_id',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='contribution_tx_id',
        ),
        migrations.AddField(
            model_name='contribution',
            name='tx_id',
            field=models.CharField(default='0x0', help_text='The transaction ID of the Contribution.', max_length=255),
        ),
    ]
