# Generated by Django 2.1.2 on 2018-11-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_auto_20181121_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['-created_on']},
        ),
    ]
