# Generated by Django 2.1.1 on 2018-09-20 21:15

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20180917_2137'),
        ('grants', '0006_grant_tokenaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('txId', models.CharField(default='0x0', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('status', models.BooleanField(default=True)),
                ('subscriptionHash', models.CharField(default='', max_length=255)),
                ('contributorSignature', models.CharField(default='', max_length=255)),
                ('contributorAddress', models.CharField(default='', max_length=255)),
                ('amountPerPeriod', models.DecimalField(decimal_places=4, default=1, max_digits=50)),
                ('tokenAddress', models.CharField(default='0x0', max_length=255)),
                ('gasPrice', models.DecimalField(decimal_places=4, default=1, max_digits=50)),
                ('network', models.CharField(default='0x0', max_length=255)),
                ('contributorProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_contributor', to='dashboard.Profile')),
                ('grantPk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_subscription', to='grants.Grant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Stakeholder',
        ),
        migrations.AddField(
            model_name='contribution',
            name='subscriptionPk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_contribution', to='grants.Subscription'),
        ),
    ]
