# Generated by Django 2.1.2 on 2018-11-26 20:34

from django.db import migrations, models
import django_extensions.db.fields


def update_grants(apps, schema_editor):
    """Handle the data migration for grant.ceontract_version."""
    Grant = apps.get_model('grants', 'Grant')

    grants = Grant.objects.all()
    for grant in grants:
        grant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_auto_20181126_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='contract_version',
            field=models.DecimalField(decimal_places=0, default=0, help_text='The contract version the Grant.', max_digits=3),
        ),
                migrations.RunPython(update_grants),
    ]
