# Generated by Django 2.1.4 on 2019-01-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_merge_20190115_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='end_approved_tx_confirmed',
            new_name='end_approve_tx_confirmed',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='new_approved_tx_confirmed',
            new_name='new_approve_tx_confirmed',
        ),
    ]
