# Generated by Django 2.1.1 on 2018-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_auto_20180920_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='adminAddress',
            new_name='admin_address',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='amountGoal',
            new_name='amount_goal',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='amountReceived',
            new_name='amount_received',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='tokenAddress',
            new_name='contract_address',
        ),
        migrations.AddField(
            model_name='grant',
            name='network',
            field=models.CharField(default='0x0', max_length=255),
        ),
        migrations.AddField(
            model_name='grant',
            name='token_address',
            field=models.CharField(default='0x0', max_length=255),
        ),
    ]
