# Generated by Django 2.1.2 on 2018-12-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_auto_20181205_2310'),
        ('grants', '0007_auto_20181207_1721'),
    ]

    operations = [
    ]
