# Generated by Django 2.1.2 on 2018-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_auto_20181126_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='contract_version',
            field=models.DecimalField(decimal_places=0, default=0, help_text='The contract version the Grant.', max_digits=3),
        ),
    ]
