# Generated by Django 2.1.7 on 2019-02-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0008_auto_20190129_0443'),
        ('grants', '0008_auto_20190201_0906'),
    ]

    operations = [
    ]
