# Generated by Django 2.1.2 on 2019-02-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0008_auto_20190201_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='clr_matching',
            field=models.DecimalField(decimal_places=0, default=0, help_text='The CLR matching amount', max_digits=20),
        ),
    ]
