# Generated by Django 2.1.1 on 2018-09-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0008_auto_20180927_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='adminProfile',
            new_name='admin_profile',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='teamMemberProfiles',
            new_name='team_member_profiles',
        ),
    ]
