# Generated by Django 2.1.4 on 2019-01-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0008_auto_20190115_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether or not the Grant is active.'),
        ),
    ]
