# Generated by Django 2.1.4 on 2019-02-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_grant_image_css'),
        ('grants', '0009_auto_20190118_1835'),
    ]

    operations = [
    ]
