# Generated by Django 2.1.2 on 2018-12-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_auto_20181211_1320'),
        ('grants', '0009_auto_20181213_2243'),
    ]

    operations = [
    ]
