# Generated by Django 2.1.1 on 2018-09-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0009_auto_20180927_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='subscriptionPk',
            new_name='subscription_pk',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='txId',
            new_name='tx_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='amountPerPeriod',
            new_name='amount_per_period',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='contributorAddress',
            new_name='contributor_address',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='contributorProfile',
            new_name='contributor_profile',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='contributorSignature',
            new_name='contributor_signature',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='gasPrice',
            new_name='gas_price',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='grantPk',
            new_name='grant_pk',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriptionHash',
            new_name='subscription_hash',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='tokenAddress',
            new_name='token_address',
        ),
    ]
