# Generated by Django 2.1.7 on 2019-02-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0009_merge_20190218_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='contributor_signature',
            field=models.CharField(blank=True, default='', help_text="The contributor's signature.", max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_hash',
            field=models.CharField(blank=True, default='', help_text="The contributor's Subscription hash.", max_length=255),
        ),
    ]
