# Generated by Django 2.1.1 on 2018-09-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0010_auto_20180927_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='required_gas_price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=50),
        ),
    ]
