# Generated by Django 2.1.4 on 2019-02-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0010_merge_20190205_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='image_css',
            field=models.CharField(blank=True, default='', help_text='additional CSS to attach to the grant-banner img.', max_length=255),
        ),
    ]
