# Generated by Django 2.1.1 on 2018-10-01 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0011_grant_required_gas_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='grant_pk',
        ),
        migrations.AddField(
            model_name='grant',
            name='transaction_hash',
            field=models.CharField(default='0x0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='grants.Grant'),
        ),
    ]
