# Generated by Django 2.1.2 on 2018-12-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0011_auto_20181217_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='num_tx_approved',
            field=models.DecimalField(decimal_places=4, default=1, help_text='The number of transactions approved for the Subscription.', max_digits=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='num_tx_processed',
            field=models.DecimalField(decimal_places=4, default=1, help_text='The number of transactoins processed by the subminer for the Subscription.', max_digits=50),
        ),
    ]
