# Generated by Django 2.1.2 on 2019-02-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0008_auto_20190130_1822'),
        ('grants', '0011_auto_20190221_2050'),
    ]

    operations = [
    ]
