# Generated by Django 2.1.4 on 2019-02-05 22:08

from dashboard.utils import has_tx_mined
from django.db import migrations
from grants.models import Grant, Subscription

def confirm_txs(apps, schema_editor):
    for grant in Grant.objects.filter(active=True).exclude(deploy_tx_id='0x0'):
        if has_tx_mined(grant.deploy_tx_id, grant.network):
            grant.deploy_tx_confirmed = True
            grant.save()

    for grant in Grant.objects.filter(active=False).exclude(cancel_tx_id='0x0'):
        if has_tx_mined(grant.cancel_tx_id, grant.network):
            grant.cancel_tx_confirmed = True
            grant.save()

    for sub in Subscription.objects.filter(active=True).exclude(new_approve_tx_id='0x0'):
        if has_tx_mined(sub.new_approve_tx_id, sub.network):
            sub.new_approve_tx_confirmed = True
            sub.save()

    for sub in Subscription.objects.filter(active=False).exclude(cancel_tx_id='0x0').exclude(end_approve_tx_id='0x0'):
        if has_tx_mined(sub.end_approve_tx_id, sub.network) and has_tx_mined(sub.cancel_tx_id, sub.network):
            sub.cancel_tx_confirmed = True
            sub.end_approve_tx_confirmed = True
            sub.save()

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0011_auto_20190205_1745'),
    ]

    operations = [
        migrations.RunPython(confirm_txs, backwards),
    ]
