# Generated by Django 2.1.2 on 2018-12-19 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_labsresearch'),
        ('grants', '0011_auto_20181217_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='request_ownership_change',
            field=models.ForeignKey(help_text="The Grant's potential new administrator profile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_ownership_change', to='dashboard.Profile'),
        ),
    ]
