# Generated by Django 2.1.2 on 2018-12-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0011_auto_20181217_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='error',
            field=models.BooleanField(default=False, help_text='Whether or not the Subscription is erroring out.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subminer_comments',
            field=models.TextField(blank=True, default='', help_text='Comments left by the subminer.'),
        ),
    ]
