# Generated by Django 2.1.4 on 2019-02-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0012_auto_20190205_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='contributor_signature',
            field=models.CharField(blank=True, default='', help_text="The contributor's signature.", max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_hash',
            field=models.CharField(blank=True, default='', help_text="The contributor's Subscription hash.", max_length=255),
        ),
    ]
