# Generated by Django 2.1.2 on 2019-02-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0012_auto_20190222_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount_per_period_usdt',
            field=models.DecimalField(decimal_places=18, default=0, help_text='The amount per contribution period in USDT', max_digits=64),
        ),
    ]
