# Generated by Django 2.1.2 on 2018-12-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0012_auto_20181223_2245'),
        ('grants', '0013_auto_20181224_0427'),
    ]

    operations = [
    ]
