# Generated by Django 2.1.5 on 2019-02-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0012_merge_20190221_2246'),
        ('grants', '0014_matchpledge'),
    ]

    operations = [
    ]
