# Generated by Django 2.1.2 on 2018-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0014_merge_20181226_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='monthly_amount_subscribed',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The monthly subscribed to by contributors USDT/DAI.', max_digits=50),
        ),
    ]
