# Generated by Django 2.1.5 on 2019-03-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0015_merge_20190225_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='is_paid_plan',
            field=models.BooleanField(default=False, help_text='Is this grant part of the gitcoin paid plans or not?'),
        ),
    ]
