# Generated by Django 2.1.7 on 2019-02-28 20:48

from django.db import migrations, models
import grants.models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0016_merge_20190305_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpledge',
            name='end_date',
            field=models.DateTimeField(default=grants.models.next_month),
        ),
    ]
