# Generated by Django 2.1.7 on 2019-03-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0018_grant_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpledge',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
