# Generated by Django 2.1.7 on 2019-04-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0018_matchpledge_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='success',
            field=models.BooleanField(default=True, help_text='Whether or not success.'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='tx_cleared',
            field=models.BooleanField(default=False, help_text='Whether or not tx cleared.'),
        ),
    ]
