# Generated by Django 2.1.7 on 2019-06-04 15:47

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0020_grant_description_rich'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLRMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('round_number', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('grant', models.ForeignKey(help_text='The associated Grant.', on_delete=django.db.models.deletion.CASCADE, related_name='clr_matches', to='grants.Grant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
