# Generated by Django 2.1.7 on 2019-06-05 01:47

import logging
from django.db import migrations
from grants.models import Grant

logger = logging.getLogger(__name__)

def forwards(apps, schema_editor):
    for grant in Grant.objects.all():
        grant.save()

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0023_auto_20190604_1552'),
    ]

    operations = [
            migrations.RunPython(forwards, backwards),
    ]

