# Generated by Django 2.1.7 on 2019-07-22 13:10

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20190718_1222'),
        ('grants', '0024_auto_20190612_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('from_address', models.CharField(default='0x0', help_text="The sender's address.", max_length=255)),
                ('to_address', models.CharField(default='0x0', help_text='The destination address.', max_length=255)),
                ('token_address', models.CharField(default='0x0', help_text='The token address to be used with the Grant.', max_length=255)),
                ('token_symbol', models.CharField(default='', help_text="The donation token's symbol.", max_length=255)),
                ('token_amount', models.DecimalField(decimal_places=18, default=0, help_text='The donation amount in tokens.', max_digits=64)),
                ('token_amount_usdt', models.DecimalField(decimal_places=4, default=0, help_text='The donation amount converted to USDT/DAI at the moment of donation.', max_digits=50)),
                ('tx_id', models.CharField(default='0x0', help_text='The transaction ID of the Contribution.', max_length=255)),
                ('network', models.CharField(default='mainnet', help_text='The network in which the Subscription resides.', max_length=8)),
                ('donation_percentage', models.DecimalField(decimal_places=2, default=0, help_text='The additional percentage selected when the donation is made', max_digits=5)),
                ('contribution', models.ForeignKey(help_text='The contribution that this donation was a part of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation', to='grants.Contribution')),
                ('profile', models.ForeignKey(help_text="The donator's profile.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='dashboard.Profile')),
                ('subscription', models.ForeignKey(help_text='The recurring subscription that this donation originated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='grants.Subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
