# Generated by Django 2.2.3 on 2019-08-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0026_auto_20190731_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='request_ownership_change',
        ),
    ]
