# Generated by Django 2.2.3 on 2019-08-21 17:25

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_merge_20190808_1934'),
        ('grants', '0027_remove_grant_request_ownership_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhantomFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('round_number', models.PositiveIntegerField(blank=True, null=True)),
                ('grant', models.ForeignKey(help_text='The associated Phantom Funding.', on_delete=django.db.models.deletion.CASCADE, related_name='phantom_funding', to='grants.Grant')),
                ('profile', models.ForeignKey(help_text='The associated Phantom Funding.', on_delete=django.db.models.deletion.CASCADE, related_name='grant_phantom_funding', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
