# Generated by Django 2.2.3 on 2019-08-30 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0028_phantomfunding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phantomfunding',
            name='grant',
            field=models.ForeignKey(help_text='The associated grant being Phantom Funding.', on_delete=django.db.models.deletion.CASCADE, related_name='phantom_funding', to='grants.Grant'),
        ),
        migrations.AlterField(
            model_name='phantomfunding',
            name='profile',
            field=models.ForeignKey(help_text='The associated profile doing the Phantom Funding.', on_delete=django.db.models.deletion.CASCADE, related_name='grant_phantom_funding', to='dashboard.Profile'),
        ),
    ]
