# Generated by Django 2.2.3 on 2019-10-16 19:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0033_grant_defer_clr_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='normalized_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='the normalized grant data; for easy consumption on read'),
        ),
    ]
