# Generated by Django 2.2.4 on 2020-01-09 20:44

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0035_auto_20191214_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('category', models.CharField(default='not_set', help_text='Grant Category', max_length=50)),
                ('grant', models.ForeignKey(help_text='The associated Grant.', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='grants.Grant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
