# Generated by Django 2.2.4 on 2020-02-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0037_auto_20200111_1709"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="comments",
            field=models.TextField(
                blank=True, default="", help_text="Comments left by subscriber."
            ),
        ),
    ]
