# Generated by Django 2.2.4 on 2020-01-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0038_grant_link_to_new_grant'),
        ('grants', '0036_grantcategory'),
    ]

    operations = [
    ]
