# Generated by Django 2.2.4 on 2020-02-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0038_subscription_comments"),
        ("grants", "0038_grant_link_to_new_grant"),
    ]

    operations = []
