# Generated by Django 2.2.4 on 2020-02-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0039_merge_20200204_0825"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="cancel_tx_id",
            field=models.CharField(
                blank=True,
                default="0x0",
                help_text="The transaction id for endContract.",
                max_length=255,
            ),
        ),
    ]
