# Generated by Django 2.2.4 on 2020-03-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0046_auto_20200321_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='negative_round_contributor_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='grant',
            name='positive_round_contributor_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
