# Generated by Django 2.2.4 on 2020-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0047_auto_20200323_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='match',
            field=models.BooleanField(default=True, help_text='Whether or not this contribution should be matched.'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='categories',
            field=models.ManyToManyField(blank=True, to='grants.GrantCategory'),
        ),
    ]
