# Generated by Django 2.2.4 on 2020-04-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0051_auto_20200413_1223'),
        ('grants', '0051_auto_20200409_2050'),
    ]

    operations = [
    ]
