# Generated by Django 2.2.4 on 2020-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0054_auto_20200414_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='clrmatch',
            name='payout_tx',
            field=models.CharField(blank=True, help_text='The test payout txid', max_length=255),
        ),
        migrations.AddField(
            model_name='clrmatch',
            name='payout_tx_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clrmatch',
            name='ready_for_payout',
            field=models.BooleanField(default=False, help_text='Ready for regular payout or not'),
        ),
        migrations.AddField(
            model_name='clrmatch',
            name='ready_for_test_payout',
            field=models.BooleanField(default=False, help_text='Ready for test payout or not'),
        ),
        migrations.AddField(
            model_name='clrmatch',
            name='test_payout_tx',
            field=models.CharField(blank=True, help_text='The test payout txid', max_length=255),
        ),
        migrations.AddField(
            model_name='clrmatch',
            name='test_payout_tx_date',
            field=models.DateTimeField(null=True),
        ),
    ]
