# Generated by Django 2.2.4 on 2020-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0055_auto_20200420_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='clrmatch',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='The comments.'),
        ),
    ]
