# Generated by Django 2.2.4 on 2020-04-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0055_auto_20200420_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='amount_goal',
        ),
        migrations.AlterField(
            model_name='clrmatch',
            name='payout_contribution',
            field=models.ForeignKey(blank=True, help_text='Contribution for the payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clr_match_payouts', to='grants.Contribution'),
        ),
        migrations.AlterField(
            model_name='clrmatch',
            name='test_payout_contribution',
            field=models.ForeignKey(blank=True, help_text='Contribution for the test payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_clr_match_payouts', to='grants.Contribution'),
        ),
    ]
