# Generated by Django 2.2.4 on 2020-06-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0062_grant_is_clr_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='grant_type',
            field=models.CharField(choices=[('tech', 'tech'), ('health', 'health'), ('media', 'Community'), ('change', 'change'), ('matic', 'matic')], default='tech', help_text='Grant CLR category', max_length=15),
        ),
    ]
