# Generated by Django 2.2.4 on 2020-06-29 11:14

from django.db import migrations, models
import grants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0063_auto_20200622_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='logo',
            field=models.ImageField(blank=True, help_text='The Grant logo image.', max_length=500, null=True, upload_to=grants.utils.get_upload_filename),
        ),
    ]
