# Generated by Django 2.2.4 on 2020-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0065_auto_20200702_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='clrmatch',
            name='has_passed_kyc',
            field=models.BooleanField(default=False, help_text='Has this grant gone through KYC?'),
        ),
    ]
