# Generated by Django 2.2.4 on 2020-07-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0066_contribution_profile_for_clr'),
        ('grants', '0066_clrmatch_has_passed_kyc'),
    ]

    operations = [
    ]
