# Generated by Django 2.2.4 on 2020-07-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0067_merge_20200707_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='profile_for_clr',
            field=models.ForeignKey(blank=True, help_text='The profile to attribute this contribution to..', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clr_pledges', to='dashboard.Profile'),
        ),
    ]
