# Generated by Django 2.2.4 on 2020-08-08 11:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models
import grants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0068_auto_20200708_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantCLR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('round_num', models.CharField(help_text='CLR Round Number', max_length=15)),
                ('is_active', models.BooleanField(default=False, help_text='Is CLR Round currently active')),
                ('start_date', models.DateTimeField(help_text='CLR Round Start Date')),
                ('end_date', models.DateTimeField(help_text='CLR Round Start Date')),
                ('grant_filters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Grants allowed in this CLR round', null=True)),
                ('subscription_filters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Grant Subscription to be allowed in this CLR round', null=True)),
                ('verified_threshold', models.DecimalField(decimal_places=2, default=25.0, help_text='Verfied CLR Threshold', max_digits=5)),
                ('unverified_threshold', models.DecimalField(decimal_places=2, default=5.0, help_text='Unverified CLR Threshold', max_digits=5)),
                ('total_pot', models.DecimalField(decimal_places=2, default=0, help_text='CLR Pot', max_digits=10)),
                ('logo', models.ImageField(blank=True, help_text='The Grant CLR round image', max_length=500, null=True, upload_to=grants.utils.get_upload_filename)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(help_text='Grant Type', max_length=15, unique=True)),
                ('label', models.CharField(help_text='Display Name', max_length=25, null=True)),
                ('categories', models.ManyToManyField(help_text='Grant Categories associated with Grant Type', to='grants.GrantCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='zcash_payout_address',
            field=models.CharField(blank=True, default='0x0', help_text='The zcash wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.CharField(blank=True, choices=[('ETH', 'ETH'), ('ZCASH', 'ZCASH')], default='ETH', help_text='specific tenant in which contribution is made', max_length=10, null=True),
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='grant_type',
            new_name='grant_type_purge'
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_type',
            field=models.ForeignKey(help_text='Grant Type', null=True, on_delete=django.db.models.deletion.CASCADE, to='grants.GrantType'),
        ),
    ]
