# Generated by Django 2.2.4 on 2020-07-21 15:05

from django.db import migrations, models
import django.db.models.deletion
import economy.models
import grants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0068_auto_20200708_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(help_text='Grant Type', max_length=15, unique=True)),
                ('label', models.CharField(help_text='Display Name', max_length=25, null=True)),
                ('categories', models.ManyToManyField(help_text='Grant Categories associated with Grant Type', to='grants.GrantCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='grant_type',
            new_name='grant_type_purge'
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_type',
            field=models.ForeignKey(help_text='Grant Type', null=True, on_delete=django.db.models.deletion.CASCADE, to='grants.GrantType'),
        ),
        migrations.CreateModel(
            name='GrantCLR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('round_num', models.CharField(help_text='CLR Round Number', max_length=15)),
                ('is_active', models.BooleanField(default=False, help_text='Is CLR Round currently active')),
                ('start_date', models.DateTimeField(help_text='CLR Round Start Date')),
                ('end_date', models.DateTimeField(help_text='CLR Round Start Date')),
                ('threshold', models.DecimalField(decimal_places=2, default=25.0, help_text='CLR Threshold', max_digits=5)),
                ('total_pot', models.DecimalField(decimal_places=2, default=0, help_text='CLR Pot', max_digits=10)),
                ('logo', models.ImageField(blank=True, help_text='The Grant CLR round image', max_length=500, null=True, upload_to=grants.utils.get_upload_filename)),
                ('grant_type', models.ForeignKey(help_text='Grant Type allowed for this round', on_delete=django.db.models.deletion.CASCADE, to='grants.GrantType')),
                ('previous_round', models.ForeignKey(blank=True, help_text='link to previous clr round', null=True, on_delete=django.db.models.deletion.CASCADE, to='grants.GrantCLR')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
