# Generated by Django 2.2.4 on 2020-07-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0070_auto_20200721_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='grant_type_purge',
        ),
    ]
