# Generated by Django 2.2.4 on 2020-08-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0071_remove_grant_grant_type_purge'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='in_active_clrs',
            field=models.ManyToManyField(help_text='Active Grants CLR Round', to='grants.GrantCLR'),
        ),
    ]
