# Generated by Django 2.2.4 on 2020-08-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0072_grant_in_active_clrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='clr_matching',
        ),
    ]
