# Generated by Django 2.2.4 on 2020-09-03 19:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0074_grant_github_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpledge',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
