# Generated by Django 2.2.4 on 2020-09-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0074_grant_github_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchpledge',
            name='data',
        ),
    ]
