# Generated by Django 2.2.4 on 2020-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0076_matchpledge_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='project_link',
            field=models.PositiveIntegerField(blank=True, help_text='Project Id which is converted to grant', null=True),
        ),
    ]
