# Generated by Django 2.2.4 on 2020-09-13 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0148_add_brightid_status'),
        ('grants', '0076_matchpledge_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grant',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Profile'),
        ),
    ]
