# Generated by Django 2.2.4 on 2020-09-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0076_matchpledge_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='funding_info',
            field=models.CharField(default='', help_text='Is this grant VC funded?', max_length=255),
        ),
    ]
