# Generated by Django 2.2.4 on 2020-09-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0077_grant_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='project_link',
        ),
    ]
