# Generated by Django 2.2.4 on 2020-09-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0080_auto_20200914_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_postive_vote',
        ),
    ]
