# Generated by Django 2.2.4 on 2020-09-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0148_add_brightid_status'),
        ('grants', '0085_grantcollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantcollections',
            name='curators',
            field=models.ManyToManyField(blank=True, help_text='List of allowed curators', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='grantcollections',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show grant as featured'),
        ),
    ]
