# Generated by Django 2.2.4 on 2020-09-23 21:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0086_grantcollections'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Stats for this Grant')),
                ('snapshot_type', models.CharField(choices=[('total', 'total'), ('increment', 'increment')], db_index=True, help_text='Snapshot Type', max_length=50)),
                ('grant', models.ForeignKey(help_text='Grant to add stats for ', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='grants.Grant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
