# Generated by Django 2.2.4 on 2020-10-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0088_auto_20200924_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='checkout_type',
            field=models.CharField(blank=True, choices=[('eth_std', 'eth_std'), ('eth_zksync_deposit', 'eth_zksync_deposit'), ('eth_zksync_batch_deposit', 'eth_zksync_batch_deposit'), ('eth_zksync_pure', 'eth_zksync_pure'), ('zcash_std', 'zcash_std')], help_text='The checkout method used while making the contribution', max_length=30, null=True),
        ),
    ]
