# Generated by Django 2.2.4 on 2020-10-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0089_contribution_checkout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantclr',
            name='customer_name',
            field=models.CharField(default='all', help_text='Customer Name', max_length=255),
        ),
        migrations.AddField(
            model_name='grantclr',
            name='sub_round_slug',
            field=models.CharField(default='all', help_text='Sub Round Slug', max_length=255),
        ),
    ]
