# Generated by Django 2.2.4 on 2020-10-15 19:33

from django.db import migrations

def forwards(apps, schema_editor):
    GrantCLR = apps.get_model('grants', 'GrantCLR')
    for gclr in GrantCLR.objects.exclude(round_num__lt=9):
        gclr.sub_round_slug = gclr.round_num
        gclr.round_num = 7
        gclr.save()
    for gclr in GrantCLR.objects.all():
        gclr.customer_name = "ethereum"
        gclr.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0090_grantclr_sub_round_slug'),
    ]

    operations = [
             migrations.RunPython(forwards, backwards),
    ]
