# Generated by Django 2.2.4 on 2020-10-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0090_auto_20201020_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Whether users can view the profile for this project or not'),
        ),
    ]
