# Generated by Django 2.2.4 on 2020-10-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0091_auto_20201015_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantclr',
            name='round_num',
            field=models.PositiveIntegerField(help_text='CLR Round Number'),
        ),
    ]
