# Generated by Django 2.2.4 on 2020-11-05 08:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0091_contribution_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantclr',
            name='collection_filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Grant Collections to be allowed in this CLR round', null=True),
        ),
        migrations.AddField(
            model_name='granttype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Is Grant Type currently active'),
        ),
        migrations.AlterField(
            model_name='matchpledge',
            name='pledge_type',
            field=models.CharField(blank=True, choices=[('tech', 'tech'), ('media', 'media'), ('health', 'health'), ('change', 'change')], help_text='CLR pledge type', max_length=15, null=True),
        ),
    ]
