# Generated by Django 2.2.4 on 2020-11-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0091_contribution_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='The telegram id of Grant creator.', max_length=255, null=True),
        ),
    ]
