# Generated by Django 2.2.4 on 2020-11-04 11:28

from django.db import migrations, models
import grants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0092_granttype_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granttype',
            name='logo',
            field=models.ImageField(blank=True, help_text="The default category's marketing banner (aspect ratio = 10:3)", max_length=500, null=True, upload_to=grants.utils.get_upload_filename),
        ),
    ]
