# Generated by Django 2.2.4 on 2020-11-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0161_auto_20201111_1318'),
        ('grants', '0092_auto_20201111_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantclr',
            name='display_text',
            field=models.CharField(blank=True, help_text='CLR display text, leave blank to adapt as CLR Round Number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='grantclr',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The team that owns the Grant CLR, useful for adding their brand logo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Profile'),
        ),
    ]
