# Generated by Django 2.2.4 on 2020-11-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0092_auto_20201015_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantclr',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='CLR Customer Name', max_length=15),
        ),
        migrations.AlterField(
            model_name='grantclr',
            name='end_date',
            field=models.DateTimeField(help_text='CLR Round End Date'),
        ),
        migrations.AlterField(
            model_name='grantclr',
            name='sub_round_slug',
            field=models.CharField(blank=True, default='', help_text='Sub Round Slug', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='grantclr',
            unique_together={('customer_name', 'round_num', 'sub_round_slug')},
        ),
    ]
