# Generated by Django 2.2.4 on 2020-11-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0093_auto_20201113_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='region',
            field=models.CharField(blank=True, choices=[('north_america', 'North America'), ('oceania', 'Oceania'), ('latin_america', 'Latin America'), ('europe', 'Europe'), ('africa', 'Africa'), ('middle_east', 'Middle East'), ('india', 'India'), ('east_asia', 'East Asia'), ('southeast_asia', 'Southeast Asia')], help_text='region to which grant belongs to', max_length=30, null=True),
        ),
    ]
