# Generated by Django 2.2.4 on 2020-11-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0093_auto_20201113_0124'),
        ('grants', '0095_auto_20201119_1031'),
    ]

    operations = [
    ]
