# Generated by Django 2.2.4 on 2020-11-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0096_merge_20201119_1921'),
        ('grants', '0094_auto_20201118_2029'),
    ]

    operations = [
    ]
