# Generated by Django 2.2.4 on 2020-11-23 12:07

from django.db import migrations, models
import economy.models
import grants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0098_auto_20201120_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantBrandingRoutingPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('url_pattern', models.CharField(help_text='A regex url pattern', max_length=50)),
                ('banner_image', models.ImageField(help_text='The banner image for a grant page', upload_to=grants.utils.get_upload_filename)),
                ('priority', models.PositiveSmallIntegerField(help_text='The priority ranking of this image 1-255. Higher priorities would be loaded first')),
                ('background_image', models.ImageField(help_text='Background image', upload_to=grants.utils.get_upload_filename)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
