# Generated by Django 2.2.4 on 2020-11-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0099_grantbrandingroutingpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='checkout_type',
            field=models.CharField(blank=True, choices=[('eth_std', 'eth_std'), ('eth_zksync', 'eth_zksync'), ('zcash_std', 'zcash_std')], help_text='The checkout method used while making the contribution', max_length=30, null=True),
        ),
    ]
