# Generated by Django 2.2.4 on 2020-11-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0100_update_checkout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='random_shuffle',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
