# Generated by Django 2.2.4 on 2020-11-27 08:36

from django.db import migrations, models
import grants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0101_grant_random_shuffle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantbrandingroutingpolicy',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image', null=True, upload_to=grants.utils.get_upload_filename),
        ),
        migrations.AlterField(
            model_name='grantclr',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='used to genrate customer_name/round_num/sub_round_slug', max_length=15),
        ),
        migrations.AlterField(
            model_name='grantclr',
            name='round_num',
            field=models.PositiveIntegerField(help_text='CLR Round Number. used to generate customer_name/round_num/sub_round_slug'),
        ),
        migrations.AlterField(
            model_name='grantclr',
            name='sub_round_slug',
            field=models.CharField(blank=True, default='', help_text='used to generate customer_name/round_num/sub_round_slug', max_length=25),
        ),
    ]
