# Generated by Django 2.2.4 on 2020-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0102_auto_20201127_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantbrandingroutingpolicy',
            name='policy_name',
            field=models.CharField(blank=True, help_text='name to make it easier to identify', max_length=25, null=True),
        ),
    ]
