# Generated by Django 2.2.4 on 2020-12-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0103_grantbrandingroutingpolicy_policy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantbrandingroutingpolicy',
            name='inline_css',
            field=models.TextField(blank=True, default='', help_text='Inline css to customize the banner fit'),
        ),
    ]
