# Generated by Django 2.2.4 on 2020-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0104_grantbrandingroutingpolicy_inline_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether or not the Grant is active.'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='random_shuffle',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='weighted_shuffle',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
