# Generated by Django 2.2.4 on 2020-12-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0105_auto_20201202_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='admin_address',
            field=models.CharField(blank=True, db_index=True, default='0x0', help_text='The wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
    ]
