# Generated by Django 2.2.4 on 2020-12-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0106_auto_20201204_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='celo_payout_address',
            field=models.CharField(blank=True, help_text='The celo wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='harmony_payout_address',
            field=models.CharField(blank=True, help_text='The harmony wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='polkadot_payout_address',
            field=models.CharField(blank=True, help_text='The polkadot wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='zil_payout_address',
            field=models.CharField(blank=True, help_text='The zilliqa wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='checkout_type',
            field=models.CharField(blank=True, choices=[('eth_std', 'eth_std'), ('eth_zksync', 'eth_zksync'), ('zcash_std', 'zcash_std'), ('celo_std', 'celo_std'), ('zil_std', 'zil_std'), ('polkadot_std', 'polkadot_std'), ('harmony_std', 'harmony_std')], help_text='The checkout method used while making the contribution', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='token_amount_usdt',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The donation amount converted to USD at the moment of donation.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount_received',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The total amount received for the Grant in USD.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount_received_in_round',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The amount received in USD this round.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='monthly_amount_subscribed',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The monthly subscribed to by contributors USD.', max_digits=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.CharField(blank=True, choices=[('ETH', 'ETH'), ('ZCASH', 'ZCASH'), ('CELO', 'CELO'), ('ZIL', 'ZIL'), ('POLKADOT', 'POLKADOT'), ('HARMONY', 'HARMONY')], default='ETH', help_text='specific tenant in which contribution is made', max_length=10, null=True),
        ),
    ]
