# Generated by Django 2.2.4 on 2020-12-04 06:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0106_auto_20201204_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='performance_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='performance metadata, for managing site uptime & performance in backend queue systems.  mostly just timestamps to control clock like behaviour to start'),
        ),
    ]
