# Generated by Django 2.2.4 on 2021-01-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0107_auto_20201222_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='opt_out_clr',
            field=models.BooleanField(default=False, help_text='Did Grant opt out of CLR matching'),
        ),
    ]
