# Generated by Django 2.2.4 on 2020-12-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0107_auto_20201208_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='harmony_payout_address',
            field=models.CharField(blank=True, help_text='The harmony wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='polkadot_payout_address',
            field=models.CharField(blank=True, help_text='The polkadot wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='checkout_type',
            field=models.CharField(blank=True, choices=[('eth_std', 'eth_std'), ('eth_zksync', 'eth_zksync'), ('zcash_std', 'zcash_std'), ('celo_std', 'celo_std'), ('zil_std', 'zil_std'), ('polkadot_std', 'polkadot_std'), ('harmony_std', 'harmony_std')], help_text='The checkout method used while making the contribution', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.CharField(blank=True, choices=[('ETH', 'ETH'), ('ZCASH', 'ZCASH'), ('CELO', 'CELO'), ('ZIL', 'ZIL'), ('POLKADOT', 'POLKADOT'), ('HARMONY', 'HARMONY')], default='ETH', help_text='specific tenant in which contribution is made', max_length=10, null=True),
        ),
    ]
