# Generated by Django 2.2.4 on 2021-01-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0107_auto_20201222_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='celo_payout_address',
            field=models.CharField(blank=True, default='0x0', help_text='The celo wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='harmony_payout_address',
            field=models.CharField(blank=True, default='0x0', help_text='The harmony wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='polkadot_payout_address',
            field=models.CharField(blank=True, default='0x0', help_text='The polkadot wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='zil_payout_address',
            field=models.CharField(blank=True, default='0x0', help_text='The zilliqa wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
    ]
