# Generated by Django 2.2.4 on 2021-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0108_auto_20210114_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='kusama_payout_address',
            field=models.CharField(blank=True, default='0x0', help_text='The kusama wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.CharField(blank=True, choices=[('ETH', 'ETH'), ('ZCASH', 'ZCASH'), ('CELO', 'CELO'), ('ZIL', 'ZIL'), ('POLKADOT', 'POLKADOT'), ('KUSAMA', 'KUSAMA'), ('HARMONY', 'HARMONY')], default='ETH', help_text='specific tenant in which contribution is made', max_length=10, null=True),
        ),
    ]
