# Generated by Django 2.2.4 on 2021-02-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0108_auto_20210114_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='kusama_payout_address',
            field=models.CharField(blank=True, default='0x0', help_text='The kusama wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
    ]
