# Generated by Django 2.2.4 on 2021-02-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0109_grant_kusama_payout_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.CharField(blank=True, choices=[('ETH', 'ETH'), ('ZCASH', 'ZCASH'), ('CELO', 'CELO'), ('ZIL', 'ZIL'), ('POLKADOT', 'POLKADOT'), ('KUSAMA', 'KUSAMA'), ('HARMONY', 'HARMONY')], default='ETH', help_text='specific tenant in which contribution is made', max_length=10, null=True),
        ),
    ]
