# Generated by Django 2.2.4 on 2021-03-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0111_auto_20210218_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='granttype',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Is visible on the Grant filters'),
        ),
    ]
