# Generated by Django 2.2.4 on 2021-03-08 15:10

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0172_auto_20210216_0820'),
        ('grants', '0112_granttype_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('key', models.CharField(blank=True, db_index=True, help_text='the api key', max_length=255)),
                ('secret', models.CharField(blank=True, db_index=True, help_text='the api secret', max_length=255)),
                ('profile', models.ForeignKey(help_text="The GrantAPI key's profile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_apikey', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
