# Generated by Django 2.2.4 on 2021-03-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0113_grantapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantbrandingroutingpolicy',
            name='url_pattern',
            field=models.CharField(help_text='A regex url pattern', max_length=255),
        ),
    ]
