# Generated by Django 2.2.4 on 2021-03-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0114_grantcollection_shuffle_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantbrandingroutingpolicy',
            name='url_pattern',
            field=models.CharField(help_text='A regex url pattern', max_length=255),
        ),
    ]
