# Generated by Django 2.2.4 on 2021-03-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0116_auto_20210316_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='visitorId',
            field=models.CharField(blank=True, default='', help_text='The visitorID of the contributor', max_length=255),
        ),
    ]
