# Generated by Django 2.2.4 on 2021-03-18 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0116_auto_20210316_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='clrmatch',
            name='clr',
            field=models.ForeignKey(help_text='The associated Grant CLR.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clr_rounds', to='grants.GrantCLR'),
        ),
    ]
