# Generated by Django 2.2.20 on 2021-05-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0117_subscription_visitorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='has_external_funding',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', help_text='Does this grant have external funding', max_length=8),
        ),
    ]
