# Generated by Django 2.2.4 on 2021-03-18 21:50

import logging
from django.db import migrations

logger = logging.getLogger(__name__)


def forwards(apps, schema_editor):
    CLRMatch = apps.get_model('grants', 'CLRMatch')
    GrantCLR = apps.get_model('grants', 'GrantCLR')

    # round_number to pk
    mapping = {
        1: 7,
        2: 8,
        3: 9,
        4: 10,
        5: 11,
        6: 12,
        7: 2,
        8: 18,
        107: 1,
        108: 14,
        110: 110,
        120: 20,
        121: 21,
    }
    try:
        for key, val in mapping.items():
            gclr = GrantCLR.objects.get(pk=val)
            if gclr:
                for clrm in CLRMatch.objects.filter(round_number=key):
                    clrm.clr = gclr
                    clrm.save()
    except Exception as e:
        print(e)

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0117_clrmatch_clr'),
    ]

    operations = [
            migrations.RunPython(forwards, backwards),
    ]


