# Generated by Django 2.2.4 on 2021-03-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0118_auto_20210318_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clrmatch',
            name='clr',
            field=models.ForeignKey(help_text='The associated Grant CLR.', on_delete=django.db.models.deletion.CASCADE, related_name='clr_rounds', to='grants.GrantCLR'),
        ),
    ]
