# Generated by Django 2.2.20 on 2021-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0118_grant_has_external_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantclr',
            name='display_text',
            field=models.CharField(blank=True, help_text='sets the custom text in CLR banner on the landing page', max_length=25, null=True),
        ),
    ]
