# Generated by Django 2.2.24 on 2021-07-23 07:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0120_auto_20210622_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Used for full text search. Generated using [title, description]', null=True),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='grants_gran_vector__534e95_gin'),
        ),
    ]
