
# Generated by Django 2.2.24 on 2021-07-26 07:03

from django.db import migrations, models
import economy.models


def port_data(apps, schema_editor):
    Grant = apps.get_model('grants', 'Grant')
    GrantTag = apps.get_model('grants', 'GrantTag')
    GrantCategory = apps.get_model('grants', 'GrantCategory')


    # populate GrantTag
    categories = GrantCategory.objects.all()
    for category in categories:
        name = category.category
        grantTag = GrantTag.objects.create(name=name)
        grantTag.save()

    tags = GrantTag.objects.all()

    # migrate grants to tag mapping
    for grant in Grant.objects.all():
        _categories = grant.categories.all()
        for category in _categories:
            tag = tags.get(name=category.category)
            grant.tags.add(tag)
        grant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0122_create_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(help_text='Grant Tag', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='granttype',
            name='categories',
        ),
        migrations.AddField(
            model_name='grant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='grants.GrantTag'),
        ),
        migrations.RunPython(port_data)
    ]
