# Generated by Django 2.2.24 on 2021-09-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0123_auto_20210726_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhantomFunding',
        ),
    ]
