# Generated by Django 2.2.24 on 2021-09-10 19:44

from django.db import migrations, models
import grants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0124_merge_20210910_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='granthalloffame',
            name='top_individual_donors_mobile',
            field=models.ImageField(help_text='The image with the top individual donors for mobile (recommended size 290x480)', null=True, upload_to=grants.utils.get_upload_filename),
        ),
        migrations.AddField(
            model_name='granthalloffame',
            name='top_matching_partners_mobile',
            field=models.ImageField(help_text='The image with the top matching partners for mobile (recommended size 290x437)', null=True, upload_to=grants.utils.get_upload_filename),
        ),
    ]
