# Generated by Django 2.2.24 on 2021-09-17 21:20

from django.db import migrations, models
import django.db.models.deletion
import grants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0185_auto_20210823_2105'),
        ('grants', '0125_auto_20210910_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granthalloffamegrantee',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='granthalloffamegrantee',
            name='username',
        ),
        migrations.AddField(
            model_name='granthalloffamegrantee',
            name='grantee',
            field=models.ForeignKey(blank=True, help_text='Sets the grantee profile', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='granthalloffame',
            name='top_matching_partners_mobile',
            field=models.ImageField(help_text='The image with the top matching partners for mobile (recommended size 290x437).', null=True, upload_to=grants.utils.get_upload_filename),
        ),
    ]
