# Generated by Django 2.2.24 on 2021-10-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0126_auto_20211001_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantclr',
            name='banner_bg_hex',
            field=models.CharField(blank=True, default='#11BC92', help_text='sets the bg color on the banner below the logo', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='grantclr',
            name='banner_text',
            field=models.CharField(blank=True, help_text='text which appears below banner', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grantclr',
            name='banner_text_hex',
            field=models.CharField(blank=True, default='#FFF', help_text='sets the text color on the banner below the logo', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='grantclr',
            name='logo_text_hex',
            field=models.CharField(blank=True, default='#000000', help_text='sets the text color of the logo', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='grantclr',
            name='type',
            field=models.CharField(choices=[('main', 'Main Round'), ('side', 'Side Round'), ('cause', 'Cause Round')], default='main', help_text='Grant CLR Type', max_length=25),
        ),
    ]
