# Generated by Django 2.2.24 on 2021-11-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0126_auto_20211001_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantclrcalculation',
            name='active',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this calc active?'),
        ),
    ]
