# Generated by Django 2.2.24 on 2021-11-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0127_auto_20211029_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='amount_per_period_usdt',
            field=models.DecimalField(decimal_places=18, default=0, help_text='The amount per contribution period in USDT', max_digits=64),
        ),
        migrations.AddField(
            model_name='contribution',
            name='grant',
            field=models.ForeignKey(help_text='The associated Grant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='grants.Grant'),
        ),
    ]
