# Generated by Django 2.2.24 on 2021-11-22 20:34

from django.db import migrations, models
import grants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0127_auto_20211029_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantcollection',
            options={'get_latest_by': 'created_on'},
        ),
        migrations.AddField(
            model_name='grantbrandingroutingpolicy',
            name='main_round_banner',
            field=models.ImageField(blank=True, help_text='The main round banner for the grant page', null=True, upload_to=grants.utils.get_upload_filename),
        ),
    ]
