# Generated by Django 2.2.24 on 2021-11-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0126_auto_20210917_2120'),
        ('grants', '0128_auto_20211124_0639'),
    ]

    operations = [
    ]
