# Generated by Django 2.2.24 on 2021-11-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0128_auto_20211124_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='amount_per_period_usdt',
            field=models.DecimalField(decimal_places=18, default=0, help_text='The amount per contribution period in USDT', max_digits=64),
        ),
        migrations.AddField(
            model_name='contribution',
            name='grant',
            field=models.ForeignKey(help_text='The associated Grant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='grants.Grant'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount_per_period_usdt',
            field=models.DecimalField(db_index=True, decimal_places=18, default=0, help_text='The amount per contribution period in USDT', max_digits=64),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='match',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether or not this contribution should be matched.'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='success',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether or not success.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='network',
            field=models.CharField(db_index=True, default='mainnet', help_text='The network in which the Subscription resides.', max_length=8),
        ),
        migrations.AddField(
            model_name='grantclrcalculation',
            name='active',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this calc active?'),
        ),
    ]
