# Generated by Django 2.2.24 on 2021-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0128_auto_20211116_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount_per_period_usdt',
            field=models.DecimalField(db_index=True, decimal_places=18, default=0, help_text='The amount per contribution period in USDT', max_digits=64),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='match',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether or not this contribution should be matched.'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='success',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether or not success.'),
        ),
    ]
