# Generated by Django 2.2.24 on 2021-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0129_auto_20211116_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='network',
            field=models.CharField(db_index=True, default='mainnet', help_text='The network in which the Subscription resides.', max_length=8),
        ),
    ]
