# Generated by Django 2.2.24 on 2021-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0131_auto_20211126_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='last_update',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The last grant admin update date', null=True),
        ),
    ]
