# Generated by Django 2.2.24 on 2021-12-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0132_auto_20211203_1427'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['contributor_address'], name='grants_subs_contrib_d72508_idx'),
        ),
    ]
