# Generated by Django 2.2.24 on 2021-12-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0133_auto_20211214_1413'),
        ('grants', '0127_auto_20211215_0139'),
    ]

    operations = [
    ]
