# Generated by Django 2.2.24 on 2022-01-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0135_auto_20211223_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='admin_profile',
            field=models.ForeignKey(help_text="The Grant administrator's profile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='dashboard.Profile'),
        ),
    ]
