# Generated by Django 2.2.24 on 2022-02-14 06:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0136_auto_20220116_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clrmatch',
            name='ready_for_test_payout',
        ),
        migrations.RemoveField(
            model_name='clrmatch',
            name='test_payout_contribution',
        ),
        migrations.RemoveField(
            model_name='clrmatch',
            name='test_payout_tx',
        ),
        migrations.RemoveField(
            model_name='clrmatch',
            name='test_payout_tx_date',
        ),
        migrations.AddField(
            model_name='clrmatch',
            name='merkle_claim',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Claim object needed to make claim against merkle contract'),
        ),
    ]
