# Generated by Django 2.2.24 on 2022-03-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0139_grantclr_grant_excludes'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='contribution',
            index_together={('modified_on', 'checkout_type')},
        ),
    ]
