# Generated by Django 2.2.24 on 2022-04-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_auto_20211022_1920'),
        ('grants', '0140_auto_20220316_1059'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='grantpayout',
        #     name='payout_token',
        # ),
        migrations.AddField(
            model_name='clrmatch',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Token in which amount should be paid out', null=True, on_delete=django.db.models.deletion.SET_NULL, to='economy.Token'),
        ),
        migrations.AddField(
            model_name='clrmatch',
            name='token_amount',
            field=models.FloatField(blank=True, help_text='CLR Amount in Token', null=True),
        ),
        migrations.AddField(
            model_name='grantpayout',
            name='conversion_date',
            field=models.DateTimeField(blank=True, help_text='date on which conversion_rate was set', null=True),
        ),
        migrations.AddField(
            model_name='grantpayout',
            name='conversion_rate',
            field=models.FloatField(default=1.0, help_text='token to USD conversion rate'),
        ),
        migrations.AddField(
            model_name='grantpayout',
            name='token',
            field=models.ForeignKey(blank=True, help_text='Token in which amount should be paid out', null=True, on_delete=django.db.models.deletion.SET_NULL, to='economy.Token'),
        ),
        migrations.AlterField(
            model_name='clrmatch',
            name='amount',
            field=models.FloatField(help_text='CLR Amount in USD'),
        ),
    ]
