# Generated by Django 2.2.24 on 2022-04-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0141_auto_20220404_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='cosmos_payout_address',
            field=models.CharField(blank=True, default='0x0', help_text='The cosmos wallet address where subscription funds will be sent.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='checkout_type',
            field=models.CharField(blank=True, choices=[('eth_std', 'eth_std'), ('eth_zksync', 'eth_zksync'), ('eth_polygon', 'eth_polygon'), ('zcash_std', 'zcash_std'), ('celo_std', 'celo_std'), ('zil_std', 'zil_std'), ('polkadot_std', 'polkadot_std'), ('harmony_std', 'harmony_std'), ('binance_std', 'binance_std'), ('rsk_std', 'rsk_std'), ('algorand_std', 'algorand_std'), ('cosmos_std', 'cosmos_std')], help_text='The checkout method used while making the contribution', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.CharField(blank=True, choices=[('ETH', 'ETH'), ('ZCASH', 'ZCASH'), ('CELO', 'CELO'), ('ZIL', 'ZIL'), ('POLKADOT', 'POLKADOT'), ('KUSAMA', 'KUSAMA'), ('HARMONY', 'HARMONY'), ('BINANCE', 'BINANCE'), ('RSK', 'RSK'), ('ALGORAND', 'ALGORAND'), ('COSMOS', 'COSMOS')], default='ETH', help_text='specific tenant in which contribution is made', max_length=10, null=True),
        ),
    ]
