# Generated by Django 2.2.24 on 2022-05-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0143_auto_20220429_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchPledge',
        ),
    ]
