# Generated by Django 2.2.24 on 2022-05-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0144_delete_matchpledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='tag_eligibility_reason',
            field=models.TextField(blank=True, default='', help_text='Eligibility Tag Reasoning'),
        ),
    ]
