# Generated by Django 2.2.24 on 2022-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0145_grant_tag_eligibility_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='tags_requested',
            field=models.ManyToManyField(blank=True, related_name='tags_requested', to='grants.GrantTag'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='grants.GrantTag'),
        ),
    ]
