# Generated by Django 2.2.24 on 2022-08-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0147_grantcontributionindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantcontributionindex',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=18, default=0, help_text='The amount contributed', max_digits=64),
        ),
    ]
