# Generated by Django 2.2.24 on 2022-08-31 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grants', '0148_grantcontributionindex_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GR15TrustScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('last_apu_score', models.DecimalField(decimal_places=18, max_digits=64, verbose_name='APU Score')),
                ('max_apu_score', models.DecimalField(decimal_places=18, max_digits=64, verbose_name='Max APU Score')),
                ('trust_bonus', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Trust bonus')),
                ('last_apu_calculation_time', models.DateTimeField(verbose_name='Last APU calculation')),
                ('max_apu_calculation_time', models.DateTimeField(verbose_name='Last APU calculation')),
                ('user', models.ForeignKey(help_text='The owner of the trust bonus', on_delete=django.db.models.deletion.CASCADE, related_name='gr15_trustbonus', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
