# Generated by Django 2.2.24 on 2022-08-30 10:40

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0210_auto_20220718_1306'),
        ('grants', '0148_grantcontributionindex_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GR15TrustScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('apu_score', models.DecimalField(decimal_places=18, max_digits=64, verbose_name='APU Score')),
                ('trust_bonus', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Trust bonus')),
                ('last_apu_calculation', models.DateTimeField(verbose_name='Last APU calculation')),
                ('last_trust_bonus_update', models.DateTimeField(verbose_name='Last trust bonus update')),
                ('profile', models.ForeignKey(help_text='The owner of the trust bonus', on_delete=django.db.models.deletion.CASCADE, related_name='gr15_trustbonus', to='dashboard.Profile', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
