# Generated by Django 2.2.24 on 2022-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0148_grantcontributionindex_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantcontributionindex',
            name='round_num',
            field=models.IntegerField(blank=True, help_text='The round number a user contributed to', null=True),
        ),
    ]
