# Generated by Django 2.2.24 on 2022-09-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0149_auto_20220916_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantcontributionindex',
            name='contribution',
            field=models.ForeignKey(blank=True, help_text='Contribution', null=True, on_delete=django.db.models.deletion.CASCADE, to='grants.Contribution'),
        ),
    ]
