# Generated by Django 2.0.3 on 2018-04-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapayload',
            name='payload',
        ),
    ]
