# Generated by Django 2.0.3 on 2018-04-14 23:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0002_remove_datapayload_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapayload',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=False),
        ),
    ]
