# Generated by Django 2.1 on 2018-08-15 17:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0002_auto_20180430_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapayload',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
