# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscodes',
            name='maxuses',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
