# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('tdi', '0002_accesscodes_maxuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitepaperAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('comments', models.TextField(max_length=5000)),
                ('email', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
