# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdi', '0003_whitepaperaccessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitepaperaccess',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
