# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdi', '0004_auto_20170926_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitepaperaccessrequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
