# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdi', '0005_whitepaperaccessrequest_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitepaperaccessrequest',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
