# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdi', '0006_auto_20171008_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscodes',
            options={'verbose_name_plural': 'Access codes'},
        ),
        migrations.AlterModelOptions(
            name='whitepaperaccess',
            options={'verbose_name_plural': 'Whitepaper access'},
        ),
    ]
