'''
    Copyright (C) 2019 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

'''
import random

from django.core.management.base import BaseCommand
from django.utils import timezone
from django.utils.crypto import get_random_string

from dashboard.models import Profile
from kudos.models import BulkTransferCoupon, Token
from townsquare.models import Offer


def make_btc(key):
    token = Token.objects.filter(owner_address='0x6239FF1040E412491557a7a02b2CBcC5aE85dc8F', contract__network='xdai', num_clones_available_counting_indirect_send__gt=10).order_by('?').first()
    n = max(100, token.num_clones_available_counting_indirect_send)
    key_len = 25
    _key = get_random_string(key_len)
    btc = BulkTransferCoupon.objects.create(
        token=token,
        num_uses_total=n,
        num_uses_remaining=n,
        current_uses=0,
        secret=_key,
        comments_to_put_in_kudos_transfer=f"Enjoy this {key} action!",
        sender_profile=Profile.objects.get(handle='gitcoinbot'),
        make_paid_for_first_minutes=0,
        )
    return btc

class Command(BaseCommand):

    help = 'creates a offer if non exists'

    def handle(self, *args, **options):

        keys = ['daily', 'weekly', 'monthly']
        for key in keys:
            has_offer = Offer.objects.current().filter(key=key)
            if has_offer.exists():
                print('offer exist already')
            else:
                btc = make_btc(key)
                days = 1
                if key == 'weekly':
                    days = 7
                if key == 'monthly':
                    days = 30
                _then = timezone.now() + timezone.timedelta(days=days) - timezone.timedelta(minutes=1)
                style = f"back{random.randint(2, 30)}"
                offer = Offer.objects.create(
                    from_name = 'gitcoinbot',
                    from_link = 'https://gitcoin.co/gitcoinbot',
                    title = 'Have a free kudos :)',
                    desc = f'The kudos for this offer is the *{btc.token.ui_name}* Kudos. Get it while its 🔥 ',
                    url = f"https://gitcoin.co{btc.url}",
                    valid_from = timezone.now(),
                    valid_to = _then,
                    key = key,
                    style = style,
                    persona = btc.token,
                    created_by = btc.sender_profile,
                    comments_admin = 'autogenerated',
                    )
                print(key, offer.pk)
