# Generated by Django 2.2.4 on 2020-11-25 16:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import quadraticlands.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0153_hackathonevent_use_circle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_use', models.BooleanField(default=False)),
                ('proof_of_receive', models.BooleanField(default=False)),
                ('proof_of_knowledge', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_status', to='dashboard.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InitialTokenDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_total', quadraticlands.models.Uint256Field(default=0)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('distribution', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_distribution', to='dashboard.Profile')),
            ],
        ),
    ]
