# Generated by Django 2.2.4 on 2021-04-21 01:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
# import quadraticlands.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0172_auto_20210216_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadLandsFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_use', models.BooleanField(default=False)),
                ('proof_of_receive', models.BooleanField(default=False)),
                ('proof_of_knowledge', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_status', to='dashboard.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InitialTokenDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('claim_total', models.DateTimeField(auto_now=True)),
                ('distribution', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_distribution', to='dashboard.Profile')),
            ],
        ),
    ]
