# Generated by Django 2.2.4 on 2020-12-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadraticlands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadLandsFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
            ],
        ),
    ]
