# Generated by Django 2.2.4 on 2021-04-21 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0172_auto_20210216_0820'),
        ('quadraticlands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTCSteward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default=False, max_length=50)),
                ('bio', models.CharField(default=False, max_length=64)),
                ('gtc_address', models.CharField(default='0x0', max_length=255)),
                ('profile_link', models.URLField(default=False, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GTCSteward', to='dashboard.Profile')),
            ],
        ),
    ]
