# Generated by Django 2.2.4 on 2020-12-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadraticlands', '0002_quadlandsfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadlandsfaq',
            name='position',
            field=models.IntegerField(unique=True),
        ),
    ]
