# Generated by Django 2.2.4 on 2021-01-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quadraticlands', '0003_auto_20201204_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('start_block', models.BigIntegerField()),
                ('end_block', models.BigIntegerField()),
                ('title', models.TextField(blank=True, default='')),
                ('ipfs_hash', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='quadraticlands.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quadraticlands.Question')),
            ],
        ),
    ]
