# Generated by Django 2.2.4 on 2021-04-25 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quadraticlands', '0004_auto_20210425_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlvote',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_status', to='dashboard.Profile'),
        ),
    ]
