# Generated by Django 2.2.4 on 2021-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadraticlands', '0005_auto_20210425_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlvote',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
