# Generated by Django 2.2.20 on 2021-05-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0180_auto_20210503_0431'),
        ('quadraticlands', '0007_gtcsteward_custom_steward_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchwagCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(default=False, help_text='actual coupon code', max_length=20)),
                ('discount_type', models.CharField(choices=[('20_off', '20 OFF'), ('40_off', '40 OFF'), ('60_off', '60 OFF')], help_text='discount', max_length=10)),
                ('profile', models.ForeignKey(blank=True, help_text='profile which has claimed the coupon', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
            ],
        ),
    ]
