# Generated by Django 2.2.20 on 2021-06-11 03:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import economy.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0181_auto_20210611_0309'),
        ('quadraticlands', '0008_schwagcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('_type', models.CharField(db_index=True, default='', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('admin', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('game', models.ForeignKey(help_text='The Game', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quadraticlands.Game')),
                ('player', models.ForeignKey(help_text='The player of the game.', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('game', models.ForeignKey(help_text='Link to Game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='quadraticlands.Game')),
                ('player', models.ForeignKey(help_text="The game feed update creators's profile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_feed', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
