# Generated by Django 2.2.20 on 2021-06-11 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quadraticlands', '0009_game_gamefeed_gameplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='player',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='gamefeed',
            name='player',
            field=models.ForeignKey(help_text="The game feed update creators's profile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_feed', to='quadraticlands.GamePlayer'),
        ),
    ]
