# Generated by Django 2.2.24 on 2022-02-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quadraticlands', '0009_game_gamefeed_gameplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamefeed',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamefeed',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='gtcsteward',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='initialtokendistribution',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='missionstatus',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='qlvote',
            name='profile',
        ),
        migrations.DeleteModel(
            name='QuadLandsFAQ',
        ),
        migrations.RemoveField(
            model_name='schwagcoupon',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameFeed',
        ),
        migrations.DeleteModel(
            name='GamePlayer',
        ),
        migrations.DeleteModel(
            name='GTCSteward',
        ),
        migrations.DeleteModel(
            name='InitialTokenDistribution',
        ),
        migrations.DeleteModel(
            name='MissionStatus',
        ),
        migrations.DeleteModel(
            name='QLVote',
        ),
        migrations.DeleteModel(
            name='SchwagCoupon',
        ),
    ]
