# Generated by Django 2.2.20 on 2021-06-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quadraticlands', '0010_auto_20210611_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='accepted',
        ),
    ]
