# Generated by Django 2.1.4 on 2018-12-26 17:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTransferCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('num_uses_total', models.IntegerField()),
                ('num_uses_remaining', models.IntegerField()),
                ('current_uses', models.IntegerField(default=0)),
                ('secret', models.CharField(max_length=255, unique=True)),
                ('comments_to_put_in_kudos_transfer', models.CharField(blank=True, max_length=255)),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_transfers', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkTransferRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('ip_address', models.GenericIPAddressField(default=None, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_transfer_redemptions', to='kudos.BulkTransferCoupon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('network', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KudosTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('web3_type', models.CharField(default='v3', max_length=50)),
                ('emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('primary_email', models.CharField(blank=True, default='', max_length=255)),
                ('tokenName', models.CharField(default='ETH', max_length=255)),
                ('tokenAddress', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, default=1, max_digits=50)),
                ('comments_public', models.TextField(blank=True, default='')),
                ('ip', models.CharField(max_length=50)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('from_username', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('network', models.CharField(default='', max_length=255)),
                ('txid', models.CharField(default='', max_length=255)),
                ('receive_txid', models.CharField(blank=True, default='', max_length=255)),
                ('received_on', models.DateTimeField(blank=True, null=True)),
                ('from_address', models.CharField(blank=True, default='', max_length=255)),
                ('receive_address', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('is_for_bounty_fulfiller', models.BooleanField(default=False, help_text='If this option is chosen, this tip will be automatically paid to the bounty fulfiller, not self.usernameusername.')),
                ('tx_status', models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped')], db_index=True, default='na', max_length=9)),
                ('receive_tx_status', models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped')], db_index=True, default='na', max_length=9)),
                ('tx_time', models.DateTimeField(blank=True, null=True)),
                ('receive_tx_time', models.DateTimeField(blank=True, null=True)),
                ('trust_url', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('price_finney', models.IntegerField()),
                ('num_clones_allowed', models.IntegerField(blank=True, null=True)),
                ('num_clones_in_wild', models.IntegerField(blank=True, null=True)),
                ('cloned_from_id', models.IntegerField()),
                ('popularity', models.IntegerField(default=0)),
                ('popularity_week', models.IntegerField(default=0)),
                ('popularity_month', models.IntegerField(default=0)),
                ('popularity_quarter', models.IntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(db_index=True, max_length=510)),
                ('image', models.CharField(max_length=255, null=True)),
                ('rarity', models.CharField(max_length=255, null=True)),
                ('tags', models.CharField(db_index=True, max_length=255, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.CharField(max_length=255, null=True)),
                ('background_color', models.CharField(max_length=255, null=True)),
                ('owner_address', models.CharField(max_length=255)),
                ('txid', models.CharField(blank=True, max_length=255, null=True)),
                ('token_id', models.IntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('send_enabled_for_non_gitcoin_admins', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kudos_contract', to='kudos.Contract')),
            ],
            options={
                'verbose_name_plural': 'Kudos',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kudos_wallets', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kudostransfer',
            name='kudos_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kudos_transfer', to='kudos.Token'),
        ),
        migrations.AddField(
            model_name='kudostransfer',
            name='kudos_token_cloned_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kudos_token_cloned_from', to='kudos.Token'),
        ),
        migrations.AddField(
            model_name='kudostransfer',
            name='recipient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_kudos', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='kudostransfer',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_kudos', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='bulktransferredemption',
            name='kudostransfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_transfer_redemptions', to='kudos.KudosTransfer'),
        ),
        migrations.AddField(
            model_name='bulktransferredemption',
            name='redeemed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_transfer_redemptions', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='bulktransfercoupon',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_transfers', to='kudos.Token'),
        ),
        migrations.AlterIndexTogether(
            name='token',
            index_together={('name', 'description', 'tags')},
        ),
    ]
