# Generated by Django 2.0.7 on 2018-08-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='expires_date',
        ),
    ]
