# Generated by Django 2.1.1 on 2018-10-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudostransfer',
            name='tokenAddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='background_color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='external_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
