# Generated by Django 2.1.2 on 2018-10-23 16:04

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('network', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='token',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='token',
            name='network',
        ),
        migrations.AddField(
            model_name='token',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kudos_contract', to='kudos.Contract'),
        ),
    ]
