# Generated by Django 2.1.2 on 2018-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kudostransfer',
            name='trust_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
