# Generated by Django 2.1.7 on 2019-04-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0002_transferenabledfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransfercoupon',
            name='sender_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bulktransfercoupon',
            name='sender_pk',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
