# Generated by Django 2.1.2 on 2018-10-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0002_auto_20181028_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudostransfer',
            name='kudos_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kudos_transfer', to='kudos.Token'),
        ),
    ]
