# Generated by Django 2.1.2 on 2019-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0002_transferenabledfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='kudostransfer',
            name='pin_rank',
            field=models.IntegerField(default=-1),
        ),
    ]
