# Generated by Django 2.1.2 on 2018-11-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0003_auto_20181028_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
