# Generated by Django 2.1 on 2018-08-31 20:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0003_remove_email_comments_priv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='emails',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='email',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
