# Generated by Django 2.1.2 on 2018-11-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0004_token_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='popularity_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='popularity_quarter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='popularity_week',
            field=models.IntegerField(default=0),
        ),
    ]
