# Generated by Django 2.1.2 on 2018-11-14 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0002_auto_20181015_2336'),
        ('kudos', '0005_auto_20181101_1356'),
    ]

    operations = [
    ]
