# Generated by Django 2.1.2 on 2018-11-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0005_auto_20181101_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name_plural': 'Kudos'},
        ),
        migrations.AlterField(
            model_name='token',
            name='description',
            field=models.CharField(db_index=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='tags',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterIndexTogether(
            name='token',
            index_together={('name', 'description', 'tags')},
        ),
    ]
