# Generated by Django 2.1.2 on 2018-11-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0006_auto_20181102_1308'),
        ('kudos', '0006_auto_20181114_1854'),
    ]

    operations = [
    ]
