# Generated by Django 2.1.2 on 2018-11-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0006_merge_20181114_2340'),
        ('kudos', '0006_auto_20181114_1854'),
    ]

    operations = [
    ]
