# Generated by Django 2.1.2 on 2018-11-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0007_merge_20181114_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudostransfer',
            name='tokenAddress',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
