# Generated by Django 2.2.3 on 2019-09-30 02:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0007_bulktransfercoupon_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransfercoupon',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
