# Generated by Django 2.1.2 on 2018-11-16 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0007_merge_20181114_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='send_enabled_for_non_gitcoin_admins',
            field=models.BooleanField(default=True),
        ),
    ]
