# Generated by Django 2.2.4 on 2019-10-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0008_tokenrequest_processed'),
        ('kudos', '0008_bulktransfercoupon_metadata'),
    ]

    operations = [
    ]
