# Generated by Django 2.1.2 on 2018-11-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0009_auto_20181118_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudostransfer',
            name='tokenAddress',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
