# Generated by Django 2.2.3 on 2019-10-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0009_merge_20191002_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='num_clones_available_counting_indirect_send',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
