# Generated by Django 2.2.3 on 2019-11-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0010_token_num_clones_available_counting_indirect_send'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('token_id', 'contract')},
        ),
    ]
