# Generated by Django 2.1.2 on 2018-11-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0010_auto_20181119_1833'),
        ('kudos', '0008_auto_20181124_2228'),
    ]

    operations = [
    ]
