# Generated by Django 2.1.2 on 2018-11-24 21:07

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0010_auto_20181119_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(default='', max_length=500)),
                ('priceFinney', models.IntegerField(default=18)),
                ('network', models.CharField(db_index=True, max_length=25)),
                ('artist', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('artwork_url', models.CharField(max_length=255)),
                ('numClonesAllowed', models.IntegerField(default=18)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('approved', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
