# Generated by Django 2.2.4 on 2020-04-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0011_auto_20191106_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenrequest',
            name='bounty_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
