# Generated by Django 2.1.2 on 2018-11-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0011_merge_20181125_0123'),
        ('kudos', '0011_merge_20181126_0304'),
    ]

    operations = [
    ]
