# Generated by Django 2.1.2 on 2018-11-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0008_auto_20181116_1816'),
        ('kudos', '0012_merge_20181126_2023'),
    ]

    operations = [
    ]
