# Generated by Django 2.1.2 on 2018-11-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0013_merge_20181126_2232'),
        ('kudos', '0008_auto_20181129_2213'),
    ]

    operations = [
    ]
