# Generated by Django 2.2.4 on 2020-05-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0014_auto_20200505_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
