# Generated by Django 2.2.4 on 2020-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0018_auto_20200625_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenrequest',
            name='gas_price_overide',
            field=models.IntegerField(default=0, help_text='If non-zero, then the celery task will use this gas price to mint hte kudos'),
        ),
    ]
