# Generated by Django 2.2.4 on 2021-01-08 02:10

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0019_tokenrequest_gas_price_overide'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransfercoupon',
            name='quest_pk',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
