# Generated by Django 2.2.24 on 2021-09-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0019_tokenrequest_gas_price_overide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudostransfer',
            name='network',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
