# Generated by Django 2.2.4 on 2021-01-13 03:52

from django.db import migrations


def forwards(apps, schema_editor):
    attempts = apps.get_model('quests', 'QuestAttempt')
    btcs = apps.get_model('kudos', 'BulkTransferCoupon')

    for attempt in attempts.objects.filter(success=True): 
        btc = btcs.objects.filter(
            token=attempt.quest.kudos_reward,
            metadata__recipient=attempt.profile.pk
        ).first()
        if btc is not None and btc.associated_quest is None:
            btc.associated_quest=attempt.quest
            btc.save()

def backwards(apps, schema_editor):
    btcs = apps.get_model('kudos', 'BulkTransferCoupon')

    for btc in btcs.objects.all():
        btc.associated_quest=None
        btc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0020_bulktransfercoupon_associated_quest'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
