# Generated by Django 2.2.24 on 2021-10-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0021_auto_20211002_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='kudostransfer',
            name='value_in_usdt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
    ]
