# Generated by Django 2.0.3 on 2018-03-20 09:36

from django.db import migrations, models
import economy.models
import enssubdomain.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ENSSubdomainRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('github_handle', models.CharField(db_index=True, max_length=255)),
                ('subdomain_wallet_address', models.CharField(max_length=50)),
                ('txn_hash', models.CharField(max_length=255)),
                ('request_timestamp', models.DateTimeField(db_index=True, default=enssubdomain.models.get_time)),
                ('pending', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
