# Generated by Django 2.0.5 on 2018-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enssubdomain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enssubdomainregistration',
            old_name='txn_hash',
            new_name='txn_hash_1',
        ),
        migrations.AddField(
            model_name='enssubdomainregistration',
            name='txn_hash_2',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
