# Generated by Django 2.0.3 on 2018-03-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enssubdomain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enssubdomainregistration',
            name='request_timestamp',
        ),
    ]
