# Generated by Django 2.0.4 on 2018-04-22 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_remove_bounty_avatar_url'),
        ('enssubdomain', '0002_remove_enssubdomainregistration_request_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enssubdomainregistration',
            name='github_handle',
        ),
        migrations.AddField(
            model_name='enssubdomainregistration',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ens_registration', to='dashboard.Profile'),
        ),
    ]
