# Generated by Django 2.0.5 on 2018-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enssubdomain', '0002_auto_20180519_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='enssubdomainregistration',
            name='signed_msg',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
