# Generated by Django 2.0.5 on 2018-05-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enssubdomain', '0004_enssubdomainregistration_txn_hash_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='enssubdomainregistration',
            name='end_nonce',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enssubdomainregistration',
            name='start_nonce',
            field=models.IntegerField(default=0),
        ),
    ]
