# Generated by Django 2.0.5 on 2018-05-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enssubdomain', '0005_auto_20180519_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='enssubdomainregistration',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
