# Generated by Django 2.0.5 on 2018-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enssubdomain', '0006_enssubdomainregistration_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='enssubdomainregistration',
            name='gas_cost_eth',
            field=models.FloatField(default=0.000649197),
        ),
    ]
