# Generated by Django 2.1.1 on 2018-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enssubdomain', '0007_enssubdomainregistration_gas_cost_eth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enssubdomainregistration',
            name='txn_hash_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enssubdomainregistration',
            name='txn_hash_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enssubdomainregistration',
            name='txn_hash_3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
