# Generated by Django 2.2.24 on 2021-12-01 11:50

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('handle', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('user', 'User'), ('repo', 'Repository')], max_length=20)),
                ('data', models.BinaryField()),
            ],
            options={
                'unique_together': {('handle', 'category')},
            },
        ),
    ]
