# Generated by Django 2.2.24 on 2021-12-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcache',
            name='category',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('repo', 'Repository'), ('issue', 'Issue'), ('issue_comment', 'Issue Comment')], max_length=20),
        ),
    ]
