# Generated by Django 2.0.6 on 2018-06-19 22:18

import avatar.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='png',
            field=models.ImageField(blank=True, null=True, upload_to=avatar.utils.get_upload_filename),
        ),
        migrations.AddField(
            model_name='avatar',
            name='use_github_avatar',
            field=models.BooleanField(default=True),
        ),
    ]
