# Generated by Django 2.0.6 on 2018-06-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name_plural': 'Avatars'},
        ),
    ]
