# Generated by Django 2.1 on 2018-09-03 20:05

import avatar.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_auto_20180627_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='custom_avatar_png',
            field=models.ImageField(blank=True, help_text='The custom avatar PNG.', null=True, upload_to=avatar.utils.get_upload_filename),
        ),
        migrations.AddField(
            model_name='avatar',
            name='github_svg',
            field=models.FileField(blank=True, help_text='The Github avatar SVG.', null=True, upload_to=avatar.utils.get_upload_filename),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The JSON configuration of the custom avatar.'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='png',
            field=models.ImageField(blank=True, help_text='The Github avatar PNG.', null=True, upload_to=avatar.utils.get_upload_filename),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='svg',
            field=models.FileField(blank=True, help_text='The custom avatar SVG.', null=True, upload_to=avatar.utils.get_upload_filename),
        ),
    ]
