# Generated by Django 2.1.2 on 2019-03-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_auto_20190114_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseavatar',
            name='autogenerated',
            field=models.BooleanField(default=False),
        ),
    ]
