# Generated by Django 2.1.2 on 2019-03-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_baseavatar_autogenerated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseavatar',
            name='autogenerated',
            field=models.BooleanField(default=False),
        ),
    ]
