# Generated by Django 2.2.4 on 2020-03-26 19:49

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0008_auto_20200301_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarTextOverlayInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('text', models.TextField(blank=True, default='')),
                ('coment', models.TextField(blank=True, default='')),
                ('num_uses_total', models.IntegerField(default=0)),
                ('num_uses_remaining', models.IntegerField(default=0)),
                ('current_uses', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
