# Generated by Django 2.2.24 on 2021-09-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0009_avatartextoverlayinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseavatar',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
