# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 20:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('fulfilled', models.BooleanField(default=False)),
                ('github_username', models.CharField(db_index=True, max_length=255)),
                ('github_meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
