# Generated by Django 2.0 on 2018-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0002_faucetrequest_fulfill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucetrequest',
            name='comment_admin',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='faucetrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faucetrequest',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='faucetrequest',
            name='fulfill_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
