# Generated by Django 2.0.3 on 2018-03-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0003_auto_20180309_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucetrequest',
            name='amount',
            field=models.FloatField(default=0.001),
        ),
    ]
