# Generated by Django 2.0.3 on 2018-03-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0004_faucetrequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucetrequest',
            name='amount',
            field=models.FloatField(default=0.0005),
        ),
    ]
