# Generated by Django 2.0.3 on 2018-03-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0005_auto_20180320_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucetrequest',
            name='input_github_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
