# Generated by Django 2.0.4 on 2018-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0006_faucetrequest_input_github_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucetrequest',
            name='amount',
            field=models.FloatField(default=0.0001),
        ),
    ]
