# Generated by Django 2.0.3 on 2018-04-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0007_auto_20180427_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucetrequest',
            name='amount',
            field=models.FloatField(default=0.00025),
        ),
    ]
