# Generated by Django 2.0.3 on 2018-04-13 14:25

from django.db import migrations


def migrate_fulfillments(apps, schema_editor):
    """Handle the data migration to Faucet with FK to Profile."""
    FaucetRequest = apps.get_model('faucet', 'FaucetRequest')
    Profile = apps.get_model('dashboard', 'Profile')
    faucet_requests = FaucetRequest.objects.all()

    for faucet_request in faucet_requests:
        handle = ''
        if faucet_request.github_username:
            handle = faucet_request.github_username
        elif faucet_request.input_github_username:
            handle = faucet_request.input_github_username

        if handle:
            try:
                profile = Profile.objects.get(handle__iexact=handle)
                faucet_request.profile = profile
                faucet_request.save()
            except Exception as e:
                print(f'Failed to migrate - Handle: ({handle}) - ',
                      f'FaucetRequest: ({faucet_request.pk}) - Error: ({e})')


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0008_faucetrequest_profile'),
    ]

    operations = [
        migrations.RunPython(migrate_fulfillments),
    ]
