# Generated by Django 2.0.4 on 2018-04-30 19:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0009_auto_20180413_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faucetrequest',
            name='input_github_username',
        ),
        migrations.AlterField(
            model_name='faucetrequest',
            name='amount',
            field=models.FloatField(default=0.00025),
        ),
        migrations.AlterField(
            model_name='faucetrequest',
            name='github_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
