# Generated by Django 2.0.7 on 2018-07-23 13:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0010_auto_20180430_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucetrequest',
            name='github_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
