# Generated by Django 2.1 on 2018-08-15 17:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0011_auto_20180723_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucetrequest',
            name='github_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
