# Generated by Django 2.0.7 on 2018-07-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0011_auto_20180723_1315'),
        ('faucet', '0011_auto_20180719_1514'),
    ]

    operations = [
    ]
