# Generated by Django 2.1 on 2018-08-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0012_merge_20180726_2001'),
        ('faucet', '0012_auto_20180815_1751'),
    ]

    operations = [
    ]
