# Generated by Django 2.2.4 on 2021-03-15 02:42

from django.db import migrations, models
import django.db.models.deletion
import economy.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0172_auto_20210216_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('nonce', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('network', models.CharField(blank=True, default='', max_length=255)),
                ('uri', models.CharField(blank=True, default='', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_requests', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
