# Generated by Django 2.2.3 on 2019-09-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questattempt',
            old_name='coupon_code',
            new_name='quest',
        ),
    ]
