# Generated by Django 2.2.3 on 2019-09-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_quest_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=100),
        ),
    ]
