# Generated by Django 2.2.3 on 2019-10-02 00:11

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_profile_referrer'),
        ('quests', '0007_quest_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestPointAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('value', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questpointawards', to='dashboard.Profile')),
                ('questattempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointawards', to='quests.QuestAttempt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
