# Generated by Django 2.2.3 on 2019-10-14 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0009_quest_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quests_created', to='dashboard.Profile'),
        ),
    ]
