# Generated by Django 2.2.3 on 2019-10-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0010_quest_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='value',
            field=models.FloatField(default=1),
        ),
    ]
