# Generated by Django 2.2.3 on 2019-10-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0011_quest_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, default='Beginner', max_length=100),
        ),
        migrations.AlterField(
            model_name='quest',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='questattempt',
            name='success',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
