# Generated by Django 2.2.3 on 2019-10-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0012_auto_20191015_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='questpointaward',
            name='action',
            field=models.CharField(default='Beat', max_length=100),
        ),
    ]
