# Generated by Django 2.2.3 on 2019-10-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0017_quest_ui_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='override_background',
            new_name='background',
        ),
    ]
