# Generated by Django 2.2.3 on 2019-11-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0018_auto_20191028_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='edit_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quest',
            name='background',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('back0', 'back0'), ('back1', 'back1'), ('back2', 'back2'), ('back3', 'back3'), ('back4', 'back4'), ('back5', 'back5'), ('back6', 'back6'), ('back7', 'back7'), ('back8', 'back8'), ('back9', 'back9'), ('back10', 'back10'), ('back11', 'back11'), ('back12', 'back12')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard'), ('Expert', 'Expert')], db_index=True, default='Beginner', max_length=100),
        ),
    ]
