# Generated by Django 2.2.3 on 2019-11-07 22:40

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_hackathonevent_show_results'),
        ('quests', '0020_auto_20191106_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('vote', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True, default='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_feedback', to='dashboard.Profile')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='quests.Quest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
