# Generated by Django 2.2.4 on 2019-12-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_hackathonevent_quest_link'),
        ('quests', '0023_auto_20191204_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='unlocked_by',
        ),
        migrations.AddField(
            model_name='quest',
            name='unlocked_by_hackathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unblocks_quest', to='dashboard.HackathonEvent'),
        ),
        migrations.AddField(
            model_name='quest',
            name='unlocked_by_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unblocks_quest', to='quests.Quest'),
        ),
    ]
