# Generated by Django 2.2.4 on 2020-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0025_questpointaward_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='admin_comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
