# Generated by Django 2.2.4 on 2020-02-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0026_auto_20200213_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='style',
            field=models.CharField(choices=[('Quiz', 'quiz'), ('Code Battle', 'code_battle'), ('Example for Demo', 'example_demo')], default='quiz', max_length=100),
        ),
    ]
