# Generated by Django 2.2.4 on 2020-03-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0025_questpointaward_metadata'),
        ('quests', '0027_auto_20200213_1644'),
    ]

    operations = [
    ]
