export const INIT_APP_COMPLETE = 'INIT_APP_COMPLETE';
export const SEND_TICKET = 'SEND_TICKET';
export const SEND_TICKET_COMPLETE = 'SEND_TICKET_COMPLETE';
export const SESSION_UPDATE_RECEIVED = 'SESSION_UPDATE_RECEIVED';
export const WEB3_INIT_COMPLETE = 'WEB3_INIT_COMPLETE';
