# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 00:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('from_amount', models.FloatField()),
                ('to_amount', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('source', models.CharField(db_index=True, max_length=30)),
                ('from_currency', models.CharField(db_index=True, max_length=30)),
                ('to_currency', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
