# Generated by Django 2.0.6 on 2018-07-02 21:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_auto_20180702_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='token',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
