# Generated by Django 2.2.4 on 2020-10-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_txupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='conversion_rate_id',
            field=models.CharField(blank=True, help_text='unique identifier used by conversion_rate_source', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='conversion_rate_source',
            field=models.CharField(blank=True, choices=[('cryptocompare', 'cryptocompare'), ('poloniex', 'poloniex'), ('uniswap', 'uniswap'), ('manual', 'manual'), ('coingecko', 'coingecko')], help_text='API source', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='conversionrate',
            name='source',
            field=models.CharField(choices=[('cryptocompare', 'cryptocompare'), ('poloniex', 'poloniex'), ('uniswap', 'uniswap'), ('manual', 'manual'), ('coingecko', 'coingecko')], db_index=True, max_length=30),
        ),
    ]
