# Generated by Django 2.1 on 2018-08-15 17:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_auto_20180702_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
