# Generated by Django 2.2.24 on 2021-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_auto_20201014_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='conversion_rate_id',
            field=models.CharField(blank=True, help_text='unique identifier used by conversion_rate_source', max_length=35, null=True),
        ),
    ]
