# Generated by Django 2.1.7 on 2019-04-30 19:55

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0031_auto_20190424_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('status', models.CharField(choices=[('o', 'open'), ('r', 'ready'), ('a', 'active'), ('c', 'closed')], db_index=True, default='o', max_length=1)),
                ('title', models.CharField(help_text='The Session title.', max_length=255)),
                ('description', models.TextField(default='', max_length=500)),
                ('value', models.BigIntegerField(default=0)),
                ('start_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('claim_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('signature', models.CharField(blank=True, max_length=132, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=132, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertSessionInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('signature', models.CharField(max_length=132)),
                ('main_address', models.CharField(max_length=42)),
                ('delegate_address', models.CharField(max_length=42)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='experts.ExpertSession')),
            ],
        ),
        migrations.AddField(
            model_name='expertsession',
            name='accepted_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_session_requests', to='experts.ExpertSessionInterest'),
        ),
        migrations.AddField(
            model_name='expertsession',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_session_requests', to='dashboard.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='expertsessioninterest',
            unique_together={('session', 'profile')},
        ),
    ]
