# Generated by Django 2.0.7 on 2018-07-09 17:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avatar', '0002_auto_20180627_0512'),
        ('dashboard', '0090_auto_20180709_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('description', models.TextField(blank=True)),
                ('gh_repos_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('gh_user_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatar.Avatar')),
                ('followers', models.ManyToManyField(related_name='follows_org', to='dashboard.Profile')),
                ('members', models.ManyToManyField(related_name='organizations', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
