# Generated by Django 2.0.7 on 2018-08-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_profile_tags'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Profile'),
        ),
    ]
