# Generated by Django 2.0.7 on 2018-08-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_organization_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_hiring',
            field=models.BooleanField(default=False, verbose_name='Is Hiring?'),
        ),
    ]
