# Generated by Django 2.1.1 on 2018-09-25 17:49

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_organization_is_hiring'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='gh_admins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='comma delimited', size=None, verbose_name='Github Administrators'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='gh_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Github Data'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='gh_members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='comma delimited', size=None, verbose_name='Github Members'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='gh_repos_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Repository Data'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org', to='dashboard.Profile', verbose_name='Profile'),
        ),
    ]
