# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('gas_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('mean_time_to_confirm_blocks', models.DecimalField(decimal_places=2, max_digits=50)),
                ('mean_time_to_confirm_minutes', models.DecimalField(decimal_places=2, max_digits=50)),
                ('_99confident_confirm_time_blocks', models.DecimalField(decimal_places=2, max_digits=50)),
                ('_99confident_confirm_time_mins', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
