# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasprofile',
            name='gas_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='gasprofile',
            name='mean_time_to_confirm_minutes',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=50),
        ),
    ]
