# Generated by Django 2.0.7 on 2018-07-04 16:21

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0002_auto_20171005_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasAdvisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('body', models.TextField(blank=True, default='')),
                ('active_until', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
