# Generated by Django 2.0.7 on 2018-08-09 15:14

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0004_auto_20180705_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasGuzzler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('gas_used', models.DecimalField(db_index=True, decimal_places=2, max_digits=50)),
                ('pct_total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('ID', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Gas Guzzlers',
            },
        ),
    ]
