# Generated by Django 2.1.2 on 2018-11-14 23:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0005_gasguzzler'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('view', models.CharField(blank=True, default='', max_length=50)),
                ('key', models.CharField(blank=True, default='', max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
