# Generated by Django 2.1.2 on 2018-12-11 18:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0126_auto_20181205_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('title', models.CharField(default='', help_text='The Job title', max_length=255)),
                ('job_type', models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time'), ('intern', 'intern'), ('contractor', 'contractor')], default='full-time', help_text='The Job type', max_length=255)),
                ('job_location', models.CharField(default='', help_text='city where the job is or remote', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='The description of the Job')),
                ('active', models.BooleanField(default=False, help_text='Whether or not the Job is active')),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='The list of Skills')),
                ('company', models.CharField(default='', help_text='The Company hiring', max_length=255)),
                ('github_profile', models.CharField(default='', help_text='user or company profile on github', max_length=255)),
                ('expiry_date', models.DateField(default=job.models.default_job_expiry)),
                ('apply_location', models.CharField(help_text='link to apply to, url or mailto:', max_length=255)),
                ('txid', models.CharField(max_length=255, null=False)),
                ('token_address', models.CharField(default='0x0', help_text='The token address to be used.', max_length=255)),
                ('token_symbol', models.CharField(default='ETH', help_text='The token symbol paid with.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, default=1, help_text='amount of payment.', max_digits=50)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
