#!/bin/bash

# export PULUMI_ACCESS_TOKEN: ***
export PULUMI_CONFIG_PASSPHRASE=
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=

export DB_NAME=
export DB_PASSWORD=
export DB_USER=

export DOCKER_GTC_WEB_IMAGE=
export REVIEW_ENV_VPC_ID=
export REVIEW_ENV_PRIVATE_SUBNET_1=
export REVIEW_ENV_PRIVATE_SUBNET_2=
export REVIEW_ENV_PUBLIC_SUBNET_1=
export REVIEW_ENV_PUBLIC_SUBNET_2=
export REVIEW_ENV_ROUTE53_ZONE_ID=
export REVIEW_ENV_DOMAIN=
export REVIEW_ENV_NAME=

