# Generated by Django 2.0.6 on 2018-06-15 22:43

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0087_auto_20180615_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestreamSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('description', models.TextField(blank=True)),
                ('vod', models.FileField(blank=True, null=True, upload_to='livestream/vods/')),
                ('zoom_id', models.CharField(blank=True, max_length=50)),
                ('zoom_password', models.CharField(blank=True, max_length=50)),
                ('attendees', models.ManyToManyField(blank=True, to='dashboard.Profile')),
            ],
            options={
                'verbose_name_plural': 'Livestream Sessions',
            },
        ),
    ]
