# Generated by Django 2.0.3 on 2018-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='avatar_url',
            field=models.CharField(default='https://avatars0.githubusercontent.com/u/1838338?s=460&v=4', max_length=255),
            preserve_default=False,
        ),
    ]
