# Generated by Django 2.0.3 on 2018-04-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_idea_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
