# Generated by Django 2.0.3 on 2018-04-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_auto_20180403_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='trending_score',
            field=models.IntegerField(default=101),
        ),
    ]
