# Generated by Django 2.2.4 on 2020-01-07 05:14

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20191211_1458'),
        ('townsquare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='key',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('other', 'other')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='dashboard.Activity')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
