# Generated by Django 2.2.4 on 2020-01-09 04:37

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0003_auto_20200108_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('title', models.TextField(blank=True, default='')),
                ('desc', models.TextField(blank=True, default='')),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_to', models.DateTimeField(db_index=True)),
                ('style', models.CharField(choices=[('success', 'success'), ('info', 'info'), ('warning', 'warning')], db_index=True, default='announce1', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='offer',
            name='style',
            field=models.CharField(choices=[('announce1', 'light-pink'), ('announce2', 'blue'), ('announce3', 'teal'), ('announce4', 'yellow'), ('announce5', 'lime-green'), ('announce6', 'pink')], db_index=True, default='announce1', max_length=50),
        ),
    ]
