# Generated by Django 2.2.4 on 2020-01-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("townsquare", "0003_auto_20200128_0725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="from_link",
            field=models.URLField(blank=True),
        ),
    ]
