# Generated by Django 2.2.4 on 2020-01-31 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_profile_as_representation'),
        ('townsquare', '0004_auto_20200129_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='dashboard.Tip'),
        ),
    ]
