# Generated by Django 2.2.4 on 2020-01-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0004_auto_20200109_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='style',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('white', 'white')], db_index=True, default='announce1', help_text='https://getbootstrap.com/docs/4.0/utilities/colors/', max_length=50),
        ),
    ]
