# Generated by Django 2.2.4 on 2020-01-09 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_merge_20200109_2043'),
        ('townsquare', '0005_auto_20200109_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers_created', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='offer',
            name='public',
            field=models.BooleanField(default=True, help_text='Is this available publicly yet?'),
        ),
    ]
