# Generated by Django 2.2.4 on 2020-02-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("townsquare", "0004_auto_20200129_1356"),
        ("townsquare", "0005_auto_20200201_2333"),
    ]

    operations = []
