# Generated by Django 2.2.4 on 2020-02-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("townsquare", "0006_merge_20200204_0824"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="amount",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
