# Generated by Django 2.2.4 on 2020-02-11 04:25

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_auto_20200205_1521'),
        ('townsquare', '0007_auto_20200205_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_to', models.DateTimeField(db_index=True)),
                ('number', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('number', models.IntegerField(default=1)),
                ('contributions', models.IntegerField(default=1)),
                ('contributions_total', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('match_total', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_rankings', to='dashboard.Profile')),
                ('round', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='townsquare.MatchRound')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
