# Generated by Django 2.2.4 on 2020-02-14 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0009_auto_20200212_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
