# Generated by Django 2.2.4 on 2020-02-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0010_comment_likes'),
        ('townsquare', '0005_comment_tip'),
    ]

    operations = [
    ]
