# Generated by Django 2.2.4 on 2020-02-21 19:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0011_matchranking_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchranking',
            name='match_curve',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
