# Generated by Django 2.2.4 on 2020-03-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0012_matchranking_match_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_tip_comment',
            field=models.BooleanField(default=False),
        ),
    ]
