# Generated by Django 2.2.4 on 2020-02-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0012_matchranking_match_curve'),
        ('townsquare', '0011_merge_20200218_0637'),
    ]

    operations = [
    ]
