# Generated by Django 2.2.4 on 2020-03-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_merge_20200303_2256'),
        ('townsquare', '0013_suggestedaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='dashboard.Tip'),
        ),
    ]
