# Generated by Django 2.2.4 on 2020-03-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0013_suggestedaction'),
        ('townsquare', '0013_comment_is_tip_comment'),
    ]

    operations = [
    ]
