# Generated by Django 2.2.4 on 2020-03-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0014_merge_20200304_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_tip_comment',
        ),
    ]
