# Generated by Django 2.2.4 on 2020-03-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0015_remove_comment_is_tip_comment'),
        ('townsquare', '0014_auto_20200319_1901'),
    ]

    operations = [
    ]
