# Generated by Django 2.2.4 on 2020-03-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0016_merge_20200319_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_tip_comment',
            field=models.BooleanField(default=False),
        ),
    ]
