# Generated by Django 2.2.4 on 2020-04-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_auto_20200422_1452'),
        ('townsquare', '0018_comment_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='dashboard.Tip'),
        ),
    ]
