# Generated by Django 2.2.4 on 2020-05-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0112_auto_20200520_1454'),
        ('townsquare', '0019_pinnedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='dashboard.Tip'),
        ),
        migrations.AlterField(
            model_name='pinnedpost',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='dashboard.Activity'),
        ),
    ]
