# Generated by Django 2.2.4 on 2020-04-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0019_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='user',
        ),
        migrations.AlterField(
            model_name='pin',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='dashboard.Activity'),
        ),
    ]
