# Generated by Django 2.2.4 on 2020-04-28 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_auto_20200422_1452'),
        ('townsquare', '0020_auto_20200427_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='hash_what',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='dashboard.Profile'),
            preserve_default=False,
        ),
    ]
