# Generated by Django 2.2.4 on 2020-05-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_auto_20200430_1352'),
        ('townsquare', '0021_auto_20200428_0137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pin',
            new_name='PinnedPost',
        ),
    ]
