# Generated by Django 2.2.4 on 2020-06-30 04:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0022_auto_20200528_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchround',
            name='elegible_round_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
