# Generated by Django 2.2.4 on 2020-10-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0023_auto_20200907_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='key',
            field=models.CharField(choices=[('townsquare', 'townsquare'), ('header', 'header'), ('footer', 'footer'), ('founders_note_daily_email', 'founders_note_daily_email'), ('grants', 'grants')], db_index=True, max_length=50),
        ),
    ]
