# Generated by Django 2.2.24 on 2021-09-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townsquare', '0025_squelchprofile_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squelchprofile',
            name='label',
            field=models.CharField(choices=[('Human', 'Human'), ('Heuristic', 'Heuristic'), ('Prediction', 'Prediction'), ('Manual', 'Manual')], default='Manual', help_text='means used to mark user as sybil', max_length=20),
        ),
    ]
