point_values = {
        'Login': 1,
        'Visit': 1,
        'new_tip': 1,
        'send_tip': 1,
        'new_grant_subscription': 2,
        'new_grant_contribution': 2,
        'new_kudos': 2,
        'new_bounty': 8,
        'worker_approved': 3,
        'worker_rejected': 2,
        'increase_payout': 1,
        'increased_bounty': 1,
        'new_crowdfund': 2,
        'worker_applied': 2,
        'start_work': 3,
        'work_submitted': 5,
        'work_done': 8,
}