#!/bin/bash

export POC_DB_NAME=
export POC_DB_PASSWORD=
export POC_DB_USER=
export POC_PUBLIC_KEY_GE=
export POC_PUBLIC_KEY_GR=

export POC_GITHUB_API_USER=
export POC_GITHUB_API_TOKEN=
export POC_GITHUB_CLIENT_ID=
export POC_GITHUB_CLIENT_SECRET=
export POC_GITHUB_APP_NAME=
