# Generated by Django 2.1.2 on 2019-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardrank',
            name='amount',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaderboardrank',
            name='leaderboard',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterIndexTogether(
            name='leaderboardrank',
            index_together={('leaderboard', 'active')},
        ),
    ]
