# Generated by Django 2.1.7 on 2019-04-06 01:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20190212_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailevent',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
