# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='key',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterIndexTogether(
            name='stat',
            index_together=set([('created_on', 'key')]),
        ),
    ]
