# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20171008_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='val',
            field=models.IntegerField(),
        ),
    ]
