# Generated by Django 2.2.3 on 2019-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20190720_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsupressionlist',
            name='email',
            field=models.TextField(max_length=255),
        ),
    ]
