# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20171008_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='priv',
            field=models.CharField(default='', max_length=30),
        ),
    ]
