# Generated by Django 2.2.3 on 2019-11-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardrank',
            name='product',
            field=models.CharField(db_index=True, default='all', max_length=255),
            preserve_default=False,
        ),
    ]
