# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_profile_repos_data'),
        ('marketing', '0007_leaderboardrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('email', models.EmailField(max_length=255)),
                ('direction', models.CharField(max_length=50)),
                ('github_username', models.CharField(max_length=255)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Bounty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
