# Generated by Django 2.2.4 on 2020-02-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0008_leaderboardrank_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingcallback",
            name="msg",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
