# Generated by Django 2.2.3 on 2019-10-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_tokenairdrop_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenairdrop',
            name='token_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
