# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 02:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='github',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
    ]
