# Generated by Django 2.2.4 on 2020-03-26 02:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_manualstat_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundupEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('from_email', models.EmailField(max_length=255)),
                ('from_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, max_length=5000)),
                ('kudos_ids', models.CharField(help_text='kudosid1,kudosid2,kudosid3', max_length=255)),
                ('highlights', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('sponsor', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('bounties_spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
