# Generated by Django 2.2.4 on 2020-04-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_roundupemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualstat',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
