# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_auto_20180101_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubOrgToTwitterHandleMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('github_orgname', models.CharField(max_length=500)),
                ('twitter_handle', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
