# Generated by Django 2.2.4 on 2020-06-30 20:23

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_auto_20200626_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('key', models.CharField(choices=[('google_analytics', 'google_analytics'), ('other', 'other')], db_index=True, max_length=255)),
                ('search_string', models.CharField(blank=True, db_index=True, max_length=255)),
                ('value', models.TextField(blank=True, max_length=5000)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
