# Generated by Django 2.2.4 on 2020-08-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_auto_20200626_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundupemail',
            name='hide_dynamic',
            field=models.BooleanField(default=False),
        ),
    ]
