# Generated by Django 2.0 on 2018-03-08 06:19

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_githuborgtotwitterhandlemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('status', models.CharField(max_length=50)),
                ('slackuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='marketing.SlackUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
