# Generated by Django 2.0 on 2018-03-08 06:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20180228_0924'),
        ('marketing', '0016_slackpresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_events', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
