# Generated by Django 2.2.4 on 2020-09-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_auto_20200903_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingdate',
            name='context_tag',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
