# Generated by Django 2.0 on 2018-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_githubevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubevent',
            name='what',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
