# Generated by Django 2.2.4 on 2020-09-09 09:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_auto_20200903_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundupemail',
            name='kudos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
