# Generated by Django 2.2.4 on 2020-09-25 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_roundupemail_kudos'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingdate',
            name='last_modified',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 9, 25, 9, 44, 19, 299543)),
        ),
        migrations.AddField(
            model_name='upcomingdate',
            name='sequence',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upcomingdate',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
