# Generated by Django 2.0 on 2018-03-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_emailevent'),
        ('marketing', '0019_githubevent_repo'),
    ]

    operations = [
    ]
