# Generated by Django 2.2.4 on 2020-10-07 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_auto_20200925_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingdate',
            name='last_modified',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 10, 7, 11, 52, 56, 242963)),
        ),
    ]
