# Generated by Django 2.0.3 on 2018-04-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20180405_0806'),
        ('marketing', '0020_merge_20180308_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_subscriptions', to='dashboard.Profile'),
        ),
    ]
