# Generated by Django 2.0.4 on 2018-04-19 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0021_emailsubscriber_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='repos',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='slack_channel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='slack_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
