# Generated by Django 2.0.4 on 2018-05-07 20:57

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0021_emailsubscriber_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('organization', models.CharField(blank=True, db_index=True, max_length=255)),
                ('comments', models.TextField(max_length=5000)),
                ('public', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
