# Generated by Django 2.0.4 on 2018-05-07 16:46

from django.db import migrations


def insert_alumni(apps, schema_editor):
    Alumni = apps.get_model('marketing', 'Alumni')
    elements = [
        ('PixelantDesign', 'gitcoinco'),
        ('mbeacom', 'gitcoinco'),
        ('StareIntoTheBeard', 'gitcoinco'),
        ('thelostone-mc', 'gitcoinco'),
        ('KamesCG', 'uport'),
        ('SaptakS', 'gitcoinco'), # TODO: Do Gitcoinco alumni count?
        ('eswarasai', 'MARKETProtocol'),
        ('Perfectmak', 'MARKETProtocol'),
        ('lazaridiscom', 'Metamask'),
        ('voith', 'ethereum'),
        ('dylanjw', 'ethereum'),
    ]
    for ele in elements:
        Alumni.objects.create(
            username=ele[0],
            organization=ele[1],
            comments='Auto generated alumni by marketing.migraitons.0023',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0022_alumni'),
    ]

    operations = [
        migrations.RunPython(insert_alumni),
    ]
