# Generated by Django 2.0.5 on 2018-05-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0022_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='comments',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
