# Generated by Django 2.0.4 on 2018-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0023_auto_20180507_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
