# Generated by Django 2.2.4 on 2020-10-13 02:26

from django.db import migrations


def forwards(apps, schema_editor):
    email_info = {
        '/new_bounty_daily': ('daily', 'GA','https://github.com/gitcoinco/web/pull/6728','2020',''),
        '/grant_cancellation': ('transactional', 'grants','','2018','',''),
        '/request_amount_email': ('transactional', 'GA','https://github.com/gitcoinco/web/pull/6760','2020',''),
        '/featured_funded_bounty': ('transactional', 'bounties','','2018',''),
        '/subscription_terminated': ('transactional', 'grants','','2018',''),
        '/new_grant': ('transactional', 'grants','','2018',''),
        '/new_supporter': ('transactional', 'grants','','2018',''),
        '/thank_you_for_supporting': ('transactional', 'grants','','2018',''),
        '/support_cancellation': ('transactional', 'grants','','2018',''),
        '/successful_contribution': ('transactional', 'grants','https://github.com/gitcoinco/web/commit/b55e1c84c403dc4334df6c6c68b60624c589fd9b', '2018','',''),
        '/pending_contributions': ('once/grants round', 'grants','https://github.com/gitcoinco/web/pull/7645','2020',''),
        '/new_kudos': ('transactional', 'kudos','https://github.com/gitcoinco/web/pull/2492','2018',''),
        '/kudos_mint': ('transactional', 'kudos','https://github.com/gitcoinco/web/pull/2492','2018',''),
        '/kudos_mkt': ('launch', 'kudos','https://github.com/gitcoinco/web/pull/2492','2018',''),
        '/new_bounty': ('duplicate?', 'bounty','','2017',''),
        '/roundup': ('weekly', 'GA','https://gitcoin.co/_administrationmarketing/roundupemail/','2020',''),
        '/faucet_rejected': ('transactional', 'faucet','https://github.com/gitcoinco/web/commit/a4a346c11e95f8048d5b6723720a984e8a0eddfa','2018',''),
        '/faucet': ('transactional', 'facuet','','2018',''),
        '/new_tip': ('transactional', 'tip','','2017',''),
        '/new_match': ('transactional', 'bounties','https://github.com/gitcoinco/web/commit/41c4c5d0b968bc5575fb1c595602c4f0595b3615', '2018','pls purge',''),
        '/quarterly_roundup': ('quarterly', 'GA', 'https://github.com/gitcoinco/web/issues/946','2019','pls purge',''),
        '/new_work_submission': ('transactional', 'bounties','','2017',''),
        '/weekly_founder_recap': ('unknown/broken', 'bounties', 'https://github.com/gitcoinco/web/issues/3013','2018','pls purge',''),
        '/weekly_unread_notifications_email': ('weekly', 'GA','https://github.com/gitcoinco/web/pull/3959','2018', 'pls purge',''),
        '/new_bounty_rejection': ('transactional', 'bounties','','2017',''),
        '/comment': ('transactional', 'GA','https://github.com/gitcoinco/web/commit/81c68914e06d23ee7b7d28e27e4b633fc37dafb3','2020',''),
        '/mention': ('transactional', 'GA','https://github.com/gitcoinco/web/pull/5839','2020',''),
        '/wallpost': ('transactional', 'GA','https://github.com/gitcoinco/web/commit/11dadb83c8cb6ca76427786d304dbd8fbe77695f','2020',''),
        '/grant_update': ('transactional', 'grants','','2020',''),
        '/grant_recontribute': ('once/grants round', 'grants','','2020',''),
        '/grant_txn_failed': ('transactional', 'grants','https://github.com/gitcoinco/web/pull/6791','2020',''),
        '/new_bounty_acceptance': ('transactional', 'bounties','','2017',''),
        '/bounty_expire_warning': ('transactional', 'bounties','','2017',''),
        '/bounty_feedback': ('admin/transactional', 'bounties','https://github.com/gitcoinco/web/commit/bc539c3c31657eb1cf8da8086286ab30e9022c0e','2017',''),
        '/funder_stale': ('admin/transactional', 'bounties','https://github.com/gitcoinco/web/commit/b956d1dc485f8f697ffaaa65925b4b916a436c53','2017',''),
        '/start_work_expire_warning': ('transactional', 'bounties','','2017',''),
        '/start_work_expired': ('transactional', 'bounties','','2017',''),
        '/gdpr_reconsent': ('old', 'GA','https://github.com/gitcoinco/web/pull/1249','2018',''),
        '/share_bounty': ('transactional', 'bounties','https://github.com/gitcoinco/web/pull/3672','2018',''),
        '/new_tip/resend': ('transactional', 'tips','https://github.com/gitcoinco/web/commit/80d1a994e9c6ca601259b67b7d3bdc76353892be','2018',''),
        '/tribe_hackathon_prizes': ('once/hackathon', 'hackathons', 'https://github.com/gitcoinco/web/pull/7146','2020','broken?',''),
        '/day_email_campaign/<int:day>': ('onboarding', 'GA', 'https://github.com/gitcoinco/web/pull/3766','2018','pls purge',''),
        '/start_work_approved': ('transactional', 'bounties','','2017',''),
        '/start_work_rejected': ('transactional', 'bounties','','2017',''),
        '/start_work_new_applicant': ('transactional', 'bounties','','2017',''),
        '/start_work_applicant_about_to_expire': ('transactional', 'bounties','','2017',''),
        '/start_work_applicant_expired': ('transactional', 'bounties','','2017',''),
        '/funder_payout_reminder': ('transactional', 'bounties','https://github.com/gitcoinco/web/pull/3894','2018',''),
        '/no_applicant_reminder': ('transactional', 'bounties','https://github.com/gitcoinco/web/pull/5062','2019',''),
        '/match_distribution': ('transactional', 'grants', 'https://github.com/gitcoinco/web/commit/6cb80e9384abebf125a62112a5e5c183e9e6bbf9', '2020',''),
    }

    EmailInventory = apps.get_model('marketing', 'EmailInventory')
    for key, val in email_info.items():
        EmailInventory.objects.create(
            path=key,
            type=val[0],
            product=val[1],
            era=val[3],
            comment=val[4],
            url=val[2],
            stats={},
            )

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0023_auto_20201013_0225'),
    ]

    operations = [
         migrations.RunPython(forwards, backwards),
    ]
