# Generated by Django 2.0.5 on 2018-05-23 21:44

from django.db import migrations


def forwards_func(apps, schema_editor):
    EmailSubscriber = apps.get_model('marketing', 'EmailSubscriber')
    for es in EmailSubscriber.objects.all():
        es.save()


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0023_auto_20180515_1510'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
        ),
    ]
