# Generated by Django 2.0.5 on 2018-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0024_auto_20180523_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardrank',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardrank',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
