# Generated by Django 2.2.4 on 2020-10-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0024_auto_20201013_0226'),
        ('marketing', '0021_auto_20201007_1153'),
    ]

    operations = [
    ]
