# Generated by Django 2.0.5 on 2018-05-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0025_auto_20180525_1943'),
        ('marketing', '0025_emailsubscriber_form_submission_records'),
    ]

    operations = [
    ]
