# Generated by Django 2.0.5 on 2018-05-28 23:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0025_auto_20180525_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='form_submission_records',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
    ]
