# Generated by Django 2.2.4 on 2020-10-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0025_merge_20201013_0321'),
        ('marketing', '0022_auto_20201012_0825'),
    ]

    operations = [
    ]
