# Generated by Django 2.0.5 on 2018-05-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0025_auto_20180525_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailevent',
            name='ip_address',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
