# Generated by Django 2.2.4 on 2020-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0026_merge_20201014_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailinventory',
            name='url',
            field=models.URLField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='upcomingdate',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
