# Generated by Django 2.0.5 on 2018-05-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0025_emailsubscriber_form_submission_records'),
        ('marketing', '0026_emailsubscriber_form_submission_records'),
    ]

    operations = [
    ]
