# Generated by Django 2.0.5 on 2018-05-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0027_auto_20180528_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailevent',
            name='payload',
        ),
    ]
