# Generated by Django 2.2.4 on 2020-11-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0027_auto_20201014_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingdate',
            name='last_modified',
            field=models.DateTimeField(db_index=True),
        ),
    ]
