# Generated by Django 2.2.4 on 2021-03-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0028_auto_20201111_1252'),
        ('marketing', '0022_auto_20201121_1751'),
    ]

    operations = [
    ]
