# Generated by Django 2.0.5 on 2018-06-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0027_merge_20180529_2228'),
        ('marketing', '0028_remove_emailevent_payload'),
    ]

    operations = [
    ]
