# Generated by Django 2.2.4 on 2021-02-08 14:35

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0028_auto_20201111_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigestEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('from_email', models.EmailField(max_length=255)),
                ('from_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, max_length=15000)),
                ('bounties_spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('upcoming_hackathon_spec', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('release_date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
