# Generated by Django 2.2.4 on 2020-11-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0028_auto_20201111_0445'),
        ('marketing', '0028_auto_20201111_1252'),
    ]

    operations = [
    ]
