# Generated by Django 2.2.24 on 2021-10-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0028_auto_20201111_1252'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='leaderboardrank',
            index_together={('leaderboard', 'active', 'product', 'amount', 'github_username'), ('leaderboard', 'active'), ('leaderboard', 'active', 'product', 'amount'), ('leaderboard', 'active', 'product')},
        ),
    ]
