# Generated by Django 2.2.24 on 2021-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0029_auto_20211012_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='email_index',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
