# Generated by Django 2.0.7 on 2018-07-26 21:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0030_emailsupressionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardrank',
            name='tech_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
        ),
    ]
