# Generated by Django 2.2.4 on 2021-02-08 21:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0030_hackathonmarketingemail_hackathonsummaryemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathonsummaryemail',
            old_name='bounties_spec',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='hackathonmarketingemail',
            name='upcoming_hackathon_spec',
        ),
        migrations.AddField(
            model_name='hackathonsummaryemail',
            name='features_2',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
