# Generated by Django 2.2.24 on 2021-10-12 16:35

from django.db import migrations

def forwards(apps, schema_editor):
    EmailSubscriber = apps.get_model('marketing', 'EmailSubscriber')
    for es in EmailSubscriber.objects.all():
        print(es.pk)
        es.save()

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0030_emailsubscriber_email_index'),
    ]

    operations = [
         migrations.RunPython(forwards, backwards),
    ]
