# Generated by Django 2.1.1 on 2018-09-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_auto_20180823_1626'),
        ('marketing', '0031_auto_20180815_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardrank',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboard_ranks', to='dashboard.Profile'),
        ),
    ]
