# Generated by Django 2.0.7 on 2018-07-05 21:38

from django.db import migrations


def forwards_func(apps, schema_editor):
    ProgrammingLanguage = apps.get_model('marketing', 'ProgrammingLanguage')
    names = ['css', 'solidity', 'python', 'javascript', 'ruby', 'html', 'design']
    names += [
      '.NET', 'ASP .NET', 'Angular', 'Backbone', 'Bootstrap', 'C', 'C#', 'C++', 'CSS', 'CSS3',
      'CoffeeScript', 'Dart', 'Django', 'Drupal', 'DynamoDB', 'ElasticSearch', 'Ember', 'Erlang', 'Express', 'Go', 'Groovy',
      'Grunt', 'HTML', 'Hadoop', 'Jasmine', 'Java', 'JavaScript', 'Jekyll', 'Knockout', 'LaTeX', 'Mocha', 'MongoDB',
      'MySQL', 'NoSQL', 'Node.js', 'Objective-C', 'Oracle', 'PHP', 'Perl', 'Polymer', 'Postgres', 'Python', 'R', 'Rails',
      'React', 'Redis', 'Redux', 'Ruby', 'SASS', 'Scala', 'Sqlite', 'Swift', 'TypeScript', 'Websockets', 'WordPress', 'jQuery'
    ]
    for name in names:
        ProgrammingLanguage.objects.create(name=name)



class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0031_programminglanguage'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
        ),
    ]

