# Generated by Django 2.1 on 2018-09-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0031_auto_20180815_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailevent',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
