# Generated by Django 2.1.1 on 2018-09-05 15:48

from django.db import migrations, models


def migrate_leaderboard_profile(apps, schema_editor):
    """Migrate LeaderboardRank to include Profile relation."""
    LeaderboardRank = apps.get_model('marketing', 'LeaderboardRank')
    Profile = apps.get_model('dashboard', 'Profile')
    for rank in LeaderboardRank.objects.filter(active=True):
        try:
            profile = Profile.objects.get(handle=rank.github_username)
            rank.profile = profile
            rank.save()
        except Profile.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0032_leaderboardrank_profile'),
    ]

    operations = [
        migrations.RunPython(migrate_leaderboard_profile),
    ]
