# Generated by Django 2.1.1 on 2018-09-17 20:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0035_accountdeletionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeletionrequest',
            name='profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
