# Generated by Django 2.1.2 on 2018-11-27 00:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0037_auto_20181113_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardrank',
            name='tech_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
