# Generated by Django 2.0.5 on 2018-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hop',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='txid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hop',
            name='web3_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
