# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('title', models.CharField(max_length=30)),
                ('web3_created', models.DateField()),
                ('value_in_token', models.PositiveIntegerField(default=1)),
                ('token_name', models.CharField(max_length=30)),
                ('token_address', models.CharField(max_length=30)),
                ('bounty_type', models.CharField(choices=[('bug', 'bug'), ('security', 'security'), ('feature', 'feature'), ('unknown', 'unknown')], max_length=30)),
                ('project_length', models.CharField(choices=[('hours', 'hours'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('unknown', 'unknown')], max_length=30)),
                ('experience_level', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('unknown', 'unknown')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
