# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170916_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='value_in_token',
            field=models.BigIntegerField(default=1),
        ),
    ]
