# Generated by Django 2.1.2 on 2019-01-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_labsresearch_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
