# Generated by Django 2.1.4 on 2019-01-03 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profile_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bounty_reserved_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_bounties', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Visit', 'Visit'), ('added_slack_integration', 'Added Slack Integration'), ('removed_slack_integration', 'Removed Slack Integration'), ('updated_avatar', 'Updated Avatar'), ('account_disconnected', 'Account Disconnected')], max_length=50),
        ),
    ]
