# Generated by Django 2.1.2 on 2019-01-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190103_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
