# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ip',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
