'''
    Copyright (C) 2017 Gitcoin Core 

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

'''
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 18:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_subscription_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bounty_owner_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='bounty_owner_github_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='claimee_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='claimee_github_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='claimee_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='bounty',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
