# Generated by Django 2.1.4 on 2019-01-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bounty_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this bounty is featured'),
        ),
    ]
