# Generated by Django 2.1.4 on 2019-01-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bounty_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='funder_last_messaged_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bountyfulfillment',
            name='funder_last_notified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
