# Generated by Django 2.1.2 on 2019-01-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181227_1957'),
        ('dashboard', '0006_bounty_estimated_hours'),
    ]

    operations = [
    ]
