# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170920_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='current_bounty',
            field=models.BooleanField(default=False),
        ),
    ]
