# Generated by Django 2.1.4 on 2019-01-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_bountycomment_feedbackentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountycomment',
            name='commentreceiver',
        ),
        migrations.RemoveField(
            model_name='bountycomment',
            name='commentsender',
        ),
        migrations.RemoveField(
            model_name='bountycomment',
            name='fulfillment',
        ),
        migrations.DeleteModel(
            name='BountyComment',
        ),
    ]
