# Generated by Django 2.1.5 on 2019-01-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190115_0528'),
        ('dashboard', '0008_auto_20190120_1907'),
    ]

    operations = [
    ]
