# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_bounty_current_bounty'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountySyncRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('github_url', models.URLField()),
                ('processed', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
