# Generated by Django 2.1.5 on 2019-01-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190120_1907'),
        ('dashboard', '0008_remove_profile_avatar'),
    ]

    operations = [
    ]
