# Generated by Django 2.1.5 on 2019-01-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_merge_20190122_0857'),
        ('dashboard', '0009_merge_20190122_2108'),
    ]

    operations = [
    ]
