# Generated by Django 2.1.4 on 2019-01-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_merge_20190122_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this bounty is featured'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_search_status',
            field=models.CharField(blank=True, choices=[('AL', 'Actively looking for work'), ('PL', 'Passively looking and open to hearing new opportunities'), ('N', 'Not open to hearing new opportunities')], max_length=2),
        ),
    ]
