# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_bountysyncrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='value_in_token',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
        ),
    ]
