# Generated by Django 2.1.5 on 2019-02-05 19:11

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190130_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='remote',
            field=models.BooleanField(default=False, help_text='If this option is chosen, profile is okay with remote job'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
