# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170920_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='expires_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='web3_created',
            field=models.DateTimeField(),
        ),
    ]
