# Generated by Django 2.1.2 on 2019-01-30 18:52

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190130_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='created_on',
            field=models.DateTimeField(db_index=True, default=economy.models.get_time),
        ),
        migrations.AddField(
            model_name='interest',
            name='modified_on',
            field=models.DateTimeField(default=economy.models.get_time),
        ),
    ]
