# Generated by Django 2.1.5 on 2019-02-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190131_2149'),
        ('dashboard', '0011_auto_20190129_0443'),
    ]

    operations = [
    ]
