# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20170921_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='_val_usd_db',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=20),
        ),
    ]
