# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_bounty__val_usd_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='contract_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
