# Generated by Django 2.1.2 on 2019-02-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190130_1853'),
        ('dashboard', '0013_bounty_featuring_date'),
    ]

    operations = [
    ]
