# Generated by Django 2.1.5 on 2019-02-14 09:16

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_merge_20190221_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='repo_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=50),
        ),
        migrations.AddField(
            model_name='bounty',
            name='unsigned_nda',
            field=models.FileField(blank=True, help_text='NDA for private repos.', null=True, upload_to=app.utils.get_upload_filename),
        ),
        migrations.AddField(
            model_name='interest',
            name='nda_signed',
            field=models.FileField(blank=True, help_text='NDA signed by applicant.', null=True, upload_to=app.utils.get_upload_filename),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='The profile resume.', null=True, upload_to=app.utils.get_upload_filename),
        ),
    ]
