# Generated by Django 2.1.7 on 2019-02-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_merge_20190205_0434'),
        ('dashboard', '0013_bounty_featuring_date'),
    ]

    operations = [
    ]
