# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_bounty_contract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='network',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
