# Generated by Django 2.1.7 on 2019-02-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_bounty_featuring_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bounty_reserved_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
