# Generated by Django 2.1.5 on 2019-02-15 11:04

import app.utils
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190214_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('doc', models.FileField(blank=True, help_text='Bounty documents.', null=True, upload_to=app.utils.get_upload_filename)),
                ('doc_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='interest',
            name='nda_signed',
        ),
        migrations.AlterField(
            model_name='bounty',
            name='unsigned_nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsignednda', to='dashboard.BountyDocuments'),
        ),
        migrations.AddField(
            model_name='interest',
            name='signed_nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signednda', to='dashboard.BountyDocuments'),
        ),
    ]
