# Generated by Django 2.1.7 on 2019-03-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_merge_20190218_1651'),
        ('dashboard', '0014_merge_20190221_2246'),
    ]

    operations = [
    ]
