# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_bounty_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='_val_usd_db',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
