# Generated by Django 2.1.7 on 2019-03-07 16:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0015_auto_20190301_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyInvites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted')], max_length=20)),
                ('bounty', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Bounty')),
                ('invitee', models.ManyToManyField(blank=True, related_name='invitee', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ManyToManyField(blank=True, related_name='inviter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
