# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20170928_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='idx_experience_level',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='bounty',
            name='idx_project_length',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Security', 'Security'), ('Feature', 'Feature'), ('Unknown', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Unknown', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='project_length',
            field=models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Unknown', 'Unknown')], max_length=50),
        ),
    ]
