# Generated by Django 2.1.7 on 2019-03-13 13:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0015_merge_20190225_1422'),
        ('dashboard', '0015_auto_20190308_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='grants.Grant'),
        ),
    ]
