# Generated by Django 2.1.7 on 2019-03-08 15:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190307_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountyinvites',
            name='bounty',
        ),
        migrations.AddField(
            model_name='bountyinvites',
            name='bounty',
            field=models.ManyToManyField(blank=True, related_name='bounty', to='dashboard.Bounty'),
        ),
    ]
