# Generated by Django 2.1.7 on 2019-03-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190301_1625'),
        ('dashboard', '0016_auto_20190305_1443'),
    ]

    operations = [
    ]
