# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20170928_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='idx_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
