# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_bounty_idx_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('emails', models.TextField()),
                ('url', models.CharField(default='', max_length=255)),
                ('tokenName', models.CharField(max_length=255)),
                ('tokenAddress', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=50)),
                ('comments', models.TextField(default='')),
                ('ip', models.CharField(max_length=50)),
                ('expires_date', models.DateTimeField()),
                ('github_url', models.URLField(null=True)),
                ('from_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
