# Generated by Django 2.1.7 on 2019-03-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_merge_20190305_2048'),
        ('dashboard', '0015_auto_20190228_1027'),
    ]

    operations = [
    ]
