# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 14:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='emails',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
