# Generated by Django 2.1.7 on 2019-03-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_bountyinvites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountyinvites',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('completed', 'completed')], max_length=20),
        ),
    ]
