# Generated by Django 2.1.2 on 2019-03-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20190312_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
