# Generated by Django 2.1.7 on 2019-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20190312_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='fee_amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='bounty',
            name='fee_tx_id',
            field=models.CharField(blank=True, default='0x0', max_length=255),
        ),
    ]
