# Generated by Django 2.1.7 on 2019-03-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0017_matchpledge_end_date'),
        ('dashboard', '0020_auto_20190312_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='grants.Grant'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='grants.Subscription'),
        ),
    ]
