# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_tip_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='network',
            field=models.CharField(default='', max_length=255),
        ),
    ]
