# Generated by Django 2.1.7 on 2019-03-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20190319_1502'),
        ('dashboard', '0021_profile_custom_tagline'),
    ]

    operations = [
    ]
