# Generated by Django 2.1.7 on 2019-03-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20190315_1421'),
        ('dashboard', '0020_auto_20190312_0739'),
    ]

    operations = [
    ]
