# Generated by Django 2.1.7 on 2019-03-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20190315_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='fee_amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=50),
        ),
    ]
