# Generated by Django 2.1.7 on 2019-03-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_profile_custom_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackentry',
            name='code_quality_rating',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='feedbackentry',
            name='communication_rating',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='feedbackentry',
            name='recommendation_rating',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='feedbackentry',
            name='satisfaction_rating',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='feedbackentry',
            name='speed_rating',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
