# Generated by Django 2.1.7 on 2019-03-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_merge_20190325_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='unsigned_nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty', to='dashboard.BountyDocuments'),
        ),
        migrations.AlterField(
            model_name='bountyinvites',
            name='bounty',
            field=models.ManyToManyField(blank=True, related_name='bountyinvites', to='dashboard.Bounty'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='signed_nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest', to='dashboard.BountyDocuments'),
        ),
    ]
