# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20171002_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='avatar_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
