# Generated by Django 2.1.7 on 2019-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_merge_20190319_1251'),
        ('dashboard', '0024_auto_20190326_1759'),
    ]

    operations = [
    ]
