# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 17:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='repos_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
