# Generated by Django 2.1.7 on 2019-04-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20190401_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='actions_count',
            field=models.IntegerField(default=3),
        ),
    ]
