# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_profile_repos_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bounty',
            options={'verbose_name_plural': 'Bounties'},
        ),
    ]
