# Generated by Django 2.1.7 on 2019-03-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_profile_actions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fee_percentage',
            field=models.IntegerField(default=10),
        ),
    ]
