# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20171215_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=50),
        ),
    ]
