# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20171228_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='standard_bounties_id',
            field=models.IntegerField(default=0),
        ),
    ]
