# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20171228_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='github_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='current_bounty',
            field=models.BooleanField(default=False, help_text='whether this bounty is the most current revision one or not'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='is_open',
            field=models.BooleanField(help_text='Whether the bounty has been filled'),
        ),
    ]
