# Generated by Django 2.1.7 on 2019-04-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20190424_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matches_interested',
            field=models.ManyToManyField(blank=True, related_name='_profile_matches_interested_+', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='matches_not_interested',
            field=models.ManyToManyField(blank=True, related_name='_profile_matches_not_interested_+', to='dashboard.Profile'),
        ),
    ]
