# Generated by Django 2.1.7 on 2019-05-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20190424_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='attached_job_description',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_owner_github_username',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_type',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Security', 'Security'), ('Feature', 'Feature'), ('Unknown', 'Unknown')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='current_bounty',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this bounty is the most current revision one or not'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Unknown', 'Unknown')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='featuring_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='permission_type',
            field=models.CharField(choices=[('permissionless', 'permissionless'), ('approval', 'approval')], db_index=True, default='permissionless', max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='project_type',
            field=models.CharField(choices=[('traditional', 'traditional'), ('contest', 'contest'), ('cooperative', 'cooperative')], db_index=True, default='traditional', max_length=50),
        ),
    ]
