# Generated by Django 2.1.7 on 2019-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20190424_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bounty_category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
