# Generated by Django 2.0 on 2018-01-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20180105_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bounty',
            name='interested_comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='standard_bounties_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_access_token',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='interest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='interested',
            field=models.ManyToManyField(to='dashboard.Interest'),
        ),
    ]
