# Generated by Django 2.0 on 2018-01-24 19:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20180105_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bounty',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Whether the bounty has been accepted'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='bounty',
            name='bounty_owner_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='claimee_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='interested_comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='num_fulfillments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bounty',
            name='standard_bounties_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bounty',
            name='web3_type',
            field=models.CharField(default='bounties_network', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_access_token',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='_val_usd_db',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='claimee_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='claimee_github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='claimee_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='is_open',
            field=models.BooleanField(help_text='Whether the bounty is still open for fulfillments.'),
        ),
        migrations.AddField(
            model_name='interest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='interested',
            field=models.ManyToManyField(to='dashboard.Interest'),
        ),
    ]
