# Generated by Django 2.1.7 on 2019-05-31 16:46

from django.db import migrations

def forwards(apps, schema_editor):
    from dashboard.models import Profile
    Profile.objects.filter(max_tip_amount_usdt_per_tx=500).update(max_tip_amount_usdt_per_tx=2500)
    Profile.objects.filter(max_tip_amount_usdt_per_week=1500).update(max_tip_amount_usdt_per_week=20000)


def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20190531_1646'),
    ]

    operations = [
         migrations.RunPython(forwards, backwards),
    ]
