# Generated by Django 2.0 on 2018-01-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20180124_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='web3_type',
            field=models.CharField(default='bounties_network', max_length=50),
        ),
    ]
