# Generated by Django 2.0 on 2018-01-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20180116_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='num_fulfillments',
            field=models.IntegerField(default=0),
        ),
    ]
