# Generated by Django 2.0 on 2018-01-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_bounty_num_fulfillments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Whether the bounty has been accepted'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='is_open',
            field=models.BooleanField(help_text='Whether the bounty is still open for fulfillments.'),
        ),
    ]
