# Generated by Django 2.0 on 2018-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_bounty_web3_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='web3_type',
            field=models.CharField(default='bounties_network', max_length=50),
        ),
    ]
