# Generated by Django 2.1.7 on 2019-06-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_bounty_bounty_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='identifier',
            field=models.CharField(default='', max_length=255),
        ),
    ]
