# Generated by Django 2.0 on 2018-01-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20180125_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='claimeee_address',
            new_name='fulfiller_address',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='claimee_email',
            new_name='fulfiller_email',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='claimee_github_username',
            new_name='fulfiller_github_username',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='claimee_metadata',
            new_name='fulfiller_metadata',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='claimee_name',
            new_name='fulfiller_name',
        ),
        migrations.AlterField(
            model_name='bounty',
            name='interested',
            field=models.ManyToManyField(blank=True, to='dashboard.Interest'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='interested_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='issue_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
