# Generated by Django 2.1.7 on 2019-06-17 06:21

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_bounty_bounty_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_banner',
            field=models.FileField(blank=True, help_text='The profile banner image.', null=True, upload_to=app.utils.get_upload_filename),
        ),
    ]
