# Generated by Django 2.1.7 on 2019-06-17 15:49

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_bounty_bounty_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='admin_override_org_logo',
            field=models.ImageField(blank=True, help_text='Organization Logo - Override', null=True, upload_to=app.utils.get_upload_filename),
        ),
        migrations.AddField(
            model_name='bounty',
            name='admin_override_org_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_override_avatar',
            field=models.ImageField(blank=True, help_text='override profile avatar', null=True, upload_to=app.utils.get_upload_filename),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_override_name',
            field=models.CharField(blank=True, help_text='override profile name.', max_length=255),
        ),
    ]
