# Generated by Django 2.1.7 on 2019-06-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_hackathonevent_identifier'),
        ('dashboard', '0034_data_for_old_grants'),
        ('dashboard', '0033_auto_20190531_1646'),
    ]

    operations = [
    ]
