# Generated by Django 2.0 on 2018-01-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20180119_1549'),
        ('dashboard', '0034_auto_20180119_1019'),
    ]

    operations = [
    ]
