# Generated by Django 2.1.7 on 2019-06-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_hackathonevent_identifier'),
        ('dashboard', '0034_data_for_old_grants'),
    ]

    operations = [
    ]
