# Generated by Django 2.0 on 2018-01-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_merge_20180122_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='_val_usd_db',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
