# Generated by Django 2.0 on 2018-01-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20180129_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bounty',
            options={},
        ),
        migrations.AlterField(
            model_name='bounty',
            name='github_url',
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='idx_status',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='network',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='web3_created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='bounty',
            index_together={('network', 'idx_status')},
        ),
    ]
