# Generated by Django 2.1.7 on 2019-06-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20190531_1646'),
        ('dashboard', '0035_merge_20190620_1248'),
    ]

    operations = [
    ]
