# Generated by Django 2.0 on 2018-01-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20180122_1522'),
        ('dashboard', '0035_merge_20180119_1818'),
    ]

    operations = [
    ]
