# Generated by Django 2.0 on 2018-01-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_bountyfulfillment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bountyfulfillment',
            old_name='address',
            new_name='fulfiller_address',
        ),
        migrations.RenameField(
            model_name='bountyfulfillment',
            old_name='email',
            new_name='fulfiller_email',
        ),
        migrations.RenameField(
            model_name='bountyfulfillment',
            old_name='github_username',
            new_name='fulfiller_github_username',
        ),
        migrations.RenameField(
            model_name='bountyfulfillment',
            old_name='metadata',
            new_name='fulfiller_metadata',
        ),
        migrations.RenameField(
            model_name='bountyfulfillment',
            old_name='name',
            new_name='fulfiller_name',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_address',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_email',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_github_username',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_metadata',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_name',
        ),
    ]
