# Generated by Django 2.1.7 on 2019-06-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20190624_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_wallpaper',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
