# Generated by Django 2.1.7 on 2019-06-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_merge_20190622_0828'),
        ('dashboard', '0034_auto_20190524_1229'),
    ]

    operations = [
    ]
