# Generated by Django 2.0 on 2018-02-11 18:34

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20180130_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('shortcode', models.CharField(default='', max_length=255)),
                ('url', models.URLField(null=True)),
                ('network', models.CharField(default='', max_length=255)),
                ('token_name', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=1)),
                ('expires_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoinRedemptionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('txid', models.CharField(default='', max_length=255)),
                ('txaddress', models.CharField(max_length=255)),
                ('sent_on', models.DateTimeField(null=True)),
                ('coin_redemption', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CoinRedemption')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
