# Generated by Django 2.0 on 2018-01-30 19:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20180130_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='fulfillments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
