# Generated by Django 2.0 on 2018-01-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20180130_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='from_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
