# Generated by Django 2.1.7 on 2019-06-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20190617_1549'),
        ('dashboard', '0037_merge_20190624_1656'),
    ]

    operations = [
    ]
