# Generated by Django 2.0 on 2018-01-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_merge_20180122_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bounty_owner_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
