# Generated by Django 2.0 on 2018-01-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_bounty_bounty_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='claimee_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
