# Generated by Django 2.0.1 on 2018-02-01 16:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_tip_from_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyFulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('fulfiller_address', models.CharField(max_length=50)),
                ('fulfiller_email', models.CharField(blank=True, max_length=255)),
                ('fulfiller_github_username', models.CharField(blank=True, max_length=255)),
                ('fulfiller_name', models.CharField(blank=True, max_length=255)),
                ('fulfiller_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_address',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_email',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_github_username',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_metadata',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_name',
        ),
        migrations.AddField(
            model_name='bounty',
            name='fulfillments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='bountyfulfillment',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Bounty'),
        ),
    ]
