# Generated by Django 2.0 on 2018-02-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_tip_from_username'),
        ('dashboard', '0038_bounty_fulfillments'),
    ]

    operations = [
    ]
