# Generated by Django 2.0 on 2018-01-30 16:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_tip_from_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('action', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout')], max_length=50)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
