# Generated by Django 2.1.7 on 2019-07-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20190627_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='hourly_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hunter_hourly_rate',
            field=models.IntegerField(null=True),
        ),
    ]
