# Generated by Django 2.1.7 on 2019-07-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('dashboard', '0039_auto_20190706_0633'), ('dashboard', '0040_interest_hourly_contract')]

    dependencies = [
        ('dashboard', '0038_auto_20190627_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='hourly_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hunter_hourly_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='hourly_contract',
            field=models.BooleanField(default=False),
        ),
    ]
