# Generated by Django 2.1.7 on 2019-07-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20190709_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_wallpaper',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
