# Generated by Django 2.0.1 on 2018-02-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_migrate_fulfillments_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_address',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_email',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_github_username',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_metadata',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='fulfiller_name',
        ),
    ]
