# Generated by Django 2.0 on 2018-02-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_coinredemption_coinredemptionrequest'),
        ('dashboard', '0042_auto_20180201_1541'),
    ]

    operations = [
    ]
