# Generated by Django 2.0 on 2018-02-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_merge_20180215_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinredemption',
            options={'verbose_name_plural': 'Coin Redemptions'},
        ),
        migrations.AlterModelOptions(
            name='coinredemptionrequest',
            options={'verbose_name_plural': 'Coin Redemption Requests'},
        ),
    ]
