# Generated by Django 2.2.3 on 2019-07-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20190729_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='text_color',
            field=models.CharField(blank=True, help_text='hexcode for the text, default to black', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonevent',
            name='background_color',
            field=models.CharField(blank=True, help_text='hexcode for the banner, default to white', max_length=255, null=True),
        ),
    ]
