# Generated by Django 2.0 on 2018-02-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20180219_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='override_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tip',
            name='comments_priv',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tip',
            name='comments_public',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tip',
            name='from_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tip',
            name='from_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tip',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tip',
            name='from_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tip',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='receive_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tip',
            name='receive_txid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tip',
            name='received_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
