# Generated by Django 2.0.3 on 2018-03-19 20:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20180228_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='useraction',
            name='location_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
