# Generated by Django 2.2.3 on 2019-08-07 15:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20190803_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='text_color',
            field=models.CharField(blank=True, help_text='hexcode for the text, default to black', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('design', 'design'), ('documentation', 'documentation'), ('other', 'other')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='hackathonevent',
            name='background_color',
            field=models.CharField(blank=True, help_text='hexcode for the banner, default to white', max_length=7, null=True),
        ),
    ]
