# Generated by Django 2.0.3 on 2018-03-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20180318_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='stakeholders',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.DeleteModel(
            name='Stakeholder',
        ),
    ]
