# Generated by Django 2.2.3 on 2019-08-08 12:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20190807_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='bounty_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('design', 'design'), ('documentation', 'documentation'), ('other', 'other')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
