# Generated by Django 2.0.3 on 2018-03-21 00:19

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20180320_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_url', models.URLField(db_index=True)),
                ('current_funding', models.DecimalField(decimal_places=4, default=1, max_digits=50)),
                ('goal_funding', models.DecimalField(decimal_places=4, default=1, max_digits=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_address', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, to='dashboard.Stakeholder'),
        ),
    ]
