# Generated by Django 2.0.3 on 2018-03-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_bounty_last_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountyfulfillment',
            name='accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_type',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Security', 'Security'), ('Feature', 'Feature'), ('Unknown', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Unknown', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='last_comment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='project_length',
            field=models.CharField(blank=True, choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Unknown', 'Unknown')], max_length=50),
        ),
    ]
