# Generated by Django 2.1.7 on 2019-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_merge_20190808_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='idx_status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('done', 'done'), ('expired', 'expired'), ('reserved', 'reserved'), ('open', 'open'), ('started', 'started'), ('submitted', 'submitted'), ('unknown', 'unknown')], db_index=True, default='open', max_length=9),
        ),
    ]
