# Generated by Django 2.2.3 on 2019-08-28 08:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_merge_20190808_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_theme',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
