# Generated by Django 2.2.3 on 2019-08-23 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20190816_1645'),
        ('dashboard', '0048_merge_20190808_1934'),
    ]

    operations = [
    ]
