# Generated by Django 2.0.3 on 2018-03-21 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20180320_1719'),
        ('dashboard', '0048_grant'),
    ]

    operations = [
    ]
