# Generated by Django 2.0.3 on 2018-04-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20180328_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='idx_status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('done', 'done'), ('expired', 'expired'), ('open', 'open'), ('started', 'started'), ('submitted', 'submitted'), ('unknown', 'unknown')], db_index=True, default='open', max_length=9),
        ),
    ]
