# Generated by Django 2.2.3 on 2019-08-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_profile_custom_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='custom_theme',
            field=models.CharField(blank=True, default='light', max_length=50, null=True),
        ),
    ]
