# Generated by Django 2.0.3 on 2018-03-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_merge_20180320_1845'),
        ('dashboard', '0049_auto_20180328_0832'),
    ]

    operations = [
    ]
