# Generated by Django 2.0.3 on 2018-04-01 16:47

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20180328_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('url_name', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=255)),
                ('link_copy', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('stat_graph', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
