# Generated by Django 2.2.4 on 2019-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20190828_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='contract_version',
            field=models.CharField(blank=True, choices=[('2', '2'), ('1', '1')], default='1', max_length=5),
        ),
    ]
