# Generated by Django 2.0.3 on 2018-04-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20180320_1718'),
        ('dashboard', '0049_auto_20180328_0832'),
    ]

    operations = [
    ]
