# Generated by Django 2.1.7 on 2019-08-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20190822_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='reserved_for_user_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='reserved_for_user_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
