# Generated by Django 2.0.3 on 2018-03-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20180329_0654'),
        ('dashboard', '0049_auto_20180328_0832'),
    ]

    operations = [
    ]
