# Generated by Django 2.0.3 on 2018-04-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20180404_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pref_lang_code',
            field=models.CharField(default='en', max_length=2),
            preserve_default=False,
        ),
    ]
