# Generated by Django 2.0.3 on 2018-04-01 16:47

from django.db import migrations

def insert_tools(apps, schema_editor):
    Tool = apps.get_model('dashboard', 'Tool')

    #basics
    issue_explorer = Tool(name="Issue Explorer", category="BASIC", img="v2/images/why-different/code_great.png", description='''A searchable index of all of the funded work available in
                            the system.''', url_name="explorer", link_copy="Try It", active = True, stat_graph = "bounties_fulfilled" )
    issue_explorer.save()
    fund_work = Tool(name="Fund Work", category="BASIC", img="v2/images/tldr/bounties.jpg", description='''Got work that needs doing?  Create an issue and offer a bounty to get folks
                            working on it.''',
    url_name="new_funding", link_copy="Try It", active = False, stat_graph = "bounties_fulfilled" )
    fund_work.save()
    tips = Tool(name="Tips", category="BASIC", img="v2/images/tldr/tips.jpg", description='''Leave a tip to thank someone for
                        helping out.''',
    url_name="tip", link_copy="Try It", active = False, stat_graph = "tips" )
    tips.save()

    #advanced
    chrome_extension = Tool(name="Chrome Browser Extension", category="ADVANCED", img="v2/images/tools/browser_extension.png", description='''Browse Gitcoin where you already work.
                    On Github''',
    url_name="browser_extension", link_copy="Try It", active = False, stat_graph = "browser_ext_chrome" )
    chrome_extension.save()

    gitcoin_bot = Tool(name="gitcoinbot", category="ADVANCED", img="v2/images/helmet.png", description='''Chat Interface available on Github''',
    link="https://github.com/gitcoinco/web/tree/master/app/gitcoinbot", link_copy="Try It", active = False, stat_graph = "bot" )
    gitcoin_bot.save()
    
    
    #community
    slack_community = Tool(name="Slack Community", category="COMMUNITY", img="v2/images/social/slack2.png", description='''Questions / Discussion / Just say hi ? Swing by
                                our slack channel.''',
    url_name="slack", link_copy="Try It", active = False, stat_graph = "slack_users" )
    slack_community.save()

    gitter_community = Tool(name="Gitter Community", category="COMMUNITY", img="v2/images/social/gitter.png", description='''The gitter channel is less active than slack, but
                is still a good place to ask questions.''',
    url_name="gitter", link_copy="Try It", active = False, stat_graph = "gitter_users" )
    gitter_community.save()


    #tools to build

    github = Tool(name="Github Repos", category="TOOLS_TO_BUILD", img="v2/images/social/github.png", description='''All of our development is open source, and managed
              via Github.''',
    url_name="github", link_copy="Try It", active = False, stat_graph = "github_stargazers_count" )
    github.save()

    api = Tool(name="API", category="TOOLS_TO_BUILD", img="v2/images/tools/api.jpg", description='''Gitcoin provides a simple HTTPS API to access data
                            without having to run your own Ethereum node.''',
    link="https://github.com/gitcoinco/web/blob/master/readme_api.md#https-api", link_copy="Try It", active = True, stat_graph = "github_forks_count" )
    api.save()

    buidl = Tool(name="BUIDL your own", category="TOOLS_TO_BUILD", img="v2/images/dogfood.jpg", description='''Dogfood.. Yum! Gitcoin is built using Gitcoin.
                Got something you want to see in the world? Let the community know
                <a href="/slack">on slack</a>
                or <a href="https://github.com/gitcoinco/gitcoinco/issues/new">our github repos</a>
                .''',
    active = False, new = True )
    buidl.save()


    # alpha
    leaderboard = Tool(name="Leaderboard", category="ALPHA", img="v2/images/tools/leaderboard.png", description='''Check out who is topping the charts in
                the Gitcoin community this month.''',
    url_name="_leaderboard", link_copy="Try It", active = False, stat_graph = "bounties_fulfilled" )
    leaderboard.save()

    profiles = Tool(name="Profiles", category="ALPHA", img="v2/images/tools/profiles.png", description='''Browse the work that you\'ve done, and how your OSS repuation is growing. ''',
    url_name="profile", link_copy="Try It", active = True, stat_graph = "profiles_ingested" )
    profiles.save()

    tx_prefictor = Tool(name="ETH Tx Time Predictor", category="ALPHA", img="v2/images/tradeoffs.png", description='''Estimate Tradeoffs between Ethereum Network Tx Fees and Confirmation Times ''',
    url_name="gas", link_copy="Try It", active = True, stat_graph = "gas_page" )
    tx_prefictor.save()

    faucet = Tool(name="Faucet", category="ALPHA", img="v2/images/gas.svg", description='''Get Mainnet ETH which can be used in Gitcoin or other dapps.''',
    url_name="faucet", link_copy="Try It", active = True, stat_graph = "faucet_page" )
    faucet.save()

    sponsor = Tool(name="Code Sponsor", category="ALPHA", img="v2/images/codesponsor.jpg", description='''CodeSponsor sustains open source
                        by connecting sponsors with open source projects.''',
    link="https://codesponsor.io", link_copy="Try It", active = False, stat_graph = "codesponsor" )
    sponsor.save()

    bounties = Tool(name="Bounties Universe", category="ALPHA", img="v2/images/why-different/projects.jpg", description='''Bounties from around the internet''',
    url_name="universe_index", link_copy="Details", active = False, stat_graph = "na" )
    bounties.save()


    #coming soon
    ios_app = Tool(name="iOS app", category="COMING_SOON", img="v2/images/tools/iOS.png", description='''Gitcoin has an iOS app in alpha. Install it to
                    browse funded work on-the-go.''',
    url_name="ios", link_copy="Details", active = False, stat_graph = "ios_app_users" )
    ios_app.save()

    firefox_ext = Tool(name="Firefox Browser Extension", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''Firefox version of our browser extension''',
    link="https://github.com/gitcoinco/chrome_ext/issues/1", link_copy="Details", active = False, stat_graph = "na" )
    firefox_ext.save()

    email_gen = Tool(name="Cold Outreach Email Generator", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''Disrupt recruiters with this recruitment tool''',
    link="https://github.com/gitcoinco/skunkworks/issues/20", link_copy="Details", active = False, stat_graph = "na" )
    email_gen.save()

    mentorship = Tool(name="Mentorship Matcher", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''Matches Devs with Coaches''',
    link="https://github.com/gitcoinco/web/issues/565", link_copy="Details", active = False, stat_graph = "na" )
    mentorship.save()

    ethavatar = Tool(name="ETHAvatar", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''gravatar but for Ethereum addresses''',
    link="https://github.com/gitcoinco/skunkworks/issues/63", link_copy="Details", active = False, stat_graph = "na" )
    ethavatar.save()

    pitch = Tool(name="Pitch Page", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''Matches Entrepeneurs to Coding Tasks''',
    link="https://github.com/gitcoinco/web/issues/506", link_copy="Details", active = False, stat_graph = "na" )
    pitch.save()

    jobs = Tool(name="Job Board", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''What it sounds like!''',
    link="https://github.com/gitcoinco/web/issues/540", link_copy="Details", active = False, stat_graph = "na" )
    jobs.save()

    subdomains = Tool(name="<handle>.gitcoin.eth subdomains", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''Make it easy for friends to find you on ENS''',
    link="https://github.com/gitcoinco/web/issues/540", link_copy="Details", active = False, stat_graph = "na" )
    subdomains.save()

    top_secret = Tool(name="Top Secret Project 001", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''We can\'t talk about what it is yet :) ''',
    active = False, stat_graph = "na" )
    top_secret.save()

    coding_school = Tool(name="Web3 Coding School", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''Onboard developers from web2 to web3 with these coding challenges ''',
    link="https://github.com/gitcoinco/web/issues/631", link_copy="Details", active = False, stat_graph = "na" )
    coding_school.save()

    cold_outreach = Tool(name="Cold Outreach", category="COMING_SOON", img="v2/images/tools/comingsoon.png", description='''Cold Outreach emails that don't stink ''',
    link="https://github.com/gitcoinco/coldoutreach", link_copy="Details", active = False, stat_graph = "na" )
    cold_outreach.save()


    #fun
    wallpapers = Tool(name="Ethwallpaper", category="COMING_SOON", img="v2/images/tools/ethwallpaper.png", description='''Repository of
                        Ethereum wallpapers.''',
    link="https://ethwallpaper.co", link_copy="Try It", active = False, stat_graph = "google_analytics_sessions_ethwallpaper" )
    wallpapers.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_tool'),
    ]

    operations = [
        migrations.RunPython(insert_tools),
    ]
