# Generated by Django 2.0.3 on 2018-03-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_merge_20180329_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='pitch',
            field=models.CharField(default='', max_length=255),
        ),
    ]
