# Generated by Django 2.0.3 on 2018-04-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_merge_20180329_0708'),
        ('dashboard', '0050_auto_20180404_1109'),
    ]

    operations = [
    ]
