# Generated by Django 2.1.7 on 2019-08-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20190823_2017'),
        ('dashboard', '0049_auto_20190828_0322'),
    ]

    operations = [
    ]
