# Generated by Django 2.2.3 on 2019-09-03 21:02

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20190823_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='repos',
            field=models.ManyToManyField(blank=True, to='dashboard.Repo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='repos',
            field=models.ManyToManyField(blank=True, to='dashboard.Repo'),
        ),
    ]
