# Generated by Django 2.0.3 on 2018-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20180404_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suppress_leaderboard',
            field=models.BooleanField(default=False, help_text='If this option is chosen, we will remove your profile information from the leaderboard'),
        ),
    ]
