# Generated by Django 2.2.3 on 2019-09-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20190829_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dominant_persona',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('funder', 'Funder'), ('', 'Neither')], max_length=25),
        ),
    ]
