# Generated by Django 2.0.3 on 2018-04-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20180405_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='fulfillment_accepted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='fulfillment_submitted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
