# Generated by Django 2.2.3 on 2019-09-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_profile_dominant_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, help_text='the users activity level (high, low, new)', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='avg_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_repeated_relationships',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_rate',
            field=models.IntegerField(default=0),
        ),
    ]
