# Generated by Django 2.1.7 on 2019-09-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_merge_20190828_2048'),
        ('dashboard', '0050_searchhistory_search_type'),
    ]

    operations = [
    ]
