# Generated by Django 2.2.4 on 2019-09-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20190903_2102'),
        ('dashboard', '0050_searchhistory_search_type'),
    ]

    operations = [
    ]
