# Generated by Django 2.0.3 on 2018-03-30 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_grant_pitch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='stakeholders',
        ),
    ]
