# Generated by Django 2.0.3 on 2018-04-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20180401_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dashboard.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='votes',
            field=models.ManyToManyField(blank=True, to='dashboard.ToolVote'),
        ),
    ]
