# Generated by Django 2.0.3 on 2018-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20180412_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='fulfillment_started_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='fulfillment_accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='fulfillment_submitted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
