# Generated by Django 2.0.3 on 2018-03-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_remove_grant_stakeholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='current_funding',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='goal_funding',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=50),
        ),
    ]
