# Generated by Django 2.2.3 on 2019-09-09 20:26

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0052_auto_20190909_1822'),
    ]

    operations = [
    ]
