# Generated by Django 2.0.3 on 2018-04-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20180413_0736'),
        ('dashboard', '0051_profile_suppress_leaderboard'),
    ]

    operations = [
    ]
