# Generated by Django 2.0.3 on 2018-04-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20180401_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
    ]
