# Generated by Django 2.0.3 on 2018-04-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20180412_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='canceled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
