# Generated by Django 2.0.3 on 2018-04-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20180329_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='dashboard.Profile'),
        ),
    ]
