# Generated by Django 2.2.3 on 2019-09-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_searchhistory_search_type'),
        ('dashboard', '0053_repentry'),
    ]

    operations = [
    ]
