# Generated by Django 2.0.3 on 2018-04-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_tool_vote_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='vote_score',
        ),
    ]
