# Generated by Django 2.0.4 on 2018-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_merge_20180413_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountyfulfillment',
            name='fulfiller_github_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
