# Generated by Django 2.2.3 on 2019-09-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_merge_20190911_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackentry',
            name='private',
            field=models.BooleanField(default=True, help_text='whether this feedback can be shown publicly'),
        ),
    ]
