# Generated by Django 2.2.3 on 2019-10-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_auto_20190928_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred', to='dashboard.Profile'),
        ),
    ]
