# Generated by Django 2.0.4 on 2018-04-20 16:13

import app.storage
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_remove_bounty_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=app.storage.get_avatar_path),
        ),
    ]
