# Generated by Django 2.2.3 on 2019-09-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_feedbackentry_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_persona',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('funder', 'Funder'), ('', 'Neither')], max_length=25),
        ),
    ]
