# Generated by Django 2.2.4 on 2019-10-07 22:54

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_profile_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(help_text='Hackathon slug', max_length=255)),
                ('referer', models.URLField(blank=True, help_text='Url comes from', null=True)),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.HackathonEvent')),
                ('registrant', models.ForeignKey(help_text='User profile', on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_registration', to='dashboard.Profile')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='hackathons',
            field=models.ManyToManyField(blank=True, to='dashboard.HackathonRegistration'),
        ),
    ]
