# Generated by Django 2.0.4 on 2018-04-20 15:08

import app.storage
from django.db import migrations, models
import economy.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_remove_bounty_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('avatar', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=app.storage.get_avatar_path)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=app.storage.get_avatar_path),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', to='dashboard.Profile'),
        ),
    ]
