# Generated by Django 2.0.3 on 2018-04-19 09:10

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_remove_bounty_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('url_name', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=255)),
                ('link_copy', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('stat_graph', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dashboard.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='votes',
            field=models.ManyToManyField(blank=True, to='dashboard.ToolVote'),
        ),
    ]
