# Generated by Django 2.0.4 on 2018-04-23 13:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_remove_bounty_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='repos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='slack_channel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='slack_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
