# Generated by Django 2.2.3 on 2019-09-11 20:44

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_profile_selected_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_calc_date',
            field=models.DateTimeField(default=economy.models.get_time),
        ),
    ]
