# Generated by Django 2.2.3 on 2019-09-11 20:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_profile_last_calc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='as_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
