# Generated by Django 2.0.4 on 2018-04-23 17:59

from django.db import migrations, models


def migrate_tool_categories(apps, schema_editor):
    """Migrate Tool categories from original full string to two characters."""
    Tool = apps.get_model('dashboard', 'Tool')
    Tool.objects.filter(category='BASIC').update(category='BA')
    Tool.objects.filter(category='ADVANCED').update(category='AD')
    Tool.objects.filter(category='TOOLS_TO_BUILD').update(category='BU')
    Tool.objects.filter(category='COMMUNITY').update(category='CO')
    Tool.objects.filter(category='ALPHA').update(category='AL')
    Tool.objects.filter(category='COMING_SOON').update(category='CS')
    Tool.objects.filter(category='FOR_FUN').update(category='FF')


def update_eth_wallpaper(apps, schema_editor):
    """Migrate ethwallpaper tool to just for fun category."""
    Tool = apps.get_model('dashboard', 'Tool')
    Tool.objects.filter(name="Ethwallpaper").update(category='FF')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20180419_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('AD', 'ADVANCED'), ('AL', 'ALPHA'), ('BA', 'BASIC'), ('BU', 'TOOLS_TO_BUILD'), ('CS', 'COMING_SOON'), ('CO', 'COMMUNITY'), ('FF', 'FOR_FUN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='img',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tool',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tool',
            name='link_copy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(migrate_tool_categories),
        migrations.RunPython(update_eth_wallpaper),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('AD', 'ADVANCED'), ('AL', 'ALPHA'), ('BA', 'BASIC'), ('BU', 'TOOLS_TO_BUILD'), ('CS', 'COMING_SOON'), ('CO', 'COMMUNITY'), ('FF', 'FOR_FUN')], max_length=2),
        ),
    ]
