# Generated by Django 2.0.3 on 2018-04-23 17:45

from django.db import migrations


def update(apps, schema_editor):
    Tool = apps.get_model('dashboard', 'Tool')
    Tool.objects.filter(name="Ethwallpaper").update(category="FOR_FUN")


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20180419_0910'),
    ]

    operations = [
        migrations.RunPython(update),
    ]
