# Generated by Django 2.2.3 on 2019-09-11 23:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0058_profile_as_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='as_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('source_id', models.PositiveIntegerField()),
                ('network', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=500)),
                ('from_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_earnings', to='dashboard.Profile')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('to_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
