# Generated by Django 2.2.4 on 2019-10-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_auto_20190930_1525'),
        ('dashboard', '0058_auto_20191017_1723'),
    ]

    operations = [
    ]
