# Generated by Django 2.0.4 on 2018-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20180423_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountyfulfillment',
            name='fulfiller_hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
