# Generated by Django 2.2.4 on 2019-10-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_merge_20191022_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackathonregistration',
            options={},
        ),
    ]
