# Generated by Django 2.0.3 on 2018-04-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_tool_modifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pref_lang_code',
            field=models.CharField(choices=[('en', 'English')], default='en', max_length=2),
            preserve_default=False,
        ),
    ]
