# Generated by Django 2.2.3 on 2019-09-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0060_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='org_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_earnings', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='dashboard.Profile'),
        ),
    ]
