# Generated by Django 2.0.4 on 2018-04-24 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_tool_modifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slack_channel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='slack_repos',
            field=django.contrib.postgres.fields.ArrayField(
              base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='slack_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
