# Generated by Django 2.2.3 on 2019-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_auto_20190918_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rep',
        ),
        migrations.AddField(
            model_name='profile',
            name='reliability',
            field=models.CharField(blank=True, help_text='the users reliability level (high, medium, unproven)', max_length=10),
        ),
    ]
