# Generated by Django 2.0.4 on 2018-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_profile_pref_lang_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='has_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interest',
            name='issue_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
