# Generated by Django 2.0.4 on 2018-04-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_auto_20180427_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='has_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interest',
            name='issue_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
