# Generated by Django 2.2.4 on 2019-11-01 21:59

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_hackathonevent_show_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonproject',
            name='logo',
            field=models.ImageField(blank=True, help_text='Project Logo', null=True, upload_to=app.utils.get_upload_filename),
        ),
    ]
