# Generated by Django 2.2.4 on 2019-11-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_hackathonevent_show_results'),
        ('dashboard', '0061_blockedurlfilter'),
    ]

    operations = [
    ]
