# Generated by Django 2.0.3 on 2018-04-26 21:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_mentors_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='commitment_per_week',
            field=models.CharField(choices=[('1_5', '1 - 5'), ('5_10', '5 - 10'), ('10_15', '10 - 15'), ('15_20', '15 - 20'), ('20_', '20+')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(choices=[('1_5', '1 - 5'), ('5_10', '5 - 10'), ('10_15', '10 - 15'), ('15_20', '15 - 20'), ('20_', '20+')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='org',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], help_text='comma delimited', null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_offered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], help_text='comma delimited', null=True, size=None),
        ),
    ]
