# Generated by Django 2.2.3 on 2019-09-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_auto_20190919_1408'),
        ('dashboard', '0051_profile_gitcoin_discord_username'),
    ]

    operations = [
    ]
