# Generated by Django 2.2.4 on 2019-11-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_bounty_state'),
        ('dashboard', '0063_merge_20191120_1423'),
    ]

    operations = [
    ]
