# Generated by Django 2.2.3 on 2019-09-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_merge_20190919_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank_coder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank_funder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank_org',
            field=models.IntegerField(default=0),
        ),
    ]
