# Generated by Django 2.2.4 on 2019-11-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_profile_location'),
        ('dashboard', '0064_blockedurlfilter'),
    ]

    operations = [
    ]
