# Generated by Django 2.2.4 on 2019-11-27 04:49

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_blockedurlfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tribe_description',
            field=models.TextField(blank=True, default='', help_text='HTML rich description.'),
        ),
        migrations.CreateModel(
            name='TribeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('leader', models.BooleanField(default=False, help_text='tribe leader')),
                ('status', models.CharField(blank=True, choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=20)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='dashboard.Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
