# Generated by Django 2.0.5 on 2018-05-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_auto_20180430_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slack_channel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slack_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
