# Generated by Django 2.2.4 on 2019-11-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_blockedurlfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='description',
            field=models.TextField(blank=True, default='', help_text='HTML rich description.'),
        ),
    ]
