# Generated by Django 2.2.3 on 2019-09-20 02:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_auto_20190919_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('key', models.CharField(db_index=True, default='', max_length=50)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
