# Generated by Django 2.0.4 on 2018-05-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_auto_20180430_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='snooze_warnings_for_days',
            field=models.IntegerField(default=0),
        ),
    ]
