# Generated by Django 2.2.4 on 2019-11-21 20:37

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_blockedurlfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TribeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('leader', models.BooleanField(help_text='tribe leader')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='dashboard.Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
