# Generated by Django 2.0.4 on 2018-05-06 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_auto_20180430_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.URLField()),
                ('hat_long', models.URLField()),
                ('hat_short', models.URLField()),
                ('hair_long', models.URLField()),
                ('hair_short', models.URLField()),
                ('earring', models.URLField()),
                ('earring_back', models.URLField()),
                ('clothing', models.URLField()),
                ('ears', models.URLField()),
                ('beard', models.URLField()),
                ('mustache', models.URLField()),
                ('mouth', models.URLField()),
                ('nose', models.URLField()),
                ('eyes', models.URLField()),
                ('glasses', models.URLField()),
                ('background', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Avatar'),
        ),
    ]
