# Generated by Django 2.2.4 on 2019-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_merge_20191130_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
