# Generated by Django 2.2.4 on 2019-12-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20191127_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='quest_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
