# Generated by Django 2.0.5 on 2018-05-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20180504_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('added_slack_integration', 'Added Slack Integration'), ('removed_slack_integration', 'Removed Slack Integration')], max_length=50),
        ),
    ]
