# Generated by Django 2.0.4 on 2018-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20180505_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_profile',
            field=models.BooleanField(default=False, help_text='If this option is chosen, we will remove your profile information all_together'),
        ),
    ]
