# Generated by Django 2.2.4 on 2019-11-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_tribemember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribemember',
            name='leader',
            field=models.BooleanField(help_text='tribe leader', null=True),
        ),
    ]
