# Generated by Django 2.2.4 on 2019-12-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_hackathonevent_quest_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='automatic_backup',
            field=models.BooleanField(default=False, help_text='automatic backup profile to cloud storage such as 3Box if the flag is true'),
        ),
    ]
