# Generated by Django 2.2.4 on 2019-12-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_hackathonevent_quest_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='description',
            field=models.TextField(blank=True, default='', help_text='HTML rich description.'),
        ),
    ]
