# Generated by Django 2.2.4 on 2019-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_hackathonevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='bounty_owner_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
