# Generated by Django 2.2.4 on 2019-11-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_auto_20191125_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tribe_description',
            field=models.TextField(blank=True, default='', help_text='HTML rich description.'),
        ),
    ]
