# Generated by Django 2.2.4 on 2019-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20191211_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_wallet_address',
            field=models.BooleanField(default=True, help_text='If this option is chosen, we will remove your wallet information all together'),
        ),
    ]
