# Generated by Django 2.2.4 on 2019-12-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_profile_automatic_backup'),
        ('dashboard', '0068_auto_20191211_1458'),
    ]

    operations = [
    ]
