# Generated by Django 2.2.4 on 2020-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20191211_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='chat_channel_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
