# Generated by Django 2.0.4 on 2018-05-07 18:41

from django.db import migrations


def forwards_func(apps, schema_editor):
    Profile = apps.get_model('dashboard', 'Profile')
    profiles = Profile.objects.filter(github_access_token='').all()
    print(f"got {profiles.count()} profiles")
    for profile in profiles:
        if not getattr(profile, 'user', None):
            profile.hide_profile = True
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20180507_1841'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
        ),
    ]
