# Generated by Django 2.2.4 on 2019-12-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20191211_1458'),
        ('dashboard', '0066_profile_address'),
    ]

    operations = [
    ]
