# Generated by Django 2.2.4 on 2019-12-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20191211_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='payout_tx_id',
            field=models.CharField(blank=True, default='0x0', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='etc_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
