# Generated by Django 2.2.4 on 2019-12-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20191211_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backup_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='backup_bounties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='backup_interests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='backup_jobs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='backup_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='backup_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='backup_tips',
            field=models.BooleanField(default=False),
        ),
    ]
