# Generated by Django 2.2.4 on 2019-12-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20191211_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_theme',
            field=models.CharField(blank=True, default='light', max_length=50, null=True),
        ),
    ]
