# Generated by Django 2.0.4 on 2018-05-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20180507_1841'),
        ('dashboard', '0065_bounty_snooze_warnings_for_days'),
    ]

    operations = [
    ]
