# Generated by Django 2.2.4 on 2019-12-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20191218_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_backup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
