# Generated by Django 2.0.4 on 2018-05-07 21:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20180507_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='privacy_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
