# Generated by Django 2.0.5 on 2018-05-09 19:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20180507_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='snooze_warnings_for_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
