# Generated by Django 2.0.5 on 2018-05-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20180507_1841'),
        ('dashboard', '0065_auto_20180506_0528'),
    ]

    operations = [
    ]
