# Generated by Django 2.0.4 on 2018-05-09 14:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20180507_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='has_question',
        ),
        migrations.AlterField(
            model_name='bounty',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
