# Generated by Django 2.2.4 on 2019-12-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_profile_hide_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hide_wallet_address',
            field=models.BooleanField(default=True, help_text='If this option is chosen, we will remove your wallet information all together'),
        ),
    ]
