# Generated by Django 2.0.4 on 2018-05-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20180507_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='application_scheme',
            field=models.CharField(choices=[('permissionless', 'permissionless'), ('approval', 'approval')], default='permissionless', max_length=50),
        ),
        migrations.AddField(
            model_name='bounty',
            name='work_scheme',
            field=models.CharField(choices=[('traditional', 'traditional'), ('contest', 'contest'), ('cooperative', 'cooperative')], default='traditional', max_length=50),
        ),
    ]
