# Generated by Django 2.2.4 on 2020-01-19 10:17

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_auto_20200108_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, help_text='The image (jpeg, png, gif) url.', null=True, upload_to=app.utils.get_upload_filename),
        ),
    ]
