# Generated by Django 2.2.4 on 2020-01-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_auto_20200108_1527'),
        ('dashboard', '0070_activity_view_count'),
    ]

    operations = [
    ]
