# Generated by Django 2.2.4 on 2019-12-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_profile_last_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backup_acknowledgment',
            field=models.BooleanField(default=False),
        ),
    ]
