# Generated by Django 2.2.4 on 2020-01-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_auto_20200108_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='chat_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
