# Generated by Django 2.2.4 on 2019-12-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_profile_backup_acknowledgment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='backup_interests',
            new_name='backup_preferences',
        ),
    ]
