# Generated by Django 2.0.5 on 2018-05-09 20:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_bounty_snooze_warnings_for_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='privacy_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
