# Generated by Django 2.0.5 on 2018-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_bounty_privacy_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_num_issues_start_work',
            field=models.IntegerField(default=3),
        ),
    ]
