# Generated by Django 2.2.4 on 2020-01-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_auto_20200110_1720'),
        ('dashboard', '0071_merge_20200109_2043'),
    ]

    operations = [
    ]
