# Generated by Django 2.2.4 on 2020-01-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_profile_custom_theme'),
        ('dashboard', '0072_auto_20200110_1720'),
    ]

    operations = [
    ]
