# Generated by Django 2.0.5 on 2018-05-15 15:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_profile_max_num_issues_start_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='privacy_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
