# Generated by Django 2.0.5 on 2018-05-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_merge_20180508_2059'),
        ('dashboard', '0074_auto_20180515_1510'),
    ]

    operations = [
    ]
