# Generated by Django 2.0.5 on 2018-05-20 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20180515_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bounty_owner_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties_funded', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='tip',
            name='recipient_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tips', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='tip',
            name='sender_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tips', to='dashboard.Profile'),
        ),
    ]
