# Generated by Django 2.2.4 on 2020-01-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20200113_2241'),
        ('dashboard', '0073_merge_20200114_1638'),
    ]

    operations = [
    ]
