# Generated by Django 2.0.5 on 2018-05-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20180515_1510'),
        ('dashboard', '0070_auto_20180507_2327'),
    ]

    operations = [
    ]
