# Generated by Django 2.0.5 on 2018-05-10 23:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_mentors_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillNeeded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_skillneeded_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_skilloffered_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='commitment_per_week',
            field=models.CharField(blank=True, choices=[('1_5', '1 - 5'), ('5_10', '5 - 10'), ('10_15', '10 - 15'), ('15_20', '15 - 20'), ('20_', '20+')], max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, choices=[('1_5', '1 - 5'), ('5_10', '5 - 10'), ('10_15', '10 - 15'), ('15_20', '15 - 20'), ('20_', '20+')], max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='org',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skilloffered',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilloffered_offered', to='dashboard.SkillTag'),
        ),
        migrations.AddField(
            model_name='skillneeded',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillneeded_needed', to='dashboard.SkillTag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_needed',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='skills_needed', through='dashboard.SkillNeeded', to='dashboard.SkillTag', verbose_name='Skills needed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_offered',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='skills_offered', through='dashboard.SkillOffered', to='dashboard.SkillTag', verbose_name='Skills offered'),
        ),
    ]
