# Generated by Django 2.2.4 on 2020-01-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_activity_file'),
        ('dashboard', '0074_auto_20200113_2241'),
    ]

    operations = [
    ]
