# Generated by Django 2.0.5 on 2018-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20180515_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='application_scheme',
            field=models.CharField(choices=[('permissionless', 'permissionless'), ('approval', 'approval')], default='permissionless', max_length=50),
        ),
        migrations.AddField(
            model_name='bounty',
            name='work_scheme',
            field=models.CharField(choices=[('traditional', 'traditional'), ('contest', 'contest'), ('cooperative', 'cooperative')], default='traditional', max_length=50),
        ),
        migrations.AddField(
            model_name='interest',
            name='pending',
            field=models.BooleanField(default=False, help_text='If this option is chosen, this interest is pending and not yet active'),
        ),
    ]
