# Generated by Django 2.0.5 on 2018-05-20 03:57

from django.db import migrations


def migrate_bounty_owner_profile(apps, schema_editor):
    Bounty = apps.get_model('dashboard', 'Bounty')
    Profile = apps.get_model('dashboard', 'Profile')
    bounties = Bounty.objects.all()
    profiles = Profile.objects.all()

    for bounty in bounties:
        try:
            bounty.bounty_owner_profile = profiles.filter(handle=bounty.bounty_owner_github_username).latest('id')
            bounty.save()
        except Exception as e:
            print(f'Exception in dashboard migration 0076 - ({e}) - {bounty}')


def migrate_tip_profiles(apps, schema_editor):
    Tip = apps.get_model('dashboard', 'Tip')
    Profile = apps.get_model('dashboard', 'Profile')
    tips = Tip.objects.all()
    profiles = Profile.objects.all()

    for tip in tips:
        try:
            tip.recipient_profile = profiles.filter(handle=tip.username).latest('id')
            tip.sender_profile = profiles.filter(handle=tip.from_username).latest('id')
            tip.save()
        except Exception as e:
            print(f'Exception in dashboard migration 0076 - ({e}) - {tip}')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_auto_20180520_0349'),
    ]

    operations = [migrations.RunPython(migrate_bounty_owner_profile), migrations.RunPython(migrate_tip_profiles)]
