# Generated by Django 2.2.4 on 2020-01-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_auto_20200117_1441'),
        ('dashboard', '0075_auto_20200117_1650'),
    ]

    operations = [
    ]
