# Generated by Django 2.0.5 on 2018-05-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_auto_20180524_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trust_profile',
            field=models.BooleanField(default=False, help_text='If this option is chosen, the user is able to submit a faucet/ens domain registration even if they are new to github'),
        ),
    ]
