# Generated by Django 2.0.5 on 2018-05-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_merge_20180520_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='pending',
            field=models.BooleanField(default=False, help_text='If this option is chosen, this interest is pending and not yet active'),
        ),
    ]
