# Generated by Django 2.2.4 on 2020-01-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0076_merge_20200117_1700"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="kudos",
        ),
    ]
