# Generated by Django 2.2.4 on 2020-01-20 18:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_tippayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='as_representation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
