# Generated by Django 2.2.4 on 2020-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_profile_as_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='persona_is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dominant_persona',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('funder', 'Funder'), ('mentor', 'Mentor'), ('', 'Neither')], max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_persona',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('funder', 'Funder'), ('mentor', 'Mentor'), ('', 'Neither')], max_length=25),
        ),
    ]
