# Generated by Django 2.2.4 on 2020-01-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_profile_as_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_score',
            field=models.FloatField(default=0),
        ),
    ]
