# Generated by Django 2.2.4 on 2020-02-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_profile_as_representation'),
        ('dashboard', '0069_merge_20191212_2115'),
    ]

    operations = [
    ]
