# Generated by Django 2.2.4 on 2020-01-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_auto_20200112_1142'),
        ('dashboard', '0078_profile_as_representation'),
    ]

    operations = [
    ]
