# Generated by Django 2.2.4 on 2020-02-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0078_auto_20200117_1755"),
        ("dashboard", "0079_auto_20200204_0629"),
        ("dashboard", "0079_tribemember_title"),
    ]

    operations = []
