# Generated by Django 2.0.5 on 2018-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_auto_20180525_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pref_lang_code',
            field=models.CharField(blank=True, choices=[('en', 'English')], max_length=2),
        ),
    ]
