# Generated by Django 2.0.5 on 2018-05-31 00:53

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_auto_20180525_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('github_url', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('denomination', models.CharField(default='ETH', max_length=5)),
                ('status', models.CharField(choices=[('funded', 'funded'), ('unfunded', 'unfunded')], default='funded', max_length=1)),
                ('bounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='dashboard.Bounty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('created_on', models.DateField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.BountyRequest')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref_lang_code',
            field=models.CharField(blank=True, choices=[('en', 'English')], max_length=2),
        ),
        migrations.AddField(
            model_name='bountyrequest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_requests', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='bountyrequest',
            name='followers',
            field=models.ManyToManyField(to='dashboard.Profile'),
        ),
    ]
