# Generated by Django 2.2.4 on 2020-01-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_auto_20200123_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dominant_persona',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('funder', 'Funder'), ('mentor', 'Mentor'), ('', 'Neither')], max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_persona',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('funder', 'Funder'), ('mentor', 'Mentor'), ('', 'Neither')], max_length=25),
        ),
    ]
