# Generated by Django 2.0.5 on 2018-05-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_auto_20180531_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountyrequest',
            name='status',
            field=models.CharField(choices=[('funded', 'funded'), ('unfunded', 'unfunded')], default='funded', max_length=8),
        ),
    ]
