# Generated by Django 2.0.5 on 2018-05-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_profile_form_submission_records'),
        ('dashboard', '0080_auto_20180529_1508'),
    ]

    operations = [
    ]
