# Generated by Django 2.0.5 on 2018-06-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_merge_20180529_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='admin_override_and_hide',
            field=models.BooleanField(default=False, help_text='Admin override to hide the bounty from the system'),
        ),
    ]
