# Generated by Django 2.2.4 on 2020-02-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_auto_20200205_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='stream',
            field=models.BooleanField(default=False, help_text='Streaming Tips on Sablier if True'),
        ),
    ]
