# Generated by Django 2.0.5 on 2018-05-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_merge_20180529_2228'),
        ('dashboard', '0075_auto_20180523_0751'),
    ]

    operations = [
    ]
