# Generated by Django 2.0.5 on 2018-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_merge_20180529_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='permission_type',
            field=models.CharField(choices=[('permissionless', 'permissionless'), ('approval', 'approval')], default='permissionless', max_length=50),
        ),
        migrations.AddField(
            model_name='bounty',
            name='project_type',
            field=models.CharField(choices=[('traditional', 'traditional'), ('contest', 'contest'), ('cooperative', 'cooperative')], default='traditional', max_length=50),
        ),
        migrations.AddField(
            model_name='interest',
            name='pending',
            field=models.BooleanField(default=False, help_text='If this option is chosen, this interest is pending and not yet active'),
        ),
    ]
