# Generated by Django 2.2.4 on 2020-02-13 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_auto_20200211_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tribes_subscription',
        ),
        migrations.AlterField(
            model_name='tribessubscription',
            name='expires_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 12, 10, 50, 58, 37820, tzinfo=utc), null=True),
        ),
    ]
