# Generated by Django 2.0.5 on 2018-06-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_auto_20180528_1949'),
        ('dashboard', '0082_bounty_admin_override_and_hide'),
    ]

    operations = [
    ]
