# Generated by Django 2.0.5 on 2018-06-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_merge_20180601_1945'),
        ('dashboard', '0082_auto_20180531_1521'),
    ]

    operations = [
    ]
