# Generated by Django 2.0.5 on 2018-06-03 13:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_merge_20180601_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_repos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='discord_webhook_url',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_owner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties_funded', to='dashboard.Profile'),
        ),
    ]
