# Generated by Django 2.0.5 on 2018-06-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_merge_20180601_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='permission_type',
            field=models.CharField(choices=[('permissionless', 'permissionless'), ('approval', 'approval')], default='permissionless', max_length=50),
        ),
        migrations.AddField(
            model_name='bounty',
            name='project_type',
            field=models.CharField(choices=[('traditional', 'traditional'), ('contest', 'contest'), ('cooperative', 'cooperative')], default='traditional', max_length=50),
        ),
        migrations.AddField(
            model_name='interest',
            name='acceptance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='pending',
            field=models.BooleanField(default=False, help_text='If this option is chosen, this interest is pending and not yet active'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_owner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties_funded', to='dashboard.Profile'),
        ),
    ]
