# Generated by Django 2.2.4 on 2020-03-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_auto_20200226_0332'),
        ('dashboard', '0084_auto_20200227_1433'),
    ]

    operations = [
    ]
