# Generated by Django 2.0.6 on 2018-06-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_auto_20180531_0219'),
        ('dashboard', '0084_auto_20180604_1723'),
    ]

    operations = [
    ]
