# Generated by Django 2.0.6 on 2018-06-11 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_auto_20180604_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_repos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='discord_webhook_url',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
