# Generated by Django 2.2.4 on 2020-03-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_auto_20200226_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='payout_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='payout_tx_id',
            field=models.CharField(blank=True, default='0x0', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='etc_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
