# Generated by Django 2.0.5 on 2018-06-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_merge_20180604_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='acceptance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_owner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties_funded', to='dashboard.Profile'),
        ),
    ]
