# Generated by Django 2.2.4 on 2020-03-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_auto_20200226_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='chat_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathonproject',
            name='chat_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathonsponsor',
            name='chat_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gitcoin_chat_access_token',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
