# Generated by Django 2.2.4 on 2020-03-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_activity_hackathonevent'),
        ('dashboard', '0085_merge_20200303_2256'),
    ]

    operations = [
    ]
