# Generated by Django 2.2.4 on 2020-03-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_tip_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='confirmed',
        ),
    ]
