# Generated by Django 2.0.6 on 2018-06-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_auto_20180613_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('added_slack_integration', 'Added Slack Integration'), ('removed_slack_integration', 'Removed Slack Integration'), ('joined_livestream', 'Joined the Livestream')], max_length=50),
        ),
    ]
