# Generated by Django 2.2.4 on 2020-03-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_remove_tip_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
