# Generated by Django 2.0.6 on 2018-06-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_bounty_admin_override_suspend_auto_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='admin_mark_as_remarket_ready',
            field=models.BooleanField(default=False, help_text='Admin override to mark as remarketing ready'),
        ),
    ]
