# Generated by Django 2.0.6 on 2018-06-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_auto_20180613_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='attached_job_description',
            field=models.URLField(blank=True, null=True),
        ),
    ]
