# Generated by Django 2.2.4 on 2020-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_merge_20200309_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_chat_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
