# Generated by Django 2.2.4 on 2020-03-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_auto_20200309_1519'),
        ('dashboard', '0086_auto_20200301_1309'),
    ]

    operations = [
    ]
