# Generated by Django 2.0.7 on 2018-07-03 21:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_auto_20180621_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='idx_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
    ]
