# Generated by Django 2.2.4 on 2020-03-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_remove_tip_confirmed'),
        ('dashboard', '0085_merge_20200303_2256'),
    ]

    operations = [
    ]
