# Generated by Django 2.2.4 on 2020-03-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_merge_20200306_1954'),
        ('dashboard', '0088_auto_20200309_2046'),
    ]

    operations = [
    ]
