# Generated by Django 2.2.4 on 2020-03-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_auto_20200309_2046'),
        ('dashboard', '0085_auto_20200305_1508'),
    ]

    operations = [
    ]
