# Generated by Django 2.0.7 on 2018-07-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_auto_20180703_2056'),
        ('dashboard', '0088_activity'),
    ]

    operations = [
    ]
