# Generated by Django 2.2.4 on 2020-03-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_activity_hackathonevent'),
        ('dashboard', '0089_merge_20200304_1242'),
    ]

    operations = [
    ]
