# Generated by Django 2.0.7 on 2018-07-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_grant_stakeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
    ]
