# Generated by Django 2.2.4 on 2020-03-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_auto_20200312_0008'),
        ('dashboard', '0090_auto_20200313_1425'),
    ]

    operations = [
    ]
