# Generated by Django 2.0.7 on 2018-07-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_auto_20180709_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='web3_type',
            field=models.CharField(default='yge', max_length=50),
        ),
    ]
