# Generated by Django 2.2.4 on 2020-03-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_merge_20200306_1553'),
        ('dashboard', '0089_merge_20200307_2024'),
    ]

    operations = [
    ]
