# Generated by Django 2.2.4 on 2020-03-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_merge_20200309_0426'),
        ('dashboard', '0090_auto_20200313_1425'),
    ]

    operations = [
    ]
