# Generated by Django 2.2.4 on 2020-04-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_merge_20200405_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_chat_seen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_chat_status',
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='featured_logo_height',
            field=models.PositiveSmallIntegerField(default=0, help_text='Custom image max-height. Value of 0 removes the attribute from image. Anything above 0 sets the max-height. Field is set to 0 by default.'),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='featured_logo_width',
            field=models.PositiveSmallIntegerField(default=316, help_text='Custom image max-width. Default max-width of 316.'),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this hackathon on the hackathon list page.'),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='visible',
            field=models.BooleanField(default=True, help_text='Can this HackathonEvent be seeing on /hackathons ?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='avg feedback from those who theyve done work with', max_digits=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='earnings_count',
            field=models.IntegerField(db_index=True, default=0, help_text='How many times has user earned crypto with Gitcoin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='follower_count',
            field=models.IntegerField(db_index=True, default=0, help_text='how many users follow them'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.IntegerField(db_index=True, default=0, help_text='how many users are they following'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_org',
            field=models.BooleanField(db_index=True, default=True, help_text='Is this profile an org?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organizations_fk',
            field=models.ManyToManyField(blank=True, to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spent_count',
            field=models.IntegerField(db_index=True, default=0, help_text='How many times has user spent crypto with Gitcoin'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('wall_post', 'Wall Post'), ('status_update', 'Update status'), ('new_bounty', 'New Bounty'), ('start_work', 'Work Started'), ('stop_work', 'Work Stopped'), ('work_submitted', 'Work Submitted'), ('work_done', 'Work Done'), ('worker_approved', 'Worker Approved'), ('worker_rejected', 'Worker Rejected'), ('worker_applied', 'Worker Applied'), ('increased_bounty', 'Increased Funding'), ('killed_bounty', 'Canceled Bounty'), ('new_tip', 'New Tip'), ('receive_tip', 'Tip Received'), ('bounty_abandonment_escalation_to_mods', 'Escalated checkin from @gitcoinbot about bounty status'), ('bounty_abandonment_warning', 'Checkin from @gitcoinbot about bounty status'), ('bounty_removed_slashed_by_staff', 'Dinged and Removed from Bounty by Staff'), ('bounty_removed_by_staff', 'Removed from Bounty by Staff'), ('bounty_removed_by_funder', 'Removed from Bounty by Funder'), ('new_crowdfund', 'New Crowdfund Contribution'), ('new_grant', 'New Grant'), ('update_grant', 'Updated Grant'), ('killed_grant', 'Cancelled Grant'), ('negative_contribution', 'Negative Grant Contribution'), ('new_grant_contribution', 'Contributed to Grant'), ('new_grant_subscription', 'Subscribed to Grant'), ('killed_grant_contribution', 'Cancelled Grant Contribution'), ('new_milestone', 'New Milestone'), ('update_milestone', 'Updated Milestone'), ('new_kudos', 'New Kudos'), ('created_kudos', 'Created Kudos'), ('receive_kudos', 'Receive Kudos'), ('joined', 'Joined Gitcoin'), ('played_quest', 'Played Quest'), ('beat_quest', 'Beat Quest'), ('created_quest', 'Created Quest'), ('updated_avatar', 'Updated Avatar'), ('mini_clr_payout', 'Mini CLR Payout'), ('leaderboard_rank', 'Leaderboard Rank'), ('consolidated_leaderboard_rank', 'Consolidated Leaderboard Rank'), ('consolidated_mini_clr_payout', 'Consolidated CLR Payout'), ('hackathon_registration', 'Hackathon Registration'), ('flagged_grant', 'Flagged Grant')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hide_profile',
            field=models.BooleanField(db_index=True, default=True, help_text='If this option is chosen, we will remove your profile information all_together'),
        ),
    ]
