# Generated by Django 2.2.4 on 2020-03-18 00:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_merge_20200316_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='default_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='sponsor_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to={'data__type': 'Organization'}, to='dashboard.Profile'),
        ),
        migrations.CreateModel(
            name='HackathonSponsorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('chat_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hackathon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.HackathonEvent')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
