# Generated by Django 2.2.4 on 2020-03-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_merge_20200307_2111'),
        ('dashboard', '0089_merge_20200310_1649'),
    ]

    operations = [
    ]
