# Generated by Django 2.0.7 on 2018-07-09 19:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_tip_web3_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='tip',
            name='recipient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tips', to='dashboard.Profile'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tips', to='dashboard.Profile'),
        ),
    ]
