# Generated by Django 2.2.4 on 2020-03-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_merge_20200316_1102'),
        ('dashboard', '0090_auto_20200312_2055'),
    ]

    operations = [
    ]
