# Generated by Django 2.0.7 on 2018-07-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_auto_20180709_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='web3_type',
            field=models.CharField(default='v2', max_length=50),
        ),
    ]
