# Generated by Django 2.2.4 on 2020-03-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_merge_20200309_0453'),
    ]

    operations = [
    ]
