# Generated by Django 2.2.4 on 2020-03-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_merge_20200309_0334'),
        ('dashboard', '0091_merge_20200310_1136'),
    ]

    operations = [
    ]
