# Generated by Django 2.0.7 on 2018-07-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_auto_20180709_2116'),
        ('dashboard', '0087_bounty_attached_job_description'),
    ]

    operations = [
    ]
