# Generated by Django 2.2.4 on 2020-03-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_merge_20200317_2029'),
        ('dashboard', '0092_auto_20200316_2228'),
    ]

    operations = [
    ]
