# Generated by Django 2.0.7 on 2018-07-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_auto_20180713_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_payout_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
