# Generated by Django 2.2.4 on 2020-04-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_hackathonevent_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hackathonproject',
            name='looking_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathonproject',
            name='message',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
