# Generated by Django 2.2.4 on 2020-04-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_hackathonevent_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
