# Generated by Django 2.2.4 on 2020-04-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_hackathonevent_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this hackathon on the hackathon list page.'),
        ),
    ]
