# Generated by Django 2.2.4 on 2020-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_hackathonevent_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='featured_logo_height',
            field=models.PositiveSmallIntegerField(default=0, help_text='Custom image height. Value of 0 removes the attribute from image.Anything above 0 sets the height. Field is set to 0 by default.'),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='featured_logo_width',
            field=models.PositiveSmallIntegerField(default=316, help_text='Custom image width. Default width 316.'),
        ),
    ]
