# Generated by Django 2.2.4 on 2020-04-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_auto_20200318_0001'),
        ('dashboard', '0097_merge_20200408_1219'),
    ]

    operations = [
    ]
