# Generated by Django 2.0.7 on 2018-07-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_auto_20180715_0840'),
        ('dashboard', '0097_auto_20180717_0151'),
    ]

    operations = [
    ]
