# Generated by Django 2.2.4 on 2020-04-14 09:55

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_auto_20200413_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredSuggestedTribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribe', to='dashboard.Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_by', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
