# Generated by Django 2.0.7 on 2018-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_merge_20180719_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_tip_amount_usdt_per_tx',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_tip_amount_usdt_per_week',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=50),
        ),
        migrations.AlterField(
            model_name='tip',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tip',
            name='web3_type',
            field=models.CharField(default='v3', max_length=50),
        ),
    ]
