# Generated by Django 2.2.4 on 2020-04-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_auto_20200413_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefundFeeRequest',
        ),
    ]
