# Generated by Django 2.0.7 on 2018-08-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_auto_20180723_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('new_bounty', 'New Bounty'), ('start_work', 'Work Started'), ('stop_work', 'Work Stopped'), ('work_submitted', 'Work Submitted'), ('work_done', 'Work Done'), ('worker_approved', 'Worker Approved'), ('worker_rejected', 'Worker Rejected'), ('worker_applied', 'Worker Applied'), ('increased_bounty', 'Increased Funding'), ('killed_bounty', 'Canceled Bounty'), ('new_tip', 'New Tip'), ('receive_tip', 'Tip Received'), ('new_crowdfund', 'New Crowdfund Contribution')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref_lang_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('hi', 'Hindi'), ('it', 'Italian'), ('ko', 'Korean'), ('pl', 'Polish'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=2),
        ),
    ]
