# Generated by Django 2.2.4 on 2020-04-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_auto_20200413_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefundFeeRequest',
        ),
    ]
