# Generated by Django 2.2.4 on 2020-04-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_delete_refundfeerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='discord_repos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='discord_webhook_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gitcoin_discord_username',
        ),
    ]
