# Generated by Django 2.2.4 on 2020-04-17 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0100_delete_refundfeerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('poll_type', models.CharField(choices=[('HACKATHON', 'Hackathon')], max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.HackathonEvent')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Profile'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single Choice'), ('MUTIPLE_CHOICE', 'Multiple Choices'), ('OPEN', 'Open')], max_length=50)),
                ('text', models.CharField(blank=True, max_length=350, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Poll')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('text', models.CharField(blank=True, max_length=350, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HackathonOnboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('checkout_sponsor_date', models.DateField(null=True)),
                ('invite_friends_date', models.DateField(null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.HackathonEvent')),
                ('townsquare_publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Activity')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('open_response', models.CharField(blank=True, max_length=350, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Option')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
