# Generated by Django 2.0.7 on 2018-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_auto_20180801_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='tokenName',
            field=models.CharField(default='ETH', max_length=255),
        ),
    ]
