# Generated by Django 2.0.7 on 2018-08-02 14:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0101_auto_20180726_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='github_issue_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_payout_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
