# Generated by Django 2.0.7 on 2018-08-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_auto_20180802_1427'),
        ('dashboard', '0100_auto_20180801_2212'),
    ]

    operations = [
    ]
