# Generated by Django 2.2.4 on 2020-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_fundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
