# Generated by Django 2.2.4 on 2020-05-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_fundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='ends_soon_notified',
            field=models.BooleanField(db_index=True, default=False, help_text='48 hours before hackathon ends notification send'),
        ),
    ]
