# Generated by Django 2.1 on 2018-08-24 13:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_auto_20180815_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='funding_organisation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
