# Generated by Django 2.1 on 2018-08-20 21:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_auto_20180815_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='funding_organisation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='emails',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
