# Generated by Django 2.2.4 on 2020-05-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_auto_20200430_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='org_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_earnings', to='dashboard.Profile'),
        ),
    ]
