# Generated by Django 2.1 on 2018-08-20 23:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_auto_20180815_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='interested_comment',
            new_name='comment_id',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='submissions_comment',
        ),
        migrations.AlterField(
            model_name='tip',
            name='emails',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
