# Generated by Django 2.1.1 on 2018-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_auto_20180823_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pref_lang_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('hi', 'Hindi'), ('it', 'Italian'), ('ko', 'Korean'), ('pl', 'Polish'), ('ja', 'Japanese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=2),
        ),
    ]
