# Generated by Django 2.1 on 2018-08-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_auto_20180830_1946'),
        ('dashboard', '0106_auto_20180823_1626'),
    ]

    operations = [
    ]
