# Generated by Django 2.1 on 2018-08-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_auto_20180827_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funder_total_budget_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
