# Generated by Django 2.1.1 on 2018-09-06 15:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_auto_20180823_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bounty_reserved_for',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
