# Generated by Django 2.1.1 on 2018-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_auto_20180823_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bounty_reserved_for',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bounty',
            name='bounty_reserved_for_creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
