# Generated by Django 2.2.4 on 2020-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_auto_20200505_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='featured_logo_height',
            field=models.PositiveSmallIntegerField(default=0, help_text='Custom image max-height. Value of 0 removes the attribute from image. Anything above 0 sets the max-height. Field is set to 0 by default.'),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='featured_logo_width',
            field=models.PositiveSmallIntegerField(default=316, help_text='Custom image max-width. Default max-width of 316.'),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this hackathon on the hackathon list page.'),
        ),
    ]
