# Generated by Django 2.1 on 2018-08-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_auto_20180820_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='funding_organisation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
