# Generated by Django 2.1 on 2018-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0107_profile_funder_total_budget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funder_total_budget_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
