# Generated by Django 2.1.1 on 2018-09-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20180917_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bounty_reserved_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_bounties', to='dashboard.Profile'),
        ),
    ]
