# Generated by Django 2.2.4 on 2020-05-26 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20200513_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
