# Generated by Django 2.2.4 on 2020-05-15 08:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20200513_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonproject',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
