# Generated by Django 2.2.4 on 2020-02-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20200513_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='stream_id',
            field=models.PositiveIntegerField(blank=True, null=True)
        ),
    ]