# Generated by Django 2.1.1 on 2018-09-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20180917_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funder_total_budget_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='funder_total_budget_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='funder_total_budget_usdt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
