# Generated by Django 2.1 on 2018-09-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0001_initial'),
        ('dashboard', '0108_auto_20180831_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_kudos_wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_kudos_wallet', to='kudos.Wallet'),
        ),
    ]
