# Generated by Django 2.1.1 on 2018-09-20 10:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20180917_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyFunder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('reporter_comment', models.CharField(blank=True, max_length=255)),
                ('notify_reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('underfunded', 'underfunded'), ('underscoped', 'underscoped'), ('taken', 'taken'), ('abandoned', 'abandoned'), ('spam', 'spam')], max_length=20), blank=True, default=list, size=None)),
                ('funder_notified', models.BooleanField(default=False)),
                ('funder_ack', models.BooleanField(default=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='dashboard.Bounty')),
                ('reporter_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifier', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
