# Generated by Django 2.1 on 2018-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20180917_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='funding_organisation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
