# Generated by Django 2.1.2 on 2018-10-13 11:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_bounty_funding_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='tx_hashes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
