# Generated by Django 2.1.1 on 2018-10-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_bounty_funding_organisation'),
        ('dashboard', '0109_profile_preferred_kudos_wallet'),
    ]

    operations = [
    ]
