# Generated by Django 2.1.2 on 2018-10-19 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0001_initial'),
        ('dashboard', '0109_bounty_funding_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_kudos_wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_kudos_wallet', to='kudos.Wallet'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='expires_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tokenName',
            field=models.CharField(default='ETH', max_length=255),
        ),
    ]
