# Generated by Django 2.1.1 on 2018-09-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_bounty_funding_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='utm_campaign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraction',
            name='utm_medium',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraction',
            name='utm_source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
