# Generated by Django 2.1.1 on 2018-09-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_bounty_funding_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountyfulfillment',
            name='funder_last_notified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
