# Generated by Django 2.2.4 on 2020-05-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_investigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, null=True),
        ),
    ]
