# Generated by Django 2.1.1 on 2018-10-03 13:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_bounty_funding_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='utm_campaign',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='useraction',
            name='utm_medium',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraction',
            name='utm_source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
