# Generated by Django 2.1.2 on 2018-11-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20181027_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='receive_tx_status',
            field=models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error')], db_index=True, default='na', max_length=9),
        ),
        migrations.AddField(
            model_name='tip',
            name='tx_status',
            field=models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error')], db_index=True, default='na', max_length=9),
        ),
    ]
