# Generated by Django 2.2.4 on 2020-05-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20200517_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountyfulfillment',
            name='fulfiller_email',
        ),
        migrations.RemoveField(
            model_name='bountyfulfillment',
            name='fulfiller_github_username',
        ),
        migrations.RemoveField(
            model_name='bountyfulfillment',
            name='fulfiller_name',
        ),
    ]
