# Generated by Django 2.1.1 on 2018-10-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_bountyfulfillment_funder_last_notified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='funder_last_messaged_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
