# Generated by Django 2.2.4 on 2020-05-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20200519_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountyfulfillment',
            name='fulfiller_email',
        ),
        migrations.RemoveField(
            model_name='bountyfulfillment',
            name='fulfiller_github_username',
        ),
        migrations.RemoveField(
            model_name='bountyfulfillment',
            name='fulfiller_name',
        ),
    ]
