# Generated by Django 2.1.2 on 2018-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20181005_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bountyfulfillment',
            old_name='fulfiller_last_notified_on',
            new_name='funder_last_notified_on',
        ),
        migrations.AddField(
            model_name='bounty',
            name='funder_last_messaged_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
