# Generated by Django 2.1.1 on 2018-09-25 17:49

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('dashboard', '0110_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='bounty_tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
