# Generated by Django 2.1.2 on 2018-11-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_auto_20181101_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
