# Generated by Django 2.2.4 on 2020-05-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_auto_20200520_0457'),
        ('dashboard', '0109_auto_20200519_0226'),
    ]

    operations = [
    ]
