# Generated by Django 2.1.2 on 2018-11-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_useraction_utm'),
        ('dashboard', '0112_auto_20181107_2208'),
    ]

    operations = [
    ]
