# Generated by Django 2.2.4 on 2020-05-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20200518_2331'),
        ('dashboard', '0112_auto_20200520_1454'),
    ]

    operations = [
    ]
