# Generated by Django 2.1.2 on 2018-11-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0113_merge_20181109_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
