# Generated by Django 2.1.2 on 2018-11-14 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0113_merge_20181109_1753'),
        ('dashboard', '0111_auto_20181015_2336'),
    ]

    operations = [
    ]
