# Generated by Django 2.2.4 on 2020-05-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_auto_20200527_0740'),
        ('dashboard', '0114_auto_20200522_0730'),
    ]

    operations = [
    ]
