# Generated by Django 2.1.2 on 2018-11-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_auto_20181113_0512'),
        ('dashboard', '0114_merge_20181114_2340'),
    ]

    operations = [
    ]
