# Generated by Django 2.1.2 on 2018-11-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_auto_20181113_0512'),
        ('dashboard', '0111_auto_20181102_1308'),
    ]

    operations = [
    ]
