# Generated by Django 2.1.2 on 2018-11-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_searchhistory'),
        ('dashboard', '0115_merge_20181114_2349'),
    ]

    operations = [
    ]
