# Generated by Django 2.2.4 on 2020-05-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0115_auto_20200526_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sms_verification',
            field=models.BooleanField(default=False, help_text='SMS verification process'),
        ),
    ]
