# Generated by Django 2.2.4 on 2020-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_auto_20200528_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='short_code',
            field=models.CharField(default='', help_text='used in the chat for better channel grouping', max_length=5),
        ),
    ]
