# Generated by Django 2.1.2 on 2018-11-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_merge_20181115_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='primary_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
