# Generated by Django 2.1.2 on 2018-11-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_auto_20181124_2228'),
        ('dashboard', '0116_merge_20181115_2252'),
    ]

    operations = [
    ]
