# Generated by Django 2.2.4 on 2020-06-04 06:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_auto_20200528_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonproject',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
