# Generated by Django 2.1.2 on 2018-11-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_merge_20181115_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funder_total_budget_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='funder_total_budget_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='funder_total_budget_usdt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
