# Generated by Django 2.1.2 on 2018-11-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_merge_20181115_2252'),
        ('dashboard', '0116_auto_20181124_2228'),
    ]

    operations = [
    ]
