# Generated by Django 2.1.2 on 2018-11-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0117_auto_20181116_1054'),
        ('dashboard', '0117_merge_20181126_0303'),
    ]

    operations = [
    ]
