# Generated by Django 2.2.4 on 2020-06-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0117_hackathonproject_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='tip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Tip'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='receive_tx_status',
            field=models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped'), ('not_subed', 'not_subed')], db_index=True, default='na', max_length=9),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tx_status',
            field=models.CharField(choices=[('na', 'na'), ('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('unknown', 'unknown'), ('dropped', 'dropped'), ('not_subed', 'not_subed')], db_index=True, default='na', max_length=9),
        ),
    ]
