# Generated by Django 2.2.4 on 2020-06-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20200607_1455'),
        ('dashboard', '0118_auto_20200605_1302'),
    ]

    operations = [
    ]
