# Generated by Django 2.1.2 on 2018-11-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0117_merge_20181125_0123'),
        ('dashboard', '0118_merge_20181126_1948'),
    ]

    operations = [
    ]
