# Generated by Django 2.2.4 on 2020-06-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_auto_20200609_1944'),
        ('dashboard', '0119_auto_20200605_2036'),
    ]

    operations = [
    ]
