# Generated by Django 2.1.2 on 2018-11-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0117_tip_primary_email'),
        ('dashboard', '0119_merge_20181126_2023'),
    ]

    operations = [
    ]
