# Generated by Django 2.2.4 on 2020-06-15 19:18

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_auto_20200605_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('comments', models.TextField(blank=True, default='', help_text='The comments.')),
                ('processed', models.BooleanField(default=False, help_text='Was it processed?')),
                ('comments_admin', models.TextField(blank=True, default='', help_text='The comments of an admin.')),
                ('contribution', models.ForeignKey(help_text='The associated Grant.', on_delete=django.db.models.deletion.CASCADE, related_name='contribution_flag', to='dashboard.Earning')),
                ('profile', models.ForeignKey(help_text="The flagger's profile.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_flags', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
