# Generated by Django 2.2.4 on 2020-06-10 20:08

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_profile_sms_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encoded_number',
            field=models.CharField(blank=True, help_text='Number with the user validate the account', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_validation_request',
            field=models.DateTimeField(blank=True, help_text='When the user requested a code for last time ', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='validation_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of generated SMS codes to validate account'),
        ),
        migrations.CreateModel(
            name='ProfileVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('caller_type', models.CharField(blank=True, max_length=20, null=True)),
                ('carrier_error_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_network_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_country_code', models.PositiveSmallIntegerField(default=0, null=True)),
                ('carrier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_type', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
