# Generated by Django 2.2.4 on 2020-06-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_auto_20200605_2036'),
        ('dashboard', '0120_auto_20200610_2008'),
    ]

    operations = [
    ]
