# Generated by Django 2.1.2 on 2018-11-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0115_auto_20181127_0046'),
        ('dashboard', '0120_merge_20181126_2232'),
    ]

    operations = [
    ]
