# Generated by Django 2.2.4 on 2020-06-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_profile_pref_do_not_track'),
        ('dashboard', '0120_auto_20200612_0207'),
    ]

    operations = [
    ]
