# Generated by Django 2.1.2 on 2018-11-27 00:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0121_merge_20181127_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
    ]
