# Generated by Django 2.2.4 on 2020-06-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0121_merge_20200612_0200'),
        ('dashboard', '0119_profile_pref_do_not_track'),
    ]

    operations = [
    ]
