# Generated by Django 2.2.4 on 2020-06-15 22:10

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0122_merge_20200612_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encoded_number',
            field=models.CharField(blank=True, help_text='Number with the user validate the account', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_validation_request',
            field=models.DateTimeField(blank=True, help_text='When the user requested a code for last time ', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_verification',
            field=models.BooleanField(default=False, help_text='SMS verification process'),
        ),
        migrations.AddField(
            model_name='profile',
            name='validation_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of generated SMS codes to validate account'),
        ),
        migrations.CreateModel(
            name='ProfileVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('caller_type', models.CharField(blank=True, max_length=20, null=True)),
                ('carrier_error_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_network_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_country_code', models.PositiveSmallIntegerField(default=0, null=True)),
                ('carrier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_type', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContributionFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('comments', models.TextField(blank=True, default='', help_text='The comments.')),
                ('processed', models.BooleanField(default=False, help_text='Was it processed?')),
                ('comments_admin', models.TextField(blank=True, default='', help_text='The comments of an admin.')),
                ('contribution', models.ForeignKey(help_text='The associated Grant.', on_delete=django.db.models.deletion.CASCADE, related_name='contribution_flag', to='dashboard.Earning')),
                ('profile', models.ForeignKey(help_text="The flagger's profile.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_flags', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
