# Generated by Django 2.1.2 on 2018-11-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_auto_20181128_1545'),
        ('dashboard', '0117_labsresearch'),
    ]

    operations = [
    ]
