# Generated by Django 2.1.2 on 2018-11-29 23:47

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_auto_20181128_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('handle', models.CharField(db_index=True, max_length=255, unique=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(help_text='Is the block active?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
