# Generated by Django 2.2.4 on 2020-06-23 21:48

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_auto_20200617_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='featured_logo_height',
            field=models.PositiveSmallIntegerField(default=0, help_text='Custom image max-height. Value of 0 removes the attribute from image. Anything above 0 sets the max-height. Field is set to 0 by default.'),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='featured_logo_width',
            field=models.PositiveSmallIntegerField(default=316, help_text='Custom image max-width. Default max-width of 316.'),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this hackathon on the hackathon list page.'),
        ),
        migrations.CreateModel(
            name='HackathonWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('cover', models.ImageField(upload_to='')),
                ('url', models.URLField(help_text='Blog link, calendar link, or other.')),
                ('visible', models.BooleanField(default=True, help_text='Can this HackathonWorkshop be seen on /hackathons ?')),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_event', to='dashboard.HackathonEvent')),
                ('speaker', models.ForeignKey(help_text='Main speaker profile.', on_delete=django.db.models.deletion.CASCADE, related_name='workshop_speaker', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
