# Generated by Django 2.1.2 on 2018-11-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_auto_20181128_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
