# Generated by Django 2.2.4 on 2020-06-29 11:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_auto_20200617_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='showcase',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
