# Generated by Django 2.1.2 on 2018-11-29 23:47

from django.db import migrations


def forwards_func(apps, schema_editor):
    BlockedUser = apps.get_model('dashboard', 'BlockedUser')
    handles = [ 'lazaridiscom', 'NOTLAZ', 'omidmahboubian']
    for handle in handles:
        BlockedUser.objects.create(
            handle=handle,
            active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0124_blockeduser'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
        ),
    ]
