# Generated by Django 2.1.2 on 2018-11-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0125_auto_20181129_2347'),
    ]

    operations = [
    ]
