# Generated by Django 2.1.2 on 2018-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0125_blockeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabsResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('link', models.URLField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='labs')),
            ],
        ),
    ]
