# Generated by Django 2.2.4 on 2020-07-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_auto_20200708_0906'),
        ('dashboard', '0126_profile_is_tribe'),
    ]

    operations = [
    ]
