# Generated by Django 2.1.2 on 2018-12-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_labsresearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsresearch',
            name='upcoming',
            field=models.BooleanField(default=True),
        ),
    ]
