# Generated by Django 2.1.2 on 2018-12-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_auto_20181205_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='looking_for_work',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for_work_public',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
