# Generated by Django 2.1.2 on 2018-12-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_labsresearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsresearch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='labs'),
        ),
    ]
