# Generated by Django 2.1.2 on 2018-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_labsresearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='canceled_bounty_reason',
            field=models.TextField(blank=True, default='', verbose_name='Cancelation reason'),
        ),
    ]
