# Generated by Django 2.2.4 on 2020-07-09 13:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0127_merge_20200709_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='showcase',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
