# Generated by Django 2.1.2 on 2018-12-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20181005_1854'),
        ('dashboard', '0127_auto_20181212_2124'),
    ]

    operations = [
    ]
