# Generated by Django 2.2.4 on 2020-07-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0128_hackathonevent_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_ghost_account',
            field=models.BooleanField(default=False),
        ),
    ]
