# Generated by Django 2.1.2 on 2018-12-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0128_merge_20181212_2243'),
        ('dashboard', '0002_auto_20181226_1716'),
    ]

    operations = [
    ]
