# Generated by Django 2.2.4 on 2020-07-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0128_hackathonevent_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='display_showcase',
            field=models.BooleanField(default=False),
        ),
    ]
