# Generated by Django 2.2.4 on 2020-07-27 11:54

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0129_tribessubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ignore_tribes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tribessubscription',
            name='expires_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 27, 11, 54, 40, 625983), null=True),
        ),
    ]
