# Generated by Django 2.2.4 on 2020-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0129_hackathonworkshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='hackathon_summary',
            field=models.CharField(blank=True, help_text='280 char summary that shows up on hackathon cards on the hackathon list page', max_length=280),
        ),
    ]
