# Generated by Django 2.2.4 on 2020-07-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0129_profile_active_ghost_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ghost_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_accounts', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_ghost_account',
            field=models.BooleanField(default=False),
        ),
    ]
