# Generated by Django 2.2.4 on 2020-07-27 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0129_tribessubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='hackathon_summary',
            field=models.CharField(blank=True, help_text='280 char summary that shows up on hackathon cards on the hackathon list page', max_length=280),
        ),
        migrations.AlterField(
            model_name='tribessubscription',
            name='expires_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 27, 10, 42, 37, 39263, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='HackathonWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('cover', models.ImageField(upload_to='')),
                ('url', models.URLField(help_text='Blog link, calendar link, or other.')),
                ('visible', models.BooleanField(default=True, help_text='Can this HackathonWorkshop be seen on /hackathons ?')),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_event', to='dashboard.HackathonEvent')),
                ('speaker', models.ForeignKey(help_text='Main speaker profile.', on_delete=django.db.models.deletion.CASCADE, related_name='workshop_speaker', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
