# Generated by Django 2.2.4 on 2020-07-27 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0129_tribessubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='hyper_next_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='hypercharge_mode',
            field=models.BooleanField(default=True, help_text='This bounty will be part of the hypercharged bounties'),
        ),
        migrations.AlterField(
            model_name='tribessubscription',
            name='expires_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 27, 11, 32, 58, 290457), null=True),
        ),
    ]
