# Generated by Django 2.2.4 on 2020-07-27 15:15

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0130_auto_20200727_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ignore_tribes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
