# Generated by Django 2.2.4 on 2020-07-29 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0130_auto_20200727_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ignore_tribes',
            field=models.ManyToManyField(related_name='ignore', to='dashboard.Profile'),
        ),
    ]
