# Generated by Django 2.2.4 on 2020-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0130_auto_20200714_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sigin_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
