# Generated by Django 2.2.4 on 2020-08-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0137_auto_20200806_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='minimum_character_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
