# Generated by Django 2.2.4 on 2020-08-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0138_auto_20200810_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='minimum_character_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
