# Generated by Django 2.2.4 on 2020-08-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0139_auto_20200811_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountyfulfillment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='dashboard.HackathonProject'),
        ),
    ]
