# Generated by Django 2.2.4 on 2020-08-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0140_bountyfulfillment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountyfulfillment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='dashboard.HackathonProject'),
        ),
    ]
