# Generated by Django 2.2.4 on 2020-09-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0143_userdirectory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdirectory',
            options={'managed': True},
        ),
    ]
