# Generated by Django 2.2.4 on 2020-09-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0148_add_brightid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonproject',
            name='grant_link',
            field=models.URLField(blank=True, db_index=True, help_text='Grant Link', null=True),
        ),
    ]
