# Generated by Django 2.2.4 on 2020-09-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0076_matchpledge_data'),
        ('dashboard', '0148_add_brightid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonproject',
            name='grant_link',
            field=models.ForeignKey(blank=True, help_text='Link to grant if project is converted to grant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.Grant'),
        ),
    ]
