# Generated by Django 2.2.4 on 2020-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0149_hackathonproject_grant_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonproject',
            name='grant_link',
            field=models.CharField(blank=True, db_index=True, help_text='Grant Link', max_length=255, null=True),
        ),
    ]
