# Generated by Django 2.2.4 on 2020-09-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0150_auto_20200913_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonproject',
            name='grant_link',
            field=models.ForeignKey(help_text='Link to grant if project is converted to grant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.Grant'),
        ),
    ]
