# Generated by Django 2.2.4 on 2020-09-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0150_auto_20200904_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
