# Generated by Django 2.2.4 on 2020-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0152_auto_20200930_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='use_circle',
            field=models.BooleanField(default=False, help_text='Use circle for the Hackathon'),
        ),
    ]
