# Generated by Django 2.2.4 on 2020-10-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0153_hackathonevent_use_circle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='bounty_owner_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bountyfulfillment',
            name='fulfiller_address',
            field=models.CharField(blank=True, help_text='address to which amount is credited', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bountyfulfillment',
            name='funder_address',
            field=models.CharField(blank=True, help_text='address from which amount is deducted', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bountyfulfillment',
            name='tenant',
            field=models.CharField(blank=True, choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('ETC', 'ETC'), ('ZIL', 'ZIL'), ('CELO', 'CELO'), ('PYPL', 'PYPL'), ('POLKADOT', 'POLKADOT'), ('FILECOIN', 'FILECOIN'), ('OTHERS', 'OTHERS')], help_text='specific tenant type under the payout_type', max_length=10, null=True),
        ),
    ]
