# Generated by Django 2.2.4 on 2020-10-11 22:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0153_hackathonevent_use_circle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('txid', models.CharField(default='', max_length=255)),
                ('status', models.CharField(db_index=True, default='', max_length=50)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('network', models.CharField(blank=True, db_index=True, max_length=255)),
                ('captured_at', models.DateTimeField()),
                ('earning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.Earning')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
