# Generated by Django 2.2.4 on 2020-10-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0088_auto_20200924_1536'),
        ('dashboard', '0153_hackathonevent_use_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonproject',
            name='grant_obj',
            field=models.ForeignKey(blank=True, help_text='Link to grant if project is converted to grant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.Grant'),
        ),
    ]
