# Generated by Django 2.2.4 on 2020-10-14 09:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0154_profile_override_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_poap_verified',
            field=models.BooleanField(default=False),
        )
    ]
