# Generated by Django 2.2.4 on 2020-10-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0154_profile_idena_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idena_token',
            field=models.UUIDField(null=True),
        ),
    ]
