# Generated by Django 2.2.4 on 2020-10-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0154_transactionhistory'),
        ('dashboard', '0154_profile_override_dict'),
    ]

    operations = [
    ]
