# Generated by Django 2.2.4 on 2020-10-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0154_hackathonproject_grant_obj'),
        ('dashboard', '0154_auto_20201012_1044'),
        ('dashboard', '0155_merge_20201014_1258'),
    ]

    operations = [
    ]
