# Generated by Django 2.2.4 on 2020-10-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0155_auto_20201014_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_wallet_address_anonymized',
            field=models.BooleanField(default=False, help_text="If this option is chosen, Gitcoin will hide your wallet address in it's UI/APIs, even in instances in which it's anonymized"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hide_wallet_address',
            field=models.BooleanField(default=True, help_text="If this option is chosen, Gitcoin will hide your wallet address in it's UI/APIs wherever it's associated with your handle or other PIA (personally identifiable information) wherever possible."),
        ),
    ]
