# Generated by Django 2.2.4 on 2020-10-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0156_auto_20201015_1742'),
        ('dashboard', '0154_transactionhistory'),
    ]

    operations = [
    ]
