# Generated by Django 2.2.4 on 2020-10-09 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0156_populate_profile_idena_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idena_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
