# Generated by Django 2.2.4 on 2020-10-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0156_auto_20201015_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonproject',
            name='status',
            field=models.CharField(blank=True, choices=[('invalid', 'invalid'), ('pending', 'pending'), ('accepted', 'accepted'), ('completed', 'completed')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hackathonproject',
            name='winner',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
