# Generated by Django 2.2.4 on 2020-10-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0157_profile_idena_token_index_and_defualt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_idena_connected',
            field=models.BooleanField(default=False),
        ),
    ]
