# Generated by Django 2.2.4 on 2020-10-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0157_auto_20201016_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_observed_payout_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
