# Generated by Django 2.2.4 on 2020-10-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0158_profile_anonymize_gitcoin_grants_contributions_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_observed_payout_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
