# Generated by Django 2.2.4 on 2020-11-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0161_auto_20201111_1318'),
        ('dashboard', '0160_auto_20201111_0445'),
    ]

    operations = [
    ]
