# Generated by Django 2.2.4 on 2020-11-12 16:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0161_auto_20201111_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identity_data_google',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
