# Generated by Django 2.2.4 on 2020-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0162_auto_20201112_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idena_address',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idena_status',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_idena_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_idena_verified',
            field=models.BooleanField(default=False),
        ),
    ]
