# Generated by Django 2.2.4 on 2020-11-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0162_auto_20201112_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ens_verification_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_ens_verified',
            field=models.BooleanField(default=False),
        ),
    ]
