# Generated by Django 2.2.4 on 2020-11-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0162_merge_20201112_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_duniter_verified',
            field=models.BooleanField(default=False),
        ),
    ]
