# Generated by Django 2.2.4 on 2020-11-26 03:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0163_auto_20201123_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ens_verification_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
