# Generated by Django 2.2.4 on 2020-11-30 11:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0163_profile_is_facebook_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identity_data_facebook',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
