# Generated by Django 2.2.4 on 2020-11-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0163_profile_is_duniter_verified'),
        ('dashboard', '0162_auto_20201112_1639'),
    ]

    operations = [
    ]
