# Generated by Django 2.2.4 on 2020-12-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0165_mediafile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idena_address',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idena_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
