# Generated by Django 2.2.4 on 2020-12-01 16:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0165_mediafile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identity_data_facebook',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_facebook_verified',
            field=models.BooleanField(default=False),
        ),
    ]
