# Generated by Django 2.2.4 on 2020-12-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0165_mediafile_filename'),
        ('dashboard', '0164_merge_20201113_0140'),
    ]

    operations = [
    ]
