# Generated by Django 2.2.4 on 2020-12-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0165_mediafile_filename'),
        ('dashboard', '0163_profile_is_idx_verified'),
    ]

    operations = [
    ]
