# Generated by Django 2.2.4 on 2020-12-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0166_merge_20201201_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_discord_verified',
            field=models.BooleanField(default=False),
        ),
    ]
