# Generated by Django 2.2.4 on 2021-01-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0168_auto_20201216_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Is this user upgraded to pro?'),
            preserve_default=False,
        ),
    ]
