# Generated by Django 2.2.4 on 2020-12-04 02:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0157_auto_20201021_2319'),
        ('dashboard', '0167_hackathonevent_metadata'),
    ]

    operations = []
