# Generated by Django 2.2.4 on 2021-01-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0168_auto_20201216_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mautic_id',
            field=models.CharField(blank=True, db_index=True, help_text='Mautic id to be able to do api requests without user being logged', max_length=128, null=True),
        ),
    ]
