# Generated by Django 2.2.4 on 2021-01-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0166_auto_20201201_1642'),
        ('dashboard', '0168_auto_20201216_2058'),
    ]

    operations = [
    ]
