# Generated by Django 2.2.4 on 2021-01-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0168_auto_20201216_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mautic_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
