# Generated by Django 2.2.4 on 2021-02-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0169_profile_mautic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Is this user upgraded to pro?'),
        ),
    ]
