# Generated by Django 2.2.4 on 2021-01-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0169_profile_mautic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mautic_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
