# Generated by Django 2.2.4 on 2021-02-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0170_profile_is_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountyevent',
            name='event_type',
            field=models.CharField(choices=[('accept_worker', 'Accept Worker'), ('cancel_bounty', 'Cancel Bounty'), ('submit_work', 'Submit Work'), ('stop_work', 'Stop Work'), ('stop_worker', 'Worker stopped'), ('express_interest', 'Express Interest'), ('payout_bounty', 'Payout Bounty'), ('expire_bounty', 'Expire Bounty'), ('extend_expiration', 'Extend Expiration'), ('close_bounty', 'Close Bounty'), ('worker_paid', 'Worker Paid')], max_length=50),
        ),
    ]
