# Generated by Django 2.2.4 on 2021-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0173_earning_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='poap_owner_account',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
