# Generated by Django 2.2.4 on 2021-03-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0173_earning_success'),
        ('dashboard', '0173_auto_20210312_2236'),
    ]

    operations = [
    ]
