# Generated by Django 2.2.4 on 2021-03-17 17:31
from collections import defaultdict

from django.db import migrations, models, IntegrityError, transaction


def populate_google_id(apps, schema_editor):
    from dashboard.models import Profile

    profiles_with_google_connection = Profile.objects.filter(is_google_verified=True)
    count_google_ids = defaultdict(int)

    for profile in profiles_with_google_connection:
        profile.google_user_id = profile.identity_data_google['id']
        count_google_ids[profile.google_user_id] += 1

    for google_id, count in count_google_ids.items():
        if count <= 1:
            continue
        
        # Drop google trust badge for everyone with dupplicate google id
        for profile in profiles_with_google_connection:
            if profile.google_user_id == google_id:
                profile.google_user_id = None
                profile.is_google_verified = False
                profile.identity_data_google = {}

    for profile in profiles_with_google_connection:
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0173_earning_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.RunPython(populate_google_id),
    ]
