# Generated by Django 2.2.20 on 2021-04-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0176_auto_20210409_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='poap_owner_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
