# Generated by Django 2.2.4 on 2021-04-24 05:34

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0178_auto_20210422_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_user_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
