# Generated by Django 2.2.20 on 2021-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0179_auto_20210424_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_poh_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='poh_handle',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
