# Generated by Django 2.2.20 on 2021-06-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0181_auto_20210611_0309'),
        ('dashboard', '0181_auto_20210613_1449'),
    ]

    operations = [
    ]
