# Generated by Django 2.2.21 on 2021-06-22 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0182_merge_20210618_1119'),
        ('dashboard', '0182_merge_20210618_1522'),
    ]

    operations = [
    ]
