# Generated by Django 2.2.24 on 2021-07-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0183_auto_20210701_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='total_prize',
            field=models.CharField(blank=True, help_text='extra text to display next the event dates on the hackathon list page', max_length=255, null=True),
        ),
    ]
