# Generated by Django 2.2.24 on 2021-09-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0185_auto_20210823_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='comments_priv',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='tip',
            name='network',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
