# Generated by Django 2.2.24 on 2021-09-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0187_auto_20210928_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tribe_priority',
        ),
    ]
