# Generated by Django 2.2.24 on 2021-10-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0187_auto_20210928_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribemember',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], db_index=True, max_length=20),
        ),
    ]
