# Generated by Django 2.2.24 on 2021-10-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0189_auto_20211001_1905'),
        ('dashboard', '0188_auto_20211002_0156'),
    ]

    operations = [
    ]
