# Generated by Django 2.2.24 on 2021-10-07 14:09

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0190_merge_20211004_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('key', models.CharField(choices=[('grants', 'grants'), ('hackathons', 'hackathons'), ('tips', 'tips'), ('kudos', 'kudos'), ('quests', 'quests'), ('profiles', 'profiles'), ('platform', 'platform'), ('others', 'others')], db_index=True, max_length=255)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_index', to='dashboard.Activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
