# Generated by Django 2.2.24 on 2021-10-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0190_merge_20211004_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs_bounties', to='dashboard.Profile'),
        ),
    ]
