# Generated by Django 2.2.24 on 2021-10-12 15:09

from django.db import migrations

def forwards(apps, schema_editor):
    Bounty = apps.get_model('dashboard', 'Bounty')
    for bounty in Bounty.objects.filter(current_bounty=True):
        print(bounty.pk)
        bounty.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0191_bounty_org'),
    ]

    operations = [
         migrations.RunPython(forwards, backwards),
    ]
