# Generated by Django 2.2.24 on 2021-10-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0193_activityindex'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activityindex',
            index=models.Index(fields=['id', 'key'], name='dashboard_a_id_0b0371_idx'),
        ),
    ]
