# Generated by Django 2.2.24 on 2021-11-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0194_auto_20211029_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name_plural': 'Search History'},
        ),
    ]
