# Generated by Django 2.2.24 on 2021-11-29 07:31

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0196_profile_trust_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_index', to='dashboard.Activity')),
            ],
        ),
        migrations.AddIndex(
            model_name='activityindex',
            index=models.Index(fields=['id', 'key'], name='dashboard_a_id_0b0371_idx'),
        ),
    ]
