# Generated by Django 2.2.24 on 2021-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0197_auto_20211129_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_index',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
