# Generated by Django 2.2.24 on 2022-02-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0198_profile_email_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='bounty_owner_address',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='is_open',
            field=models.BooleanField(db_index=True, help_text='Whether the bounty is still open for fulfillments.'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='project_length',
            field=models.CharField(blank=True, choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Unknown', 'Unknown')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='standard_bounties_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
