# Generated by Django 2.2.24 on 2022-03-23 09:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0199_auto_20220210_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='contact_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bounty',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
