# Generated by Django 2.2.24 on 2022-04-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0200_auto_20220420_0228'),
        ('dashboard', '0200_auto_20220420_0336'),
    ]

    operations = [
    ]
