# Generated by Django 2.2.24 on 2022-03-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0200_auto_20220323_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The description of the Bounty.'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='description_rich',
            field=models.TextField(blank=True, default='', help_text='HTML rich description.'),
        ),
    ]
