# Generated by Django 2.2.24 on 2022-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0201_auto_20220323_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='description',
            new_name='custom_description',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='description_rich',
            new_name='custom_description_rich',
        ),
        migrations.AddField(
            model_name='bounty',
            name='custom_title',
            field=models.CharField(blank=True, default='', help_text='The title of the Bounty.', max_length=200),
        ),
    ]
