# Generated by Django 2.2.24 on 2022-05-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0203_auto_20220523_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='did',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dpopp_trust_bonus',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Trust Bonus score based on dpopp passport', max_digits=5),
        ),
    ]
