# Generated by Django 2.2.24 on 2022-05-23 11:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0203_auto_20220518_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dpopp_passport',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dpopp_trust_bonus',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Trust Bonus score based on verified services', max_digits=5),
        ),
    ]
