# Generated by Django 2.2.24 on 2022-05-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0204_auto_20220525_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportstamp',
            name='passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='dashboard.Passport'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dpopp_trust_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Trust Bonus score based on dpopp passport', max_digits=5, null=True),
        ),
    ]
