# Generated by Django 2.2.24 on 2022-03-28 15:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0204_auto_20220324_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='acceptance_criteria',
            field=models.TextField(blank=True, default='', help_text='Acceptance criteria', null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='contact_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='custom_description',
            field=models.TextField(blank=True, default='', help_text='The description of the Bounty', null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='custom_description_rich',
            field=models.TextField(blank=True, default='', help_text='HTML rich description', null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='custom_title',
            field=models.CharField(blank=True, default='', help_text='The title of the Bounty', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='resources',
            field=models.TextField(blank=True, default='', help_text='Resources', null=True),
        ),
    ]
