# Generated by Django 2.2.24 on 2022-05-24 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0205_passportstampregistry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassportStampRegistry',
            new_name='PassportStamp',
        ),
    ]
