# Generated by Django 2.2.24 on 2022-05-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0206_auto_20220526_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_trust_bonus_last_updated',
            field=models.DateTimeField(blank=True, help_text='Trust Bonus score last updated datetime', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_trust_bonus_status',
            field=models.CharField(blank=True, help_text='Trust Bonus score update status', max_length=14, null=True),
        ),
    ]
