# Generated by Django 2.2.24 on 2022-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0207_auto_20220530_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport_trust_bonus_status',
            field=models.CharField(blank=True, help_text='Trust Bonus score update status', max_length=255, null=True),
        ),
    ]
