# Generated by Django 2.2.24 on 2022-06-29 09:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0208_auto_20220616_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_trust_bonus_stamp_validation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
