# Generated by Django 2.2.24 on 2022-07-18 13:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0209_profile_passport_trust_bonus_stamp_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportstamp',
            name='stamp_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='passportstamp',
            name='stamp_credential',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='passportstamp',
            name='stamp_provider',
            field=models.CharField(db_index=True, default="", max_length=256),
        ),
    ]
