# Generated by Django 2.2.24 on 2022-07-14 11:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0209_profile_passport_trust_bonus_stamp_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportstamp',
            name='stamp_credential',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='passportstamp',
            name='stamp_provider',
            field=models.CharField(default=False, max_length=256),
        ),
    ]
