# Generated by Django 2.1.4 on 2019-01-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_ethdenver2019', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_ethdenver2019_customizing_kudos',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
