# Generated by Django 2.1.7 on 2019-04-30 19:36

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('from_amount', models.FloatField()),
                ('to_amount', models.FloatField()),
                ('conversion_rate', models.FloatField()),
                ('txid', models.CharField(db_index=True, max_length=30)),
                ('transaction_date', models.DateTimeField(db_index=True)),
                ('from_token_addr', models.CharField(db_index=True, max_length=30)),
                ('to_token_symbol', models.CharField(db_index=True, max_length=10)),
                ('from_token_symbol', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
