# Generated by Django 2.1.7 on 2019-05-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeswapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyconversion',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='currencyconversion',
            name='modified_on',
        ),
    ]
