# Generated by Django 2.1.7 on 2019-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeswapper', '0003_auto_20190501_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='from_token_addr',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='currencyconversion',
            name='txid',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
